// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// BoxTrapperBlacklistMessagesArgs are the parameters of the UAPI function `BoxTrapper::blacklist_messages`.
type BoxTrapperBlacklistMessagesArgs struct {
	// The email address for which to blacklist messages.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated user.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The filename of the email message to blacklist.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// BlacklistMessages calls the UAPI function `BoxTrapper::blacklist_messages` — Add email address to BoxTrapper blocked senders
//
// This function blacklists email message senders.
//
// **Important:**
//
//   When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system disables this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) BlacklistMessages(ctx context.Context, args *BoxTrapperBlacklistMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperBlacklistMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperBlacklistMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "blacklist_messages", args)
}


// BoxTrapperBlacklistMessagesDataItem is a generated payload type.
type BoxTrapperBlacklistMessagesDataItem struct {
	// The email address that sent the blacklisted message.
	Email    string `json:"email"`

	// Whether the system failed to blacklist the message.
	//
	// **Note:**
	//
	//  The function only returns this value if it doesn't blacklist the message.
	//
	// Possible values: `1`.
	Failed   int64 `json:"failed"`

	// An array of messages that the system deleted.
	Matches  []string `json:"matches"`

	// The action that the function performed.
	//
	// Possible values: `blacklist`.
	Operator string `json:"operator"`

	// A message about the failure or the warning.
	//
	// **Note:**
	//
	//  The function only returns this value if it doesn't delete the message or experiences issues when it deletes the message.
	Reason   string `json:"reason"`

	// Whether the system experienced issues when it blacklisted the message.
	//
	// **Note:**
	//
	//  The function only returns this value if it doesn't blacklist the message.
	//
	// Possible values: `1`.
	Warning  int64 `json:"warning"`
}

// BoxTrapperDeleteMessagesArgs are the parameters of the UAPI function `BoxTrapper::delete_messages`.
type BoxTrapperDeleteMessagesArgs struct {
	// The account's email address.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The filename of the email message who's sender to delete.
	//
	//   **Warning:**
	//
	//  To delete multiple email message senders, duplicate the parameter name.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// Whether to delete all messages that resemble the `queuefile` parameter's value.
	//
	// * `1` - Delete all messages resembling the `queuefile` parameter.
	// * `0` - Do **not** delete all messages resembling the `queuefile` parameter.
	//
	// Possible values: `1`, `0`.
	//
	// Defaults to `0`.
	AllLike *int64 `cpanel:"all_like,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeleteMessages calls the UAPI function `BoxTrapper::delete_messages` — Delete messages in the BoxTrapper queue
//
// This function deletes messages in the BoxTrapper queue.
//
// **Important:**
//
// When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system disables this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) DeleteMessages(ctx context.Context, args *BoxTrapperDeleteMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperDeleteMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperDeleteMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "delete_messages", args)
}


// BoxTrapperDeleteMessagesDataItem is a generated payload type.
type BoxTrapperDeleteMessagesDataItem struct {
	// The deleted email message's sender.
	Email    string `json:"email"`

	// Whether the system failed to delete the messages.
	//
	// **Note:**
	//
	// The function only returns this value if it doesn't delete the message.
	//
	// Possible values: `1`.
	Failed   int64 `json:"failed"`

	// An array of messages that the system deleted.
	Matches  []string `json:"matches"`

	// The operation that the system performed.
	//
	// Possible values: `delete`.
	Operator string `json:"operator"`

	// A message about the failure or the warning.
	//
	// **Note:**
	//
	// The function only returns this value if it doesn't delete the message or experiences issues when it deletes the message.
	Reason   string `json:"reason"`

	// Whether the system experienced issues when it deleted the message.
	//
	// **Note:**
	//
	// The function only returns this value if it experiences issues when it deletes the message.
	//
	// Possible values: `1`.
	Warning  int64 `json:"warning"`
}

// BoxTrapperDeliverMessagesArgs are the parameters of the UAPI function `BoxTrapper::deliver_messages`.
type BoxTrapperDeliverMessagesArgs struct {
	// The sender's cPanel account email address for which to deliver email messages.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter
	// and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The filename of the email messages to deliver.
	//
	// **Note:**
	//
	// To deliver multiple email messages, pass this parameter multiple times.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// Whether to deliver all messages that resemble the `queuefile` parameter's value.
	//
	// * `1` - Deliver all similar messages.
	// * `0` - Don't deliver all similar messages.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AllLike *int64 `cpanel:"all_like,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeliverMessages calls the UAPI function `BoxTrapper::deliver_messages` — Send messages in the BoxTrapper queue
//
// This function delivers messages in the BoxTrapper queue.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) DeliverMessages(ctx context.Context, args *BoxTrapperDeliverMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperDeliverMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperDeliverMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "deliver_messages", args)
}


// BoxTrapperDeliverMessagesDataItem is a generated payload type.
type BoxTrapperDeliverMessagesDataItem struct {
	// The delivered email message's sender.
	Email    string `json:"email"`

	// Whether the system could not deliver the message.
	//
	// **Note:**
	//
	//  * The function only returns this value if it doesn't deliver the message.
	//  * `1` is the only possible value.
	//
	// Possible values: `1`.
	Failed   int64 `json:"failed"`

	// A list of delivered email messages.
	Matches  []string `json:"matches"`

	// The action that the function performed.
	//
	// * `deliver`
	// * `deliverall`
	//
	// Possible values: `deliver`, `deliverall`.
	Operator string `json:"operator"`

	// A message about the failure or the warning.
	//
	// **Note:**
	//
	// The function only returns this value if it doesn't delete the message or experiences
	// issues when it deletes the message.
	Reason   string `json:"reason"`

	// Whether the system experienced issues when it delivered the message.
	//
	// **Note:**
	//
	//  * The function only returns this value if it experiences issues when it delivers the message.
	//  * `1` is the only possible value.
	//
	// Possible values: `1`.
	Warning  int64 `json:"warning"`
}

// BoxTrapperGetAllowlistArgs are the parameters of the UAPI function `BoxTrapper::get_allowlist`.
type BoxTrapperGetAllowlistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetAllowlist calls the UAPI function `BoxTrapper::get_allowlist` — Return account BoxTrapper allowlist rules
//
// This function retrieves a list of BoxTrapper allowlist configuration rules. BoxTrapper will deliver emails that match these rules.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetAllowlist(ctx context.Context, args *BoxTrapperGetAllowlistArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "BoxTrapper", "get_allowlist", args)
}


// BoxTrapperGetBlocklistArgs are the parameters of the UAPI function `BoxTrapper::get_blocklist`.
type BoxTrapperGetBlocklistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetBlocklist calls the UAPI function `BoxTrapper::get_blocklist` — Return account BoxTrapper blocklist rules
//
// This function retrieves a list of BoxTrapper blocklist configuration rules. BoxTrapper will delete messages that match these rules and send a notification to the sender.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetBlocklist(ctx context.Context, args *BoxTrapperGetBlocklistArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "BoxTrapper", "get_blocklist", args)
}


// BoxTrapperGetConfigurationArgs are the parameters of the UAPI function `BoxTrapper::get_configuration`.
type BoxTrapperGetConfigurationArgs struct {
	// The account's email address.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetConfiguration calls the UAPI function `BoxTrapper::get_configuration` — Return email account's BoxTrapper configuration
//
// This function retrieves an account's BoxTrapper configuration.
//
// **Important:**
//
//   When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system disables this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetConfiguration(ctx context.Context, args *BoxTrapperGetConfigurationArgs) (*cpanel.UAPIResult[BoxTrapperGetConfigurationData], error) {
	return cpanel.UAPICall[BoxTrapperGetConfigurationData](ctx, c.c, http.MethodGet, "BoxTrapper", "get_configuration", args)
}


// BoxTrapperGetConfigurationData is a generated payload type.
type BoxTrapperGetConfigurationData struct {
	// Whether whitelisting is enabled.
	// * 1 - Enabled.
	// * 0 - Disabled.
	//
	// Possible values: `0`, `1`.
	EnableAutoWhitelist    int64 `json:"enable_auto_whitelist"`

	// The email addresses that send emails from the account. A comma-separated list of email addresses.
	FromAddresses          string `json:"from_addresses"`

	// The name of the person who owns the email account.
	FromName               string `json:"from_name"`

	// The number of days that the system retains log files and queued messages.
	QueueDays              int64 `json:"queue_days"`

	// The account's [Apache SpamAssassin](https://go.cpanel.net/cpaneldocsSpamFilters) threshold score.
	SpamScore              float64 `json:"spam_score"`

	// Whether the system whitelisted the email addresses in a message's `To` and `From` sections, including carbon-copied (CC) recipients.
	//
	// Possible values: `0`, `1`.
	WhitelistByAssociation int64 `json:"whitelist_by_association"`
}

// BoxTrapperGetEmailTemplateArgs are the parameters of the UAPI function `BoxTrapper::get_email_template`.
type BoxTrapperGetEmailTemplateArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The message template.
	//
	// * `blacklist`
	// * `returnverify`
	// * `verifyreleased`
	// * `verify`
	//
	// **Note:**
	//
	// For more information on each template, read our
	// [BoxTrapper](https://go.cpanel.net/cpaneldocsBoxTrapper) documentation.
	//
	// Possible values: `blacklist`, `returnverify`, `verifyreleased`, `verify`.
	//
	// This parameter is required.
	Template string `cpanel:"template"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetEmailTemplate calls the UAPI function `BoxTrapper::get_email_template` — Return specified BoxTrapper email template
//
// This function retrieves a BoxTrapper email message template.
//
// **Important:**
//
//   When you disable the
//   [*Receive Mail* role](https://go.cpanel.net/serverroles),
//   the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetEmailTemplate(ctx context.Context, args *BoxTrapperGetEmailTemplateArgs) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "BoxTrapper", "get_email_template", args)
}


// BoxTrapperGetForwardersArgs are the parameters of the UAPI function `BoxTrapper::get_forwarders`.
type BoxTrapperGetForwardersArgs struct {
	// The account's email address.
	//
	// **Important:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetForwarders calls the UAPI function `BoxTrapper::get_forwarders` — Return all BoxTrapper forwarders
//
// This function retrieves a list of email addresses to which BoxTrapper forwards email messages.
//
// **Important:**
//
// When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 86.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetForwarders(ctx context.Context, args *BoxTrapperGetForwardersArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "BoxTrapper", "get_forwarders", args)
}


// BoxTrapperGetIgnorelistArgs are the parameters of the UAPI function `BoxTrapper::get_ignorelist`.
type BoxTrapperGetIgnorelistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetIgnorelist calls the UAPI function `BoxTrapper::get_ignorelist` — Return account BoxTrapper ignorelist rules
//
// This function retrieves a list of BoxTrapper ignorelist configuration rules. BoxTrapper will delete messages that match these rules without sending a notification to the sender.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetIgnorelist(ctx context.Context, args *BoxTrapperGetIgnorelistArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "BoxTrapper", "get_ignorelist", args)
}


// BoxTrapperGetLogArgs are the parameters of the UAPI function `BoxTrapper::get_log`.
type BoxTrapperGetLogArgs struct {
	// The account's email address.
	//
	// **Important:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The date for which to return the log file and its contents.
	//
	// **Note:**
	//
	// This parameter defaults to the current date.
	Date *int64 `cpanel:"date,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetLog calls the UAPI function `BoxTrapper::get_log` — Return BoxTrapper log file and contents
//
// This function returns the account's BoxTrapper log file and its contents.
//
// **Important:**
//
// When you disable the [Receive Mail role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetLog(ctx context.Context, args *BoxTrapperGetLogArgs) (*cpanel.UAPIResult[BoxTrapperGetLogData], error) {
	return cpanel.UAPICall[BoxTrapperGetLogData](ctx, c.c, http.MethodGet, "BoxTrapper", "get_log", args)
}


// BoxTrapperGetLogData is a generated payload type.
type BoxTrapperGetLogData struct {
	// The date for which the system returned the log.
	Date  int64 `json:"date"`

	// An array of lines from the log file. If the log file doesn't exist or if no log lines exist in the file, the function returns an empty array.
	Lines []string `json:"lines"`

	// The log file's filepath. If the log file doesn't exist, the function returns an empty string.
	Path  string `json:"path"`
}

// BoxTrapperGetMessageArgs are the parameters of the UAPI function `BoxTrapper::get_message`.
type BoxTrapperGetMessageArgs struct {
	// The account’s name, either an email address or the cPanel user’s username.
	//
	// **Important:**
	//
	//  If you call this function in Webmail, the system ignores this parameter.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The message's filename.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetMessage calls the UAPI function `BoxTrapper::get_message` — Return message's top 200 lines in BoxTrapper queue
//
// This function returns the first 200 lines of an email in the BoxTrapper queue.
//
// **Important:**
//
// When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetMessage(ctx context.Context, args *BoxTrapperGetMessageArgs) (*cpanel.UAPIResult[BoxTrapperGetMessageData], error) {
	return cpanel.UAPICall[BoxTrapperGetMessageData](ctx, c.c, http.MethodGet, "BoxTrapper", "get_message", args)
}


// BoxTrapperGetMessageData is a generated payload type.
type BoxTrapperGetMessageData struct {
	// The email message's contents. Up to the first 200 lines of an email message.
	Content   string `json:"content"`

	Contents  json.RawMessage `json:"contents"`

	// The message's filename.
	QueueFile string `json:"queuefile"`
}

// BoxTrapperGetStatusArgs are the parameters of the UAPI function `BoxTrapper::get_status`.
type BoxTrapperGetStatusArgs struct {
	// The account's email address.
	//
	// **Important:**
	//
	// If you call this function in Webmail, the system ignores this parameter.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetStatus calls the UAPI function `BoxTrapper::get_status` — Return whether email account uses BoxTrapper
//
// This function checks whether BoxTrapper is enabled for an email account.
//
// **Important:**
//
// When you disable the [Receive Mail role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) GetStatus(ctx context.Context, args *BoxTrapperGetStatusArgs) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "BoxTrapper", "get_status", args)
}


// BoxTrapperIgnoreMessagesArgs are the parameters of the UAPI function `BoxTrapper::ignore_messages`.
type BoxTrapperIgnoreMessagesArgs struct {
	// The cPanel email account from which to ignore messages.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults
	// to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The filename of the email message to ignore.
	//
	// **Note:**
	//
	//  To ignore multiple email messages, duplicate this parameter.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// IgnoreMessages calls the UAPI function `BoxTrapper::ignore_messages` — Add email account to Exim ignore list
//
// This function marks email message senders for Exim to ignore.
//
// **Important:**
//
// When you disable the [Receive Mail role](https://go.cpanel.net/howtouseserverprofiles#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) IgnoreMessages(ctx context.Context, args *BoxTrapperIgnoreMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperIgnoreMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperIgnoreMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "ignore_messages", args)
}


// BoxTrapperIgnoreMessagesDataItem is a generated payload type.
type BoxTrapperIgnoreMessagesDataItem struct {
	// The ignored email message's sender.
	Email    string `json:"email"`

	// Whether the system failed to ignore the messages.
	//
	// * `1` - Failed to ignore the message.
	//
	// * `1` - Failed to ignore the message.
	//
	// * `1` - Failed to ignore the message.
	//
	// * `1` - Failed to ignore the message.
	//
	// * `1` - Failed to ignore the message.
	//
	// **Note:**
	//
	//  The function only returns this value if it experiences issues when it ignores the message.
	//
	// Possible values: `1`.
	Failed   int64 `json:"failed"`

	// An array containing ignored message files.
	Matches  []string `json:"matches"`

	// The operation that the system performed.
	//
	// * `ignore` — The system ignored this email message.
	//
	// Possible values: `ignore`.
	Operator string `json:"operator"`

	// A message that describes the failure or the warning.
	//
	// **Note:**
	//
	//  The function only returns this value if it doesn't ignore the message or experiences issues when it ignores the message.
	Reason   string `json:"reason"`

	// Whether the system experienced issues when it ignored the message.
	//
	// * `1` — The system encountered a problem.
	//
	// **Note:**
	//
	//  The function only returns this value if it experiences issues when it ignores the message.
	//
	// Possible values: `1`.
	Warning  int64 `json:"warning"`
}

// ListEmailTemplates calls the UAPI function `BoxTrapper::list_email_templates` — Return BoxTrapper email templates
//
// This function lists the BoxTrapper email templates.
//
// **Important:**
//
// When you **disable** the [Receive Mail](https://go.cpanel.net/serverroles) role, the system disables this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) ListEmailTemplates(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "BoxTrapper", "list_email_templates", cpanel.CombineArgs(extra...))
}


// BoxTrapperListQueuedMessagesArgs are the parameters of the UAPI function `BoxTrapper::list_queued_messages`.
type BoxTrapperListQueuedMessagesArgs struct {
	// The email account for which to retrieve queued messages.
	//
	// **Important:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The date for which to return queued messages.
	Date *int64 `cpanel:"date,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListQueuedMessages calls the UAPI function `BoxTrapper::list_queued_messages` — Return email account's BoxTrapper queued messages
//
// This function returns a list of messages in the account's BoxTrapper queue.
//
// **Important:**
//
//   When you disable the [*Receive Mail* role](https://go.cpanel.net/serverroles), the system **disables**
//   this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) ListQueuedMessages(ctx context.Context, args *BoxTrapperListQueuedMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperListQueuedMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperListQueuedMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "list_queued_messages", args)
}


// BoxTrapperListQueuedMessagesDataItem is a generated payload type.
type BoxTrapperListQueuedMessagesDataItem struct {
	// The sender's email address.
	From      string `json:"from"`

	// The message's unique ID.
	QueueFile string `json:"queuefile"`

	// The message's subject.
	Subject   string `json:"subject"`

	// The message's creation time.
	Time      int64 `json:"time"`
}

// BoxTrapperProcessMessagesArgs are the parameters of the UAPI function `BoxTrapper::process_messages`.
type BoxTrapperProcessMessagesArgs struct {
	// The action to perform on the email message file. To perform multiple actions on the specified email messages, pass this parameter multiple times.
	//
	// * `deliver` — Deliver a specific message.
	// * `deliverall` — Deliver all messages from a sender.
	// * `delete` — Delete a message.
	// * `deleteall` — Delete all messages from a sender.
	// * `blacklist` — Blacklist the sender of an email message.
	// * `whitelist` — Whitelist the sender of an email message.
	// * `ignore` — Ignore email messages from a sender. …
	//
	// This parameter is required.
	Action string `cpanel:"action"`

	// The filename of the email message to process. To process multiple email messages, pass this parameter multiple times.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// The account's email address.
	//
	// **Warning:**
	//
	// * The `email` parameter is required when this function is called **outside** of Webmail.
	// * If you call this function in Webmail, the `email` parameter is **not** required, and
	// the system overrides this parameter with the current authenticated user's email address.
	Email *string `cpanel:"email,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ProcessMessages calls the UAPI function `BoxTrapper::process_messages` — Run a specific BoxTrapper action for a message
//
// This function performs a specified action on messages in the BoxTrapper queue.
//
// **Important:**
//
// When you disable the [*Receive Mail*](https://go.cpanel.net/serverroles#roles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) ProcessMessages(ctx context.Context, args *BoxTrapperProcessMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperProcessMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperProcessMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "process_messages", args)
}


// BoxTrapperProcessMessagesDataItem is a generated payload type.
type BoxTrapperProcessMessagesDataItem struct {
	// The email address for which the system
	// processed an email message.
	Email    *string `json:"email"`

	// Whether the system failed to process the message.
	//
	// * `1` - The function failed to process the message. This is the only
	// possible value.
	//
	// **Note:**
	//
	// The function only returns this value if it fails to process the message.
	//
	// Possible values: `1`.
	Failed   int64 `json:"failed"`

	// An array of email messages that the system processed.
	Matches  []string `json:"matches"`

	// The operation that the system performed.
	// * `deliver` - Delivered a specific message.
	// * `deliverall` - Delivered all messages from a sender.
	// * `delete` - Deleted a message.
	// * `deleteall` - Deleted all messages from a sender.
	// * `blacklist` - Blacklisted the sender of an email message.
	// * `whitelist` - Whitelisted the sender of an email message.
	// * `ignore` - Ignored email messages from a sender. …
	Operator string `json:"operator"`

	// A message about the failure or the warning.
	//
	// **Note:**
	//
	// The function only returns this value if it fails to processes the message or experiences issues when it processes the message.
	Reason   string `json:"reason"`
}

// BoxTrapperResetEmailTemplateArgs are the parameters of the UAPI function `BoxTrapper::reset_email_template`.
type BoxTrapperResetEmailTemplateArgs struct {
	// The message template. Possible values:
	// * `blacklist` - BoxTrapper responds with this message when a blacklisted address sends an email.
	// * `verify` - BoxTrapper responds with this message when an address that does not exist on the whitelist or blacklist sends an email. This message requests a response to confirm that the sender is legitimate.
	// * `verifyreleased` - BoxTrapper responds with this message when a person responds to the verify message with an email or a click on the verification link.
	// * …
	//
	// This parameter is required.
	Template string `cpanel:"template"`

	// The account's email address.
	//
	// **Warning:**
	//
	// The `email` parameter is required when this function is called outside of webmail.
	// If you call this function in Webmail, the `email` parameter is not required, and
	// the system overrides this parameter with the current authenticated user's email address.
	Email *string `cpanel:"email,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ResetEmailTemplate calls the UAPI function `BoxTrapper::reset_email_template` — Restore default BoxTrapper email message template
//
// This function restores the BoxTrapper email message templates to the system default setting.
//
// **Important:**
//
// When you **disable** the [Receive Mail](https://go.cpanel.net/serverroles) role, the system disables this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) ResetEmailTemplate(ctx context.Context, args *BoxTrapperResetEmailTemplateArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "reset_email_template", args)
}


// BoxTrapperSaveConfigurationArgs are the parameters of the UAPI function `BoxTrapper::save_configuration`.
type BoxTrapperSaveConfigurationArgs struct {
	// The account's email address.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Whether to enable automatic whitelisting for the account.
	//
	// * `1` - Enable.
	// * `0` - Disable.
	//
	// Possible values: `0`, `1`.
	//
	// This parameter is required.
	EnableAutoWhitelist int64 `cpanel:"enable_auto_whitelist"`

	// A comma-separated list of email addresses that the system uses when it sends messages back to the original message senders.
	//
	// This parameter is required.
	FromAddresses string `cpanel:"from_addresses"`

	// The number of days to retain log files and queued messages.
	//
	// This parameter is required.
	QueueDays int64 `cpanel:"queue_days"`

	// Whether to whitelist the email addresses in a message's *To* and *From* sections, including carbon-copied (CC) recipients.
	//
	// * `1` - Whitelist.
	// * `0` - Do **not** whitelist.
	//
	// Possible values: `0`, `1`.
	//
	// This parameter is required.
	WhitelistByAssociation int64 `cpanel:"whitelist_by_association"`

	// The name of the person who owns the email account.
	FromName *string `cpanel:"from_name,omitempty"`

	// The account's Apache SpamAssassin™ threshold score. For more information about Apache SpamAssassin threshold scores, read our [Spam Filters](https://go.cpanel.net/cpaneldocsSpamFilters) documentation.
	//
	// **Note:**
	//
	// This parameter defaults to the account's current configuration.
	SpamScore *float64 `cpanel:"spam_score,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SaveConfiguration calls the UAPI function `BoxTrapper::save_configuration` — Update email account's BoxTrapper configuration
//
// This function modifies an account's BoxTrapper configuration.
//
// **Important:**
//
// When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SaveConfiguration(ctx context.Context, args *BoxTrapperSaveConfigurationArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "save_configuration", args)
}


// BoxTrapperSaveEmailTemplateArgs are the parameters of the UAPI function `BoxTrapper::save_email_template`.
type BoxTrapperSaveEmailTemplateArgs struct {
	// The template file's contents.
	//
	// You can use [variables](https://go.cpanel.net/cpaneldocsBoxTrapper) in the template
	// to include details about the original message.
	//
	// **Important:**
	//
	// * You **must** include `To: %email%` in this parameter's value.
	// * If you use the `verify` template, you **must** include `Subject: verify#%msgid%` in this parameter's value.
	// * This value cannot exceed four kilobytes (KB).
	// * You **must** URI-encode this parameter's value when using the CLI.
	//
	// This parameter is required.
	Contents string `cpanel:"contents"`

	// The account's email address.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	//
	// **Note:**
	//
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The message template.
	//
	// * `blacklist`
	// * `returnverify`
	// * `verifyreleased`
	// * `verify`
	//
	// **Important:**
	//
	// If you use the `verify` template, you **must** include `Subject: verify#%msgid%` in this parameter's value.
	//
	// **Note:**
	//
	// For more information about each template, read our [BoxTrapper documentation](https://go.cpanel.net/cpaneldocsBoxTrapper).
	//
	// Possible values: `blacklist`, `returnverify`, `verifyreleased`, `verify`.
	//
	// This parameter is required.
	Template string `cpanel:"template"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SaveEmailTemplate calls the UAPI function `BoxTrapper::save_email_template` — Save BoxTrapper message template contents
//
// This function saves the contents of a BoxTrapper message template.
//
// **Important:**
//
// When you disable the [_Receive Mail_ role](https://go.cpanel.net/howtouseserverprofiles#roles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SaveEmailTemplate(ctx context.Context, args *BoxTrapperSaveEmailTemplateArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "save_email_template", args)
}


// BoxTrapperSetAllowlistArgs are the parameters of the UAPI function `BoxTrapper::set_allowlist`.
type BoxTrapperSetAllowlistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// An array of allowlist rules.
	//
	// **Note:**
	//
	// You can set multiple allowlist rules, duplicate or increment the parameter name. For example,
	// `rules-1`, `rules-2`, and `rules-3`.
	//
	// This parameter is required.
	Rules []string `cpanel:"rules"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetAllowlist calls the UAPI function `BoxTrapper::set_allowlist` — Update account BoxTrapper allowlist
//
// This function sets the BoxTrapper allowlist configuration rules. BoxTrapper will deliver emails that match these rules.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SetAllowlist(ctx context.Context, args *BoxTrapperSetAllowlistArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "set_allowlist", args)
}


// BoxTrapperSetBlocklistArgs are the parameters of the UAPI function `BoxTrapper::set_blocklist`.
type BoxTrapperSetBlocklistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// An array of blocklist rules.
	//
	// **Note:**
	//
	// You can set multiple block rules, duplicate or increment the parameter name. For example,
	// `rules-1`, `rules-2`, and `rules-3`.
	//
	// This parameter is required.
	Rules []string `cpanel:"rules"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetBlocklist calls the UAPI function `BoxTrapper::set_blocklist` — Update account BoxTrapper blocklist
//
// This function sets the BoxTrapper blocklist configuration rules. BoxTrapper will delete messages that match these rules and send a notification to the sender.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SetBlocklist(ctx context.Context, args *BoxTrapperSetBlocklistArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "set_blocklist", args)
}


// BoxTrapperSetForwardersArgs are the parameters of the UAPI function `BoxTrapper::set_forwarders`.
type BoxTrapperSetForwardersArgs struct {
	// The account's email address.
	//
	// **Warning:**
	//
	// If you call this function
	// in Webmail, the system ignores this parameter and uses the currently-authenticated
	// email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// The email addresses to which to forward email messages.
	//
	// This parameter is required.
	Forwarder []string `cpanel:"forwarder"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetForwarders calls the UAPI function `BoxTrapper::set_forwarders` — Add email address to BoxTrapper forwarders
//
// This function adds a list of email addresses to which BoxTrapper forwards email messages.
//
// **Important:**
//
//   When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 86.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SetForwarders(ctx context.Context, args *BoxTrapperSetForwardersArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "set_forwarders", args)
}


// BoxTrapperSetIgnorelistArgs are the parameters of the UAPI function `BoxTrapper::set_ignorelist`.
type BoxTrapperSetIgnorelistArgs struct {
	// A valid email address on the cPanel account.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system overrides this parameter.
	// This parameter defaults to the current email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// An array of ignorelist rules.
	//
	// **Note:**
	//
	// You can set multiple ignore rules, duplicate or increment the parameter name. For example,
	// `rules-1`, `rules-2`, and `rules-3`.
	//
	// This parameter is required.
	Rules []string `cpanel:"rules"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetIgnorelist calls the UAPI function `BoxTrapper::set_ignorelist` — Update account BoxTrapper ignorelist
//
// This function sets the BoxTrapper ignorelist configuration rules. BoxTrapper will delete messages that match these rules without sending a notification to the sender.
//
// **Important:**
//
// When you disable the
// [*Receive Mail* role](https://go.cpanel.net/serverroles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 94.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SetIgnorelist(ctx context.Context, args *BoxTrapperSetIgnorelistArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "set_ignorelist", args)
}


// BoxTrapperSetStatusArgs are the parameters of the UAPI function `BoxTrapper::set_status`.
type BoxTrapperSetStatusArgs struct {
	// The account's name. This can be an email address or the cPanel user’s username.
	//
	// **Warning:**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	//
	// This parameter is required.
	Email string `cpanel:"email"`

	// Whether to enable or disable BoxTrapper for the email account.
	//
	// * `1` - Enable BoxTrapper.
	// * `0` - **Disable** BoxTrapper.
	//
	// Possible values: `0`, `1`.
	//
	// This parameter is required.
	Enabled int64 `cpanel:"enabled"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetStatus calls the UAPI function `BoxTrapper::set_status` — Enable or disable BoxTrapper for email account
//
// This function enables or disables BoxTrapper for an email account.
//
// **Important:**
//
//   When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) SetStatus(ctx context.Context, args *BoxTrapperSetStatusArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "BoxTrapper", "set_status", args)
}


// BoxTrapperWhitelistMessagesArgs are the parameters of the UAPI function `BoxTrapper::whitelist_messages`.
type BoxTrapperWhitelistMessagesArgs struct {
	// The filename of the email message to whitelist.
	//
	// **Note:**
	//
	// To get a list of filenames in an account's BoxTrapper queue, use the UAPI `BoxTrapper::list_queued_messages` function.
	//
	// **Note:**
	//
	// To whitelist multiple email messages, duplicate this parameter.
	//
	// This parameter is required.
	QueueFile string `cpanel:"queuefile"`

	// The cPanel account email address for which to whitelist messages.
	//
	// **Warning**
	//
	// If you call this function in Webmail, the system ignores this parameter and defaults to the currently-authenticated email address.
	Email *string `cpanel:"email,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// WhitelistMessages calls the UAPI function `BoxTrapper::whitelist_messages` — Add email address to BoxTrapper allowed senders
//
// This function whitelists email messages.
//
// **Important:**
//
// When you disable the [Receive Mail](https://go.cpanel.net/serverroles) role, the system **disables** this function.
//
// **Note:**
//
// To retrieve email messages in the BoxTrapper queue from senders that you did not previously whitelist, use the UAPI `BoxTrapper::deliver_messages` function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-prevention-(boxtrapper
func (c *BoxTrapperClient) WhitelistMessages(ctx context.Context, args *BoxTrapperWhitelistMessagesArgs) (*cpanel.UAPIResult[[]BoxTrapperWhitelistMessagesDataItem], error) {
	return cpanel.UAPICall[[]BoxTrapperWhitelistMessagesDataItem](ctx, c.c, http.MethodGet, "BoxTrapper", "whitelist_messages", args)
}


// BoxTrapperWhitelistMessagesDataItem is a generated payload type.
type BoxTrapperWhitelistMessagesDataItem struct {
	// A whitelisted email address.
	Email    string `json:"email"`

	// The system failed to whitelist the message.
	//
	// * `1` — The function failed to whitelist the message. This is the only possible value.
	//
	// **Note:**
	//
	// The function only returns this property if it failed to whitelist the message.
	//
	// Possible values: `1`.
	Failed   string `json:"failed"`

	// An array of message files that the system whitelisted.
	//
	// **Note:**
	//
	// The function **only** returns this value if it whitelists the message.
	Matches  []string `json:"matches"`

	// The action that the system performed.
	//
	// Possible values: `whitelist`.
	Operator string `json:"operator"`

	// The reason the function skipped the message during whitelisting. The `reason` property is returned only if the function failed to whitelist the message.
	Reason   string `json:"reason"`

	// Whether the system experienced issues when it whitelisted the message.
	//
	// * `1` — There was an issue whitelisting the message. This is the only possible value.
	//
	// **Note:**
	//
	// The function only returns this property if it failed to whitelist the message.
	//
	// Possible values: `1`.
	Warning  int64 `json:"warning"`
}
