// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// CPDAVDAddDelegateArgs are the parameters of the UAPI function `CPDAVD::add_delegate`.
type CPDAVDAddDelegateArgs struct {
	// The calendar to share.
	//
	// This parameter is required.
	Calendar string `cpanel:"calendar"`

	// The person to whom you will share the calendar.
	//
	// This parameter is required.
	DelegateE string `cpanel:"delegatee"`

	// The owner of the calendar, who wishes to share it to another user.
	//
	// This parameter is required.
	DelegAtOr string `cpanel:"delegator"`

	// If set, the provided access will be read-only.
	//
	// Possible values: `0`, `1`.
	Readonly *int64 `cpanel:"readonly,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddDelegate calls the UAPI function `CPDAVD::add_delegate` — Share a calendar
//
// This function adds a share for the specified calendar.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) AddDelegate(ctx context.Context, args *CPDAVDAddDelegateArgs) (*cpanel.UAPIResult[CPDAVDAddDelegateData], error) {
	return cpanel.UAPICall[CPDAVDAddDelegateData](ctx, c.c, http.MethodGet, "CPDAVD", "add_delegate", args)
}

// CPDAVDAddDelegateData is a generated payload type.
type CPDAVDAddDelegateData struct {
	// Whether the sharing succeeded.
	// * `1` — Shared.
	// * `0` — **Not** shared.
	//
	// Possible values: `0`, `1`.
	Shared int64 `json:"shared"`
}

// ListDelegates calls the UAPI function `CPDAVD::list_delegates` — List calendar sharing.
//
// This function lists the sharing configuration in calendars for this account.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) ListDelegates(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]CPDAVDListDelegatesDataItem], error) {
	return cpanel.UAPICall[[]CPDAVDListDelegatesDataItem](ctx, c.c, http.MethodGet, "CPDAVD", "list_delegates", cpanel.CombineArgs(extra...))
}

// CPDAVDListDelegatesDataItem is a generated payload type.
type CPDAVDListDelegatesDataItem struct {
	// The calendar id.
	Calendar string `json:"calendar"`

	// The name of the calendar.
	Calname string `json:"calname"`

	// The person to whom the owner of the calendar shared it.
	DelegateE string `json:"delegatee"`

	// The owner of the calendar.
	DelegAtOr string `json:"delegator"`

	// If set to `1`, the `delegatee` only has read access to the calendar.
	//
	// Possible values: `0`, `1`.
	Readonly int64 `json:"readonly"`
}

// ListUsers calls the UAPI function `CPDAVD::list_users` — List CalDAV and CardDAV users
//
// # This function lists the users that are available for use with CalDAV and CardDAV
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) ListUsers(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]map[string]map[string]CPDAVDListUsersDataItemValueValue], error) {
	return cpanel.UAPICall[[]map[string]map[string]CPDAVDListUsersDataItemValueValue](ctx, c.c, http.MethodGet, "CPDAVD", "list_users", cpanel.CombineArgs(extra...))
}

// The name of this property is the collection id.
type CPDAVDListUsersDataItemValueValue struct {
	// For calendars only: The color to use for calendar events.
	CalendarColor string `json:"calendar-color"`

	// The description of the collection.
	Description string `json:"description"`

	// The name of the collection.
	DisplayName string `json:"displayname"`

	// If this value is `1`, then the collection cannot be deleted through the API.
	//
	// Possible values: `0`, `1`.
	Protected int64 `json:"protected"`

	// The type of the collection.
	//
	// Possible values: `VADDRESSBOOK`, `VCALENDAR`, `VTODO`.
	Type2 string `json:"type"`
}

// CPDAVDManageCollectionArgs are the parameters of the UAPI function `CPDAVD::manage_collection`.
type CPDAVDManageCollectionArgs struct {
	// The owner of the calendar.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// The action to perform (create, update, or delete a collection).
	//
	// Possible values: `create`, `update`, `delete`.
	//
	// This parameter is required.
	Action string `cpanel:"action"`

	// The collection type.
	//
	// Possible values: `calendar`, `tasks`, `addressbook`.
	//
	// This parameter is required.
	CollectionType string `cpanel:"collection_type"`

	// The path to the collection.
	//
	// This parameter is required.
	Path string `cpanel:"path"`

	// The color of the calendar, if applicable.
	CalendarColor *string `cpanel:"calendar-color,omitempty"`

	// The description of the collection.
	Description *string `cpanel:"description,omitempty"`

	// The name of the collection. Required when creating a collection.
	Name *string `cpanel:"name,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ManageCollection calls the UAPI function `CPDAVD::manage_collection` — Manage a calendar, task list, or address book
//
// This function creates, updates, or deletes a collection.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) ManageCollection(ctx context.Context, args *CPDAVDManageCollectionArgs) (*cpanel.UAPIResult[CPDAVDManageCollectionData], error) {
	return cpanel.UAPICall[CPDAVDManageCollectionData](ctx, c.c, http.MethodGet, "CPDAVD", "manage_collection", args)
}

// CPDAVDManageCollectionData is a generated payload type.
type CPDAVDManageCollectionData struct {
	// Whether the operation succeeded.
	// * `1` — Operation succeeded.
	// * `0` — Operation did **not** succeed.
	//
	// Possible values: `0`, `1`.
	Shared int64 `json:"shared"`
}

// CPDAVDRemoveDelegateArgs are the parameters of the UAPI function `CPDAVD::remove_delegate`.
type CPDAVDRemoveDelegateArgs struct {
	// The calendar that was shared.
	//
	// This parameter is required.
	Calendar string `cpanel:"calendar"`

	// The person to whom the calendar was shared.
	//
	// This parameter is required.
	DelegateE string `cpanel:"delegatee"`

	// The owner of the calendar, who wishes to remove the sharing.
	//
	// This parameter is required.
	DelegAtOr string `cpanel:"delegator"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RemoveDelegate calls the UAPI function `CPDAVD::remove_delegate` — Remove a share.
//
// This function removes a share for the specified calendar.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) RemoveDelegate(ctx context.Context, args *CPDAVDRemoveDelegateArgs) (*cpanel.UAPIResult[CPDAVDRemoveDelegateData], error) {
	return cpanel.UAPICall[CPDAVDRemoveDelegateData](ctx, c.c, http.MethodGet, "CPDAVD", "remove_delegate", args)
}

// CPDAVDRemoveDelegateData is a generated payload type.
type CPDAVDRemoveDelegateData struct {
	// Whether the sharing removal succeeded.
	// * `1` — Removed.
	// * `0` — **Not** removed.
	//
	// Possible values: `0`, `1`.
	Shared int64 `json:"shared"`
}

// CPDAVDUpdateDelegateArgs are the parameters of the UAPI function `CPDAVD::update_delegate`.
type CPDAVDUpdateDelegateArgs struct {
	// The calendar to share.
	//
	// This parameter is required.
	Calendar string `cpanel:"calendar"`

	// The person to whom you will share the calendar.
	//
	// This parameter is required.
	DelegateE string `cpanel:"delegatee"`

	// The owner of the calendar, who wishes to change the details of the sharing.
	//
	// This parameter is required.
	DelegAtOr string `cpanel:"delegator"`

	// If set, the provided access will be read-only.
	//
	// Possible values: `0`, `1`.
	Readonly *int64 `cpanel:"readonly,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UpdateDelegate calls the UAPI function `CPDAVD::update_delegate` — Update calendar sharing.
//
// This function updates a share for the specified calendar.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/calendar-and-contacts-(dav
func (c *CPDAVDClient) UpdateDelegate(ctx context.Context, args *CPDAVDUpdateDelegateArgs) (*cpanel.UAPIResult[CPDAVDUpdateDelegateData], error) {
	return cpanel.UAPICall[CPDAVDUpdateDelegateData](ctx, c.c, http.MethodGet, "CPDAVD", "update_delegate", args)
}

// CPDAVDUpdateDelegateData is a generated payload type.
type CPDAVDUpdateDelegateData struct {
	// Whether the sharing succeeded.
	// * `1` — Shared.
	// * `0` — **Not** shared.
	//
	// Possible values: `0`, `1`.
	Shared int64 `json:"shared"`
}
