// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// DirectoryProtectionListDirectoriesArgs are the parameters of the UAPI function `DirectoryProtection::list_directories`.
type DirectoryProtectionListDirectoriesArgs struct {
	// The absolute or relative file path in the user's `home` directory for which to return leech protection information.
	//
	// This parameter is required.
	Dir string `cpanel:"dir"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListDirectories calls the UAPI function `DirectoryProtection::list_directories` — Return Directory Protection settings
//
// This function returns the
// [leech protection](https://go.cpanel.net/cpaneldocsLeechProtection)
// settings of the subdirectories in a directory.
//
// Available since cPanel & WHM version cPanel 88.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/directory-protection/directoryprotection-list_directories.md
func (c *DirectoryProtectionClient) ListDirectories(ctx context.Context, args *DirectoryProtectionListDirectoriesArgs) (*cpanel.UAPIResult[DirectoryProtectionListDirectoriesData], error) {
	return cpanel.UAPICall[DirectoryProtectionListDirectoriesData](ctx, c.c, http.MethodGet, "DirectoryProtection", "list_directories", args)
}

// A object containing the subdirectory's leech protection information.
type DirectoryProtectionListDirectoriesDataChildrenItemState struct {
	// The directory's leech protection status.
	//
	// * `1` — Leech protection is enabled.
	// * `0` — Leech protection is disabled.
	//
	// Possible values: `1`, `0`.
	HasLeechProtection int64 `json:"has_leech_protection"`
}

// DirectoryProtectionListDirectoriesDataChildrenItem is a generated payload type.
type DirectoryProtectionListDirectoriesDataChildrenItem struct {
	// The subdirectory's absolute directory path.
	Path string `json:"path"`

	// A object containing the subdirectory's leech protection information.
	State DirectoryProtectionListDirectoriesDataChildrenItemState `json:"state"`
}

// An object containing the current directory's leech protection information.
type DirectoryProtectionListDirectoriesDataCurrentState struct {
	// The current directory's leech protection status.
	//
	// * `1` — Leech protection is enabled.
	// * `0` — Leech protection is disabled.
	//
	// Possible values: `1`, `0`.
	HasLeechProtection int64 `json:"has_leech_protection"`
}

// The user's current directory and its leech protection information.
type DirectoryProtectionListDirectoriesDataCurrent struct {
	// The current directory's absolute file path.
	Path string `json:"path"`

	// An object containing the current directory's leech protection information.
	State DirectoryProtectionListDirectoriesDataCurrentState `json:"state"`
}

// A object containing the `home` directory's leech protection information.
type DirectoryProtectionListDirectoriesDataHomeState struct {
	// The home directory's leech protection status.
	//
	// * `1` — Leech protection is enabled.
	// * `0` — Leech protection is disabled.
	//
	// Possible values: `1`, `0`.
	HasLeechProtection int64 `json:"has_leech_protection"`
}

// The user's `home` directory and its leech protection information.
type DirectoryProtectionListDirectoriesDataHome struct {
	// The `home` directory's absolute directory path.
	Path string `json:"path"`

	// A object containing the `home` directory's leech protection information.
	State DirectoryProtectionListDirectoriesDataHomeState `json:"state"`
}

// An object containing the parent directory's leech protection information.
type DirectoryProtectionListDirectoriesDataParentState struct {
	// The parent directory's leech protection status.
	//
	// * `1` — Leech protection is enabled.
	// * `0` — Leech protection is disabled.
	//
	// Possible values: `1`, `0`.
	HasLeechProtection int64 `json:"has_leech_protection"`
}

// The parent directory of the current directory and its leech protection information.
type DirectoryProtectionListDirectoriesDataParent struct {
	// The parent directory's absolute directory path.
	Path string `json:"path"`

	// An object containing the parent directory's leech protection information.
	State DirectoryProtectionListDirectoriesDataParentState `json:"state"`
}

// DirectoryProtectionListDirectoriesData is a generated payload type.
type DirectoryProtectionListDirectoriesData struct {
	// A list of subdirectories and their leech protection information.
	//
	// **Note:**
	//
	// The function returns a list for each subdirectory in a directory.
	Children []DirectoryProtectionListDirectoriesDataChildrenItem `json:"children"`

	// The user's current directory and its leech protection information.
	Current DirectoryProtectionListDirectoriesDataCurrent `json:"current"`

	// The user's `home` directory and its leech protection information.
	Home DirectoryProtectionListDirectoriesDataHome `json:"home"`

	// The parent directory of the current directory and its leech protection information.
	Parent DirectoryProtectionListDirectoriesDataParent `json:"parent"`
}
