// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// DNSEnsureDomainsResideOnlyLocallyArgs are the parameters of the UAPI function `DNS::ensure_domains_reside_only_locally`.
type DNSEnsureDomainsResideOnlyLocallyArgs struct {
	// The domain to check.
	//
	// **Note:**
	//
	// To check multiple domains, duplicate or increment the parameter name. For example, to exclude three domains, you could:
	// * Use the `domain` parameter multiple times.
	// * Use the `domain`, `domain-1`, and `domain-2` parameters.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// EnsureDomainsResideOnlyLocally calls the UAPI function `DNS::ensure_domains_reside_only_locally` — Return whether domains only resolve locally
//
// This function indicates whether the account's domains resolve exclusively to this server.
//
// Available since cPanel & WHM version cPanel 56.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-ensure_domains_reside_only_locally.md
func (c *DNSClient) EnsureDomainsResideOnlyLocally(ctx context.Context, args *DNSEnsureDomainsResideOnlyLocallyArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "DNS", "ensure_domains_reside_only_locally", args)
}


// DNSFetchCpanelGeneratedDomainsArgs are the parameters of the UAPI function `DNS::fetch_cpanel_generated_domains`.
type DNSFetchCpanelGeneratedDomainsArgs struct {
	// The domain for which to retrieve cPanel-generated subdomains.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// FetchCpanelGeneratedDomains calls the UAPI function `DNS::fetch_cpanel_generated_domains` — Retrieve cPanel-generated subdomains for a domain
//
// This function retrieves the list of subdomains that cPanel automatically
// generates for a given domain. These include proxy subdomains such as
// `webmail`, `mail`, and `cpanel`, as well as other system-generated
// domain names.
//
// Available since cPanel & WHM version cPanel 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-fetch_cpanel_generated_domains.md
func (c *DNSClient) FetchCpanelGeneratedDomains(ctx context.Context, args *DNSFetchCpanelGeneratedDomainsArgs) (*cpanel.UAPIResult[[]DNSFetchCpanelGeneratedDomainsDataItem], error) {
	return cpanel.UAPICall[[]DNSFetchCpanelGeneratedDomainsDataItem](ctx, c.c, http.MethodGet, "DNS", "fetch_cpanel_generated_domains", args)
}


// DNSFetchCpanelGeneratedDomainsDataItem is a generated payload type.
type DNSFetchCpanelGeneratedDomainsDataItem struct {
	// A cPanel-generated domain name, returned as a fully-qualified
	// domain name (FQDN) with a trailing dot.
	Domain string `json:"domain"`
}

// DNSHasLocalAuthorityArgs are the parameters of the UAPI function `DNS::has_local_authority`.
type DNSHasLocalAuthorityArgs struct {
	// The domain to check whether the local server is authoritative for the domain's
	// DNS records.
	//
	// **Note:**
	//
	// To check multiple domains, increment or duplicate the parameter name. For
	// example, `domain-0`, `domain-1`, and `domain-2`.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// HasLocalAuthority calls the UAPI function `DNS::has_local_authority` — Return whether local DNS server is authoritative
//
// This function checks whether the local server is authoritative for the domain's DNS records.
//
// Available since cPanel & WHM version cPanel 78.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-has_local_authority.md
func (c *DNSClient) HasLocalAuthority(ctx context.Context, args *DNSHasLocalAuthorityArgs) (*cpanel.UAPIResult[[]DNSHasLocalAuthorityDataItem], error) {
	return cpanel.UAPICall[[]DNSHasLocalAuthorityDataItem](ctx, c.c, http.MethodGet, "DNS", "has_local_authority", args)
}


// DNSHasLocalAuthorityDataItem is a generated payload type.
type DNSHasLocalAuthorityDataItem struct {
	// The queried domain.
	Domain         string `json:"domain"`

	// An error message that details the reason why the local server's
	// authoritative check failed.
	//
	// **Note:**
	//
	// The function **only** returns this value when the check fails.
	Error          string `json:"error"`

	// Whether the local server is authoritative for the domain's DNS
	// records.
	//
	// * `1` — The local server is authoritative for the domain's DNS
	// records.
	// * `0` — The local server is **not** authoritative for the domain's
	// DNS records.
	//
	// Possible values: `1`, `0`.
	LocalAuthority int64 `json:"local_authority"`

	// The domain's nameservers, if any exist.
	Nameservers    []string `json:"nameservers"`

	// The domain's DNS zone, if one exists.
	//
	// * `null` — No valid DNS zone.
	Zone           *string `json:"zone"`
}

// IsAliasAvailable calls the UAPI function `DNS::is_alias_available` — Return `ALIAS` DNS record availability & resolver
//
// This function returns whether `ALIAS` and `ANAME` records are available and the value of the running PowerDNS (PDNS) `resolver` setting, if any exists.
// For more information, read our [`ALIAS` documentation](https://go.cpanel.net/dns-alias-record).
//
// Available since cPanel & WHM version cPanel 122.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_alias_available.md
func (c *DNSClient) IsAliasAvailable(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[DNSIsAliasAvailableData], error) {
	return cpanel.UAPICall[DNSIsAliasAvailableData](ctx, c.c, http.MethodGet, "DNS", "is_alias_available", cpanel.CombineArgs(extra...))
}


// DNSIsAliasAvailableData is a generated payload type.
type DNSIsAliasAvailableData struct {
	// Whether `ALIAS` records are available.
	//
	// * `1` - Available.
	// * `0` - Not available.
	//
	// When `ALIAS` records are enabled, they may work in API calls that accept `A` and `AAAA` records. However, the `ALIAS` record must use a fully qualified domain name (FQDN) rather than an IP address.
	//
	// Possible values: `1`, `0`.
	Alias    int64 `json:"alias"`

	// Whether `ANAME` records are available.
	//
	// * `1` - Available.
	// * `0` - Not available.
	//
	// **NOTE:**
	//
	// The `aname` value is always set to false (i.e. Not available). The `ANAME` record is currently not supported. It is included for completeness and future proofing.
	//
	// Possible values: `1`, `0`.
	Aname    int64 `json:"aname"`

	// The value (if any) of the running PDNS’s `resolver` setting.
	Resolver string `json:"resolver"`
}

// IsHTTPSAvailable calls the UAPI function `DNS::is_https_available` — Return DNS HTTPS record support information
//
// This function fetches information regarding HTTPS records support.
// HTTPS records are defined in RFC 9460 and provide service parameters for HTTPS endpoints.
// For more information, read our [Zone Editor documentation](https://go.cpanel.net/cpaneldocsZoneEditor).
//
// Available since cPanel & WHM version cPanel 122.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_https_available.md
func (c *DNSClient) IsHTTPSAvailable(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[DNSIsHTTPSAvailableData], error) {
	return cpanel.UAPICall[DNSIsHTTPSAvailableData](ctx, c.c, http.MethodGet, "DNS", "is_https_available", cpanel.CombineArgs(extra...))
}


// DNSIsHTTPSAvailableData is a generated payload type.
type DNSIsHTTPSAvailableData struct {
	// The DNS server type currently in use (bind, pdns, etc.).
	DNSServer string `json:"dns_server"`

	// Whether HTTPS records are supported.
	// * `1` - Supported.
	// * `0` - Not supported.
	//
	// Possible values: `1`, `0`.
	HTTPS     int64 `json:"https"`
}

// IsSvcbAvailable calls the UAPI function `DNS::is_svcb_available` — Return DNS SVCB record support information
//
// This function fetches information regarding SVCB records support.
// SVCB records are defined in RFC 9460 and provide service binding and aliasing for arbitrary services.
// For more information, read our [Zone Editor documentation](https://go.cpanel.net/cpaneldocsZoneEditor).
//
// Available since cPanel & WHM version cPanel 122.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_svcb_available.md
func (c *DNSClient) IsSvcbAvailable(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[DNSIsSvcbAvailableData], error) {
	return cpanel.UAPICall[DNSIsSvcbAvailableData](ctx, c.c, http.MethodGet, "DNS", "is_svcb_available", cpanel.CombineArgs(extra...))
}


// DNSIsSvcbAvailableData is a generated payload type.
type DNSIsSvcbAvailableData struct {
	// The DNS server type currently in use (bind, pdns, etc.).
	DNSServer string `json:"dns_server"`

	// Whether SVCB records are supported.
	// * `1` - Supported.
	// * `0` - Not supported.
	//
	// Possible values: `1`, `0`.
	Svcb      int64 `json:"svcb"`
}

// DNSLookupArgs are the parameters of the UAPI function `DNS::lookup`.
type DNSLookupArgs struct {
	// A fully qualified domain name.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// Lookup calls the UAPI function `DNS::lookup` — Return domain's DNS information
//
// This function returns DNS zone information about a domain.
//
// Available since cPanel & WHM version 90.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-lookup.md
func (c *DNSClient) Lookup(ctx context.Context, args *DNSLookupArgs) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "DNS", "lookup", args)
}


// DNSMassEditZoneArgs are the parameters of the UAPI function `DNS::mass_edit_zone`.
type DNSMassEditZoneArgs struct {
	// The current serial number in the DNS zone’s SOA (Start of Authority)
	// record. If this value does not match the zone’s current state, the
	// request fails.
	//
	// This parameter is required.
	Serial int64 `cpanel:"serial"`

	// The name of one of the user’s DNS zones.
	//
	// This parameter is required.
	Zone string `cpanel:"zone"`

	// The records to add to the zone. Each item must be a serialized
	// JSON object that contains:
	//
	// * `dname` — The record’s name.
	// * `ttl` — The record’s TTL (Time-To-Live) value.
	// * `record_type` — The record’s type. For example, `A` or `TXT`.
	// * `data` — An array of strings. The format and number of the
	//   strings depend on the `record_type` value.
	Add []string `cpanel:"add,omitempty"`

	// The records to edit in the zone. Each item must be a serialized
	// JSON object that contains:
	//
	// * `line_index` — The line number in the DNS zone where the record starts.
	//   This is a 0-based index, so to edit the first line in the file
	//   use the `0` value. To edit the second line, give `1`, and so forth.
	// * `dname` — The record’s name.
	// * `ttl` — The record’s TTL (Time-To-Live) value.
	// * `record_type` — The record’s new type. For example, `A` or `TXT`.
	// * `data` — An array of strings. The format and numb …
	Edit []string `cpanel:"edit,omitempty"`

	// The line indexes of records to remove from the zone.
	Remove []int64 `cpanel:"remove,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// MassEditZone calls the UAPI function `DNS::mass_edit_zone` — Update a DNS zone
//
// This function updates a DNS zone by allowing multiple records to be added, modified, or removed in a single call. It also ensures modified records occupy the same number of lines as before the edit.
//
// **NOTE:**
//
// You cannot use this function to edit temporary domains.
//
// Available since cPanel & WHM version 96.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-mass_edit_zone.md
func (c *DNSClient) MassEditZone(ctx context.Context, args *DNSMassEditZoneArgs) (*cpanel.UAPIResult[DNSMassEditZoneData], error) {
	return cpanel.UAPICall[DNSMassEditZoneData](ctx, c.c, http.MethodGet, "DNS", "mass_edit_zone", args)
}


// DNSMassEditZoneData is a generated payload type.
type DNSMassEditZoneData struct {
	// The DNS zone’s SOA record’s new serial number.
	// You can use this to submit later edits if you
	// track the number of lines each record takes up.
	NewSerial int64 `json:"new_serial"`
}

// DNSParseZoneArgs are the parameters of the UAPI function `DNS::parse_zone`.
type DNSParseZoneArgs struct {
	// The name of one of the user’s DNS zones.
	//
	// This parameter is required.
	Zone string `cpanel:"zone"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ParseZone calls the UAPI function `DNS::parse_zone` — Return a parsed DNS zone
//
// This function parses a given DNS zone.
//
// **Important:**
//
// Most DNS zones contain only 7-bit ASCII. However, it is possible for
// DNS zones to contain any binary sequence. An application that decodes
// this function's base64 output **must** be able to handle cases
// where the decoded octets do not match any specific character
// encoding.
//
// Available since cPanel & WHM version 96.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-parse_zone.md
func (c *DNSClient) ParseZone(ctx context.Context, args *DNSParseZoneArgs) (*cpanel.UAPIResult[Payload], error) {
	return cpanel.UAPICall[Payload](ctx, c.c, http.MethodGet, "DNS", "parse_zone", args)
}


// The zone’s content.
type Payload []string

// DNSSwapIPInZonesArgs are the parameters of the UAPI function `DNS::swap_ip_in_zones`.
type DNSSwapIPInZonesArgs struct {
	// The IPv4 address to use as the replacement in the zone files.
	//
	// This parameter is required.
	DestIP string `cpanel:"dest_ip"`

	// The domain to perform the zone file updates on.
	//
	// **Note:**
	//
	// To update multiple domains, increment or duplicate the parameter name. For
	// example, `domain-0`, `domain-1`, and `domain-2`.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// The IPv4 address to use as the replacement for FTP records in the zone files.
	//
	// If this parameter is **not** provided, then the system will use the `dest_ip` value.
	FTPIP *string `cpanel:"ftp_ip,omitempty"`

	// The IPv4 address to replace in the zone files. The detected source IPv4 address is one of:
	//
	// * If there is an A record for the root of the zone **and** the IP address is **not** a loopback address, then the system will use its address.
	// * If there are any A records in the zone whose addresses are **not** loopback addresses, then the system will use the address of the first such A record in the zone file.
	// * If no A records exist in the zone **or** all A records have loopback addresses, then the sys …
	SourceIP *string `cpanel:"source_ip,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SwapIPInZones calls the UAPI function `DNS::swap_ip_in_zones` — Update IP addresses in zone files
//
// This function replaces a domain's IPv4 address in the DNS zone
// file with the specified destination IPv4 address.
//
// Available since cPanel & WHM version cPanel 96.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/dns/dns-swap_ip_in_zones.md
func (c *DNSClient) SwapIPInZones(ctx context.Context, args *DNSSwapIPInZonesArgs) (*cpanel.UAPIResult[[]DNSSwapIPInZonesDataItem], error) {
	return cpanel.UAPICall[[]DNSSwapIPInZonesDataItem](ctx, c.c, http.MethodGet, "DNS", "swap_ip_in_zones", args)
}


// DNSSwapIPInZonesDataItem is a generated payload type.
type DNSSwapIPInZonesDataItem struct {
	// The value of the DNS record after it was updated.
	NewValue   string `json:"new_value"`

	// The value of the DNS record before it was updated.
	OldValue   string `json:"old_value"`

	// The name of the domain's updated DNS record.
	RecordName string `json:"record_name"`

	// The type of the DNS record which was updated.
	RecordType string `json:"record_type"`

	// The DNS zone in which the system updated the domain's record.
	ZoneName   string `json:"zone_name"`
}
