// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// Finish calls the UAPI function `ExtractInfo::finish` — Remove extract progress record
//
// This function clears the run-state marker that the `ExtractInfo::start`
// function wrote.
//
// **Note:**
// After it runs, the `ExtractInfo::progress` function reports the state
// `none`. This function is idempotent and succeeds whether or not a marker
// exists. Call it after the `Fileman::fileop` function with `op=extract`
// finishes, whether that operation succeeded or failed.
//
// Available since cPanel & WHM version 136.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/extractinfo/extractinfo-finish.md
func (c *ExtractInfoClient) Finish(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[ExtractInfoFinishData], error) {
	return cpanel.UAPICall[ExtractInfoFinishData](ctx, c.c, http.MethodGet, "ExtractInfo", "finish", cpanel.CombineArgs(extra...))
}

// ExtractInfoFinishData is a generated payload type.
type ExtractInfoFinishData struct {
	// Always true on success.
	Cleared bool `json:"cleared"`
}

// Progress calls the UAPI function `ExtractInfo::progress` — Return archive extraction progress
//
// This function returns progress information for an archive extraction
// that the `ExtractInfo::start` function began.
//
// **Note:**
// When no run is active, the `state` return value is `none` and the other
// return values are `0` or null.
//
// Available since cPanel & WHM version 136.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/extractinfo/extractinfo-progress.md
func (c *ExtractInfoClient) Progress(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[ExtractInfoProgressData], error) {
	return cpanel.UAPICall[ExtractInfoProgressData](ctx, c.c, http.MethodGet, "ExtractInfo", "progress", cpanel.CombineArgs(extra...))
}

// ExtractInfoProgressData is a generated payload type.
type ExtractInfoProgressData struct {
	// Bytes the destination directory has grown by since
	// the baseline that the `ExtractInfo::start`
	// function recorded. Never negative.
	CurrentBytes int64 `json:"currentBytes"`

	// Seconds since the run started. `0` when not
	// running.
	ElapsedSeconds int64 `json:"elapsedSeconds"`

	// Completion percent, from 0 to 99.
	//
	// **Note:**
	// The function derives this from `currentBytes` and
	// `totalBytes` and clamps it to 99 until the
	// `ExtractInfo::finish` function is called. The
	// value is approximate whenever
	// `totalBytesEstimated` is `1`. Even when the total
	// is exact, the destination directory delta can
	// carry noise.
	Percent float64 `json:"percent"`

	// Start epoch recorded by the `ExtractInfo::start`
	// function. Null when not running.
	StartedAtEpoch *int64 `json:"startedAtEpoch"`

	// Current run state.
	//
	// * `inprogress` - A run is active and within the
	//   timeout.
	// * `timeout` - A run has passed the timeout
	//   ceiling.
	// * `none` - Nothing is running. This includes the
	//   period after the `ExtractInfo::finish` function
	//   is called.
	//
	// Possible values: `inprogress`, `timeout`, `none`.
	State string `json:"state"`

	// The uncompressed archive size recorded at start.
	//
	// **Note:**
	// That size is exact for archives under 4 GiB. It is
	// a best-effort estimate for archives of 4 GiB or
	// more, because the gzip trailer stores the
	// uncompressed size modulo 4,294,967,296 bytes. See
	// the `totalBytesEstimated` return value.
	TotalBytes int64 `json:"totalBytes"`

	// Whether the `totalBytes` return value is an
	// estimate rather than an exact size.
	//
	// * `1` - The value is an estimate. The gzip trailer
	//   stores the uncompressed size modulo
	//   4,294,967,296 bytes, so it wrapped for an
	//   archive of 4 GiB or larger.
	// * `0` - The value is exact.
	TotalBytesEstimated int64 `json:"totalBytesEstimated"`
}

// ExtractInfoStartArgs are the parameters of the UAPI function `ExtractInfo::start`.
type ExtractInfoStartArgs struct {
	// The file path to the backup archive. It must resolve within the
	// cPanel account's home directory.
	//
	// This parameter is required.
	Archive string `cpanel:"archive"`

	// The destination directory where you want to extract the archive. It
	// must resolve within the cPanel account's home directory.
	//
	// This parameter is required.
	Directory string `cpanel:"directory"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// Start calls the UAPI function `ExtractInfo::start` — Start extract progress tracking
//
// This function starts progress tracking for a File Manager extract
// operation.
//
// **Note:**
//
//   - The `Fileman::fileop` function with `op=extract` is a single
//     synchronous call to `tar` that reports no progress of its own. This
//     function brackets that call from the outside so that a caller can show
//     real progress.
//   - Call this function first, then call the `Fileman::fileop` function to
//     perform the extract, poll the `ExtractInfo::progress` function while
//     it runs, and call the `ExtractInfo::finish` function when it
//     completes.
//   - The function records the archive's total uncompressed byte size and a
//     baseline snapshot of the destination directory's disk usage, then
//     writes a run-state marker.
//   - This function returns immediately and extracts nothing itself.
//
// Available since cPanel & WHM version 136.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/extractinfo/extractinfo-start.md
func (c *ExtractInfoClient) Start(ctx context.Context, args *ExtractInfoStartArgs) (*cpanel.UAPIResult[ExtractInfoStartData], error) {
	return cpanel.UAPICall[ExtractInfoStartData](ctx, c.c, http.MethodGet, "ExtractInfo", "start", args)
}

// ExtractInfoStartData is a generated payload type.
type ExtractInfoStartData struct {
	// Always true on success.
	Started bool `json:"started"`
}
