// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// ExternalAuthenticationAddAuthnLinkArgs are the parameters of the UAPI function `ExternalAuthentication::add_authn_link`.
type ExternalAuthenticationAddAuthnLinkArgs struct {
	// The preferred username of the account on the identity provider.
	//
	// This parameter is required.
	PreferredUsername string `cpanel:"preferred_username"`

	// The name of the identity provider.
	//
	// This parameter is required.
	ProviderID string `cpanel:"provider_id"`

	// The unique identifier for the user at the identity provider.
	//
	// This parameter is required.
	SubjectUniqueIdentifier string `cpanel:"subject_unique_identifier"`

	// The username.
	//
	// This parameter is required.
	Username string `cpanel:"username"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddAuthnLink calls the UAPI function `ExternalAuthentication::add_authn_link` — Add external authentication link
//
// This function adds an External Authentication authorization link to an account.
//
// Available since cPanel & WHM version cPanel 56.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/external-authentication/externalauthentication-add_authn_link.md
func (c *ExternalAuthenticationClient) AddAuthnLink(ctx context.Context, args *ExternalAuthenticationAddAuthnLinkArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "ExternalAuthentication", "add_authn_link", args)
}


// ConfiguredModules calls the UAPI function `ExternalAuthentication::configured_modules` — Return server's external authentication providers
//
// This function lists the display information for your server's available and configured external authentication identity provider modules.
//
// Available since cPanel & WHM version cPanel 54.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/external-authentication/externalauthentication-configured_modules.md
func (c *ExternalAuthenticationClient) ConfiguredModules(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]ExternalAuthenticationConfiguredModulesDataItem], error) {
	return cpanel.UAPICall[[]ExternalAuthenticationConfiguredModulesDataItem](ctx, c.c, http.MethodGet, "ExternalAuthentication", "configured_modules", cpanel.CombineArgs(extra...))
}


// ExternalAuthenticationConfiguredModulesDataItem is a generated payload type.
type ExternalAuthenticationConfiguredModulesDataItem struct {
	// The background color of the button on the cPanel interface.
	Color            string `json:"color"`

	// The identity provider's friendly name. cPanel & WHM interfaces will display this value.
	DisplayName      string `json:"display_name"`

	// The public URL of the identity provider's implementation documentation.
	DocumentationURL string `json:"documentation_url"`

	// The icon file to display on the button in the cPanel login interface.
	Icon             string `json:"icon"`

	// The icon file's MIME type.
	IconType         string `json:"icon_type"`

	// The text label of the login icon in the cPanel login interface.
	Label            string `json:"label"`

	// link to the identity provider's configuration for the appropriate service on the system.
	Link             string `json:"link"`

	// The identity provider's system name.
	ProviderName     string `json:"provider_name"`

	// The color of the text label in the cPanel login interface.
	TextColor        string `json:"textcolor"`
}

// GetAuthnLinks calls the UAPI function `ExternalAuthentication::get_authn_links` — Return external authentication links
//
// This function lists the external authentication links to the current cPanel account.
//
// Available since cPanel & WHM version cPanel 54.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/external-authentication/externalauthentication-get_authn_links.md
func (c *ExternalAuthenticationClient) GetAuthnLinks(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]ExternalAuthenticationGetAuthnLinksDataItem], error) {
	return cpanel.UAPICall[[]ExternalAuthenticationGetAuthnLinksDataItem](ctx, c.c, http.MethodGet, "ExternalAuthentication", "get_authn_links", cpanel.CombineArgs(extra...))
}


// ExternalAuthenticationGetAuthnLinksDataItem is a generated payload type.
type ExternalAuthenticationGetAuthnLinksDataItem struct {
	// When the user linked their account to the identity provider.
	LinkTime                int64 `json:"link_time"`

	// The preferred username of the account on the identity provider.
	PreferredUsername       string `json:"preferred_username"`

	// The system's unique key for the identity provider.
	ProviderID              string `json:"provider_id"`

	// The identity provider's protocol.
	ProviderProtocol        string `json:"provider_protocol"`

	// The unique identifier for the user at the identity provider.
	SubjectUniqueIdentifier int64 `json:"subject_unique_identifier"`
}

// HasExternalAuthModulesConfigured calls the UAPI function `ExternalAuthentication::has_external_auth_modules_configured` — Return external authentication user status
//
// This function determines whether the user enabled external authentication modules.
//
// Available since cPanel & WHM version cPanel 66.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/external-authentication/externalauthentication-has_external_auth_modules_configured.md
func (c *ExternalAuthenticationClient) HasExternalAuthModulesConfigured(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "ExternalAuthentication", "has_external_auth_modules_configured", cpanel.CombineArgs(extra...))
}


// ExternalAuthenticationRemoveAuthnLinkArgs are the parameters of the UAPI function `ExternalAuthentication::remove_authn_link`.
type ExternalAuthenticationRemoveAuthnLinkArgs struct {
	// The name of the identity provider.
	//
	// This parameter is required.
	Provider string `cpanel:"provider"`

	// The unique identifier for the user at the identity provider.
	//
	// This parameter is required.
	SubjectUniqueIdentifier string `cpanel:"subject_unique_identifier"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RemoveAuthnLink calls the UAPI function `ExternalAuthentication::remove_authn_link` — Remove external authentication link
//
// This function removes a link to an account at an external authentication identity provider.
//
// Available since cPanel & WHM version cPanel 54.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/external-authentication/externalauthentication-remove_authn_link.md
func (c *ExternalAuthenticationClient) RemoveAuthnLink(ctx context.Context, args *ExternalAuthenticationRemoveAuthnLinkArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "ExternalAuthentication", "remove_authn_link", args)
}

