// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// ImageManagerConvertFileArgs are the parameters of the UAPI function `ImageManager::convert_file`.
type ImageManagerConvertFileArgs struct {
	// The image file to convert, relative to the cPanel account's `/home` directory.
	//
	// This parameter is required.
	ImageFile string `cpanel:"image_file"`

	// The format to which to convert the images.
	//
	// This parameter is required.
	Type2 string `cpanel:"type"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ConvertFile calls the UAPI function `ImageManager::convert_file` — Create image with new format
//
// This function converts an image to a new file format.
//
// **Important:**
//
// When you disable the [WebServer role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/image-tools/imagemanager-convert_file.md
func (c *ImageManagerClient) ConvertFile(ctx context.Context, args *ImageManagerConvertFileArgs) (*cpanel.UAPIResult[ImageManagerConvertFileData], error) {
	return cpanel.UAPICall[ImageManagerConvertFileData](ctx, c.c, http.MethodGet, "ImageManager", "convert_file", args)
}


// ImageManagerConvertFileData is a generated payload type.
type ImageManagerConvertFileData struct {
	// The new absolute filepath to the image.
	ConvertedFile string `json:"converted_file"`
}

// ImageManagerCreateThumbnailsArgs are the parameters of the UAPI function `ImageManager::create_thumbnails`.
type ImageManagerCreateThumbnailsArgs struct {
	// The path to the directory where the image resides. When you pass this parameter, the function creates a thumbnail directory directly below the image directory.
	//
	// **NOTE:**
	//
	// This parameter can use an absolute directory path or a path relative to the user's home directory.
	//
	// This parameter is required.
	Dir string `cpanel:"dir"`

	// The percentage by which to reduce the thumbnails' height.
	//
	// This parameter is required.
	HeightPercentage int64 `cpanel:"height_percentage"`

	// The percentage by which to reduce the thumbnails' width.
	//
	// This parameter is required.
	WidthPercentage int64 `cpanel:"width_percentage"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateThumbnails calls the UAPI function `ImageManager::create_thumbnails` — Create image thumbnails
//
// This function creates thumbnails from images. The function saves the new thumbnail images in a thumbnails subdirectory inside the original directory. The system prepends thumbnail filenames with ``tn_`` (for example, ``tn_picture.jpg``).
//
// **Important:**
//
// When you disable the [WebServer role](https://go.cpanel.net/serverroles), the system disables this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/image-tools/imagemanager-create_thumbnails.md
func (c *ImageManagerClient) CreateThumbnails(ctx context.Context, args *ImageManagerCreateThumbnailsArgs) (*cpanel.UAPIResult[[]ImageManagerCreateThumbnailsDataItem], error) {
	return cpanel.UAPICall[[]ImageManagerCreateThumbnailsDataItem](ctx, c.c, http.MethodGet, "ImageManager", "create_thumbnails", args)
}


// ImageManagerCreateThumbnailsDataItem is a generated payload type.
type ImageManagerCreateThumbnailsDataItem struct {
	// Whether the function failed to create the thumbnail file.
	//
	// **Note:**
	//
	//  * The function **only** returns this value if it doesn't create the thumbnail.
	//  * `1` is the **only** possible value.
	//
	// Possible values: `1`.
	Failed        int64 `json:"failed"`

	// The file from which the function generated the thumbnail file. An absolute filepath.
	File          string `json:"file"`

	// The reason that the function didn't create the thumbnail file.
	//
	// **Note:**
	//
	//  The function only returns this value if it doesn't create the thumbnail.
	Reason        string `json:"reason"`

	// The thumbnail file that the function generated. An absolute filepath.
	ThumbnailFile string `json:"thumbnail_file"`
}

// ImageManagerGetDimensionsArgs are the parameters of the UAPI function `ImageManager::get_dimensions`.
type ImageManagerGetDimensionsArgs struct {
	// The path to the file to measure.
	//
	// **Note:**
	//
	// Use the absolute filepath or a path relative to the user's home directory.
	//
	// This parameter is required.
	ImageFile string `cpanel:"image_file"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetDimensions calls the UAPI function `ImageManager::get_dimensions` — Return image dimensions
//
// This function returns the dimensions of the image file that you specify.
//
// **Important:**
//
// When you disable the [WebServer role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/image-tools/imagemanager-get_dimensions.md
func (c *ImageManagerClient) GetDimensions(ctx context.Context, args *ImageManagerGetDimensionsArgs) (*cpanel.UAPIResult[ImageManagerGetDimensionsData], error) {
	return cpanel.UAPICall[ImageManagerGetDimensionsData](ctx, c.c, http.MethodGet, "ImageManager", "get_dimensions", args)
}


// ImageManagerGetDimensionsData is a generated payload type.
type ImageManagerGetDimensionsData struct {
	// The image's height, in pixels.
	Height int64 `json:"height"`

	// The image's width, in pixels.
	Width  int64 `json:"width"`
}

// ImageManagerResizeImageArgs are the parameters of the UAPI function `ImageManager::resize_image`.
type ImageManagerResizeImageArgs struct {
	// The height to which to set the image size.
	//
	// This parameter is required.
	Height int64 `cpanel:"height"`

	// The name of the file to scale.
	//
	// **Note:**
	//
	// Use the absolute filepath or a filepath relative to the user's home directory.
	//
	// This parameter is required.
	ImageFile string `cpanel:"image_file"`

	// The width to which to set the image size.
	//
	// This parameter is required.
	Width int64 `cpanel:"width"`

	// The path to the directory in which to save a copy the original
	// image file.
	//
	// **Note:**
	//
	// * If you don't pass this parameter, the function doesn't save
	// a copy of the original image.
	// * Use the absolute filepath or a filepath relative to the user's home directory.
	SaveOriginalAs *string `cpanel:"save_original_as,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ResizeImage calls the UAPI function `ImageManager::resize_image` — Save resized image
//
// This function resizes a specified image.
//
// **Important:**
//
// When you disable the [WebServer role](https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-use-server-profiles/#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 82.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/image-tools/imagemanager-resize_image.md
func (c *ImageManagerClient) ResizeImage(ctx context.Context, args *ImageManagerResizeImageArgs) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "ImageManager", "resize_image", args)
}

