// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// MailboxesExpungeMailboxMessagesArgs are the parameters of the UAPI function `Mailboxes::expunge_mailbox_messages`.
type MailboxesExpungeMailboxMessagesArgs struct {
	// The email account's name.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// The mailbox to operate on.
	//
	// **Note:**
	//
	// * Use the `Mailboxes::get_mailbox_status_list` function to list possible values for the mailbox parameter.
	// * Because you cannot escape wildcard characters such as (`*`), we recommend that you use functions that use the `mailbox_guid` parameter instead. For example, the `Mailboxes::expunge_messages_for_mailbox_guid` function.
	//
	// This parameter is required.
	Mailbox string `cpanel:"mailbox"`

	// The Dovecot query to execute.
	//
	// **Note:**
	//
	// The query parameter prevents accidental removal of all messages in the mailbox. For more information, read Dovecot's [Search Query](http://wiki2.dovecot.org/Tools/Doveadm/SearchQuery) documentation.
	//
	// This parameter is required.
	Query string `cpanel:"query"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ExpungeMailboxMessages calls the UAPI function `Mailboxes::expunge_mailbox_messages` — Delete selected messages in mailbox
//
// This function marks the selected mail messages as deleted.
//
// Available since cPanel & WHM version cPanel 64.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/mailbox-management/mailboxes-expunge_mailbox_messages.md
func (c *MailboxesClient) ExpungeMailboxMessages(ctx context.Context, args *MailboxesExpungeMailboxMessagesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Mailboxes", "expunge_mailbox_messages", args)
}

// MailboxesExpungeMessagesForMailboxGuidArgs are the parameters of the UAPI function `Mailboxes::expunge_messages_for_mailbox_guid`.
type MailboxesExpungeMessagesForMailboxGuidArgs struct {
	// The email account's name.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// The mailbox's globally unique identifier (GUID).
	//
	// Use the `Mailboxes::get_mailbox_status_list` function to list possible values for the `mailbox_guid` parameter.
	//
	// This parameter is required.
	MailboxGuid string `cpanel:"mailbox_guid"`

	// The query to select which messages you wish to remove from the mailbox.
	//
	// This parameter is required.
	Query string `cpanel:"query"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ExpungeMessagesForMailboxGuid calls the UAPI function `Mailboxes::expunge_messages_for_mailbox_guid` — Delete selected messages in mailbox by GUID
//
// This function marks the selected mailbox's messages as deleted.
//
// Available since cPanel & WHM version cPanel 64.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/mailbox-management/mailboxes-expunge_messages_for_mailbox_guid.md
func (c *MailboxesClient) ExpungeMessagesForMailboxGuid(ctx context.Context, args *MailboxesExpungeMessagesForMailboxGuidArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Mailboxes", "expunge_messages_for_mailbox_guid", args)
}

// MailboxesGetMailboxStatusListArgs are the parameters of the UAPI function `Mailboxes::get_mailbox_status_list`.
type MailboxesGetMailboxStatusListArgs struct {
	// The email account for which you you wish to request the status.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetMailboxStatusList calls the UAPI function `Mailboxes::get_mailbox_status_list` — Return cPanel account's mailbox status
//
// This function lists the account's mailbox size and globally unique identifier (GUID) by folder.
//
// Available since cPanel & WHM version cPanel 64.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/mailbox-management/mailboxes-get_mailbox_status_list.md
func (c *MailboxesClient) GetMailboxStatusList(ctx context.Context, args *MailboxesGetMailboxStatusListArgs) (*cpanel.UAPIResult[[]MailboxesGetMailboxStatusListDataItem], error) {
	return cpanel.UAPICall[[]MailboxesGetMailboxStatusListDataItem](ctx, c.c, http.MethodGet, "Mailboxes", "get_mailbox_status_list", args)
}

// MailboxesGetMailboxStatusListDataItem is a generated payload type.
type MailboxesGetMailboxStatusListDataItem struct {
	// The mailbox GUID.
	Guid string `json:"guid"`

	// The mailbox name.
	Mailbox string `json:"mailbox"`

	// The number of messages in the folder.
	Messages int64 `json:"messages"`

	// The size of the folder, in bytes.
	Vsize int64 `json:"vsize"`
}

// MailboxesHasUTF8MailboxNamesArgs are the parameters of the UAPI function `Mailboxes::has_utf8_mailbox_names`.
type MailboxesHasUTF8MailboxNamesArgs struct {
	// The user for whom to determine whether they currently use UTF-8
	// character-encoded mailbox names.
	//
	// **Note:**
	//
	// This parameter defaults to the currently-logged in user.
	User *string `cpanel:"user,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// HasUTF8MailboxNames calls the UAPI function `Mailboxes::has_utf8_mailbox_names` — Return if cPanel account's mailboxes use UTF-8
//
// This function determines whether a cPanel user currently uses UTF-8 character-encoded mailbox names.
//
// Available since cPanel & WHM version cPanel 78.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/mailbox-management/mailboxes-has_utf8_mailbox_names.md
func (c *MailboxesClient) HasUTF8MailboxNames(ctx context.Context, args *MailboxesHasUTF8MailboxNamesArgs) (*cpanel.UAPIResult[MailboxesHasUTF8MailboxNamesData], error) {
	return cpanel.UAPICall[MailboxesHasUTF8MailboxNamesData](ctx, c.c, http.MethodGet, "Mailboxes", "has_utf8_mailbox_names", args)
}

// MailboxesHasUTF8MailboxNamesData is a generated payload type.
type MailboxesHasUTF8MailboxNamesData struct {
	// Whether the user currently uses UTF-8 character-encoded mailbox names.
	// * `1` - Uses UTF-8 character-encoded mailbox names.
	// * `0` - Does **not** use UTF-8 character-encoded mailbox names.
	//
	// Possible values: `0`, `1`.
	Enabled int64 `json:"enabled"`
}

// MailboxesSetUTF8MailboxNamesArgs are the parameters of the UAPI function `Mailboxes::set_utf8_mailbox_names`.
type MailboxesSetUTF8MailboxNamesArgs struct {
	// Whether to enable or disable UTF-8 character-encoded mailbox
	// names.
	//
	// * `1` - Enable UTF-8 encoded mailbox names.
	// * `0` - Disable UTF-8 encoded mailbox names.
	//
	// Possible values: `0`, `1`.
	//
	// This parameter is required.
	Enabled int64 `cpanel:"enabled"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetUTF8MailboxNames calls the UAPI function `Mailboxes::set_utf8_mailbox_names` — Enable or disable Webmail mailbox UTF-8 encoding
//
// This function enables or disables UTF-8-encoded mailbox names on Roundcube webmail for a cPanel user's email accounts.
//
// Available since cPanel & WHM version cPanel 78.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/mailbox-management/mailboxes-set_utf8_mailbox_names.md
func (c *MailboxesClient) SetUTF8MailboxNames(ctx context.Context, args *MailboxesSetUTF8MailboxNamesArgs) (*cpanel.UAPIResult[MailboxesSetUTF8MailboxNamesData], error) {
	return cpanel.UAPICall[MailboxesSetUTF8MailboxNamesData](ctx, c.c, http.MethodGet, "Mailboxes", "set_utf8_mailbox_names", args)
}

// MailboxesSetUTF8MailboxNamesData is a generated payload type.
type MailboxesSetUTF8MailboxNamesData struct {
	// Whether the system changed mailbox name setting's status.
	// * `1` - Success.
	// * `0` - Failure.
	//
	// Possible values: `0`, `1`.
	Success int64 `json:"success"`
}
