// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// AccountExists calls the UAPI function `Nova::account_exists` — Return Nova account status
//
// This function returns whether the cPanel user has been provisioned on the AI App Builder (Nova), that is, whether the cPanel user file carries a Nova API token.
//
// **Notes:**
//
//   - This function **requires** that your package includes the AI App Builder feature.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-account_exists.md
func (c *NovaClient) AccountExists(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "Nova", "account_exists", cpanel.CombineArgs(extra...))
}

// NovaAddAPITokenArgs are the parameters of the UAPI function `Nova::add_api_token`.
type NovaAddAPITokenArgs struct {
	// The AI App Builder API token to add.
	//
	// This parameter is required.
	APIToken string `cpanel:"api_token"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddAPIToken calls the UAPI function `Nova::add_api_token` — Add an existing AI App Builder API token
//
// This function adds an existing AI App Builder API token to a cPanel user.
//
// **Notes:**
//
//   - This function **requires** that your package includes the AI App Builder feature.
//   - You can create an AI App Builder API token with the `Nova::create_account` function.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-add_api_token.md
func (c *NovaClient) AddAPIToken(ctx context.Context, args *NovaAddAPITokenArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Nova", "add_api_token", args)
}

// CanCreateDomains calls the UAPI function `Nova::can_create_domains` — Return domain creation availability
//
// This function returns whether a cPanel account can create new subdomains or addon domains.
//
// **Notes:**
//
//   - This function **requires** that your package includes the AI App Builder feature.
//   - Creating a new addon domain depends on the creation of subdomains. If the cPanel account has reached its limit for subdomains, you **cannot** create a new addon domain.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-can_create_domains.md
func (c *NovaClient) CanCreateDomains(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "Nova", "can_create_domains", cpanel.CombineArgs(extra...))
}

// CreateAccount calls the UAPI function `Nova::create_account` — Create AI App Builder API key
//
// This function creates an AI App Builder API token for a cPanel account.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-create_account.md
func (c *NovaClient) CreateAccount(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[NovaCreateAccountData], error) {
	return cpanel.UAPICall[NovaCreateAccountData](ctx, c.c, http.MethodGet, "Nova", "create_account", cpanel.CombineArgs(extra...))
}

// NovaCreateAccountData is a generated payload type.
type NovaCreateAccountData struct {
	// The AI App Builder API token for the cPanel account.
	Key string `json:"key"`
}

// NovaDiskQuotaCheckArgs are the parameters of the UAPI function `Nova::disk_quota_check`.
type NovaDiskQuotaCheckArgs struct {
	// The domain to use for the AI App Builder website.
	Domain *string `cpanel:"domain,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DiskQuotaCheck calls the UAPI function `Nova::disk_quota_check` — Return disk quota information
//
// This function checks whether a user has sufficient free space to back up the domain's document root.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-disk_quota_check.md
func (c *NovaClient) DiskQuotaCheck(ctx context.Context, args *NovaDiskQuotaCheckArgs) (*cpanel.UAPIResult[NovaDiskQuotaCheckData], error) {
	return cpanel.UAPICall[NovaDiskQuotaCheckData](ctx, c.c, http.MethodGet, "Nova", "disk_quota_check", args)
}

// NovaDiskQuotaCheckData is a generated payload type.
type NovaDiskQuotaCheckData struct {
	// The amount of space available in megabytes (MB).
	AvailableSpace int64 `json:"available_space"`

	// Whether the document root has enough space to make a backup.
	// * `1` - There is enough space.
	// * `0` - There is not enough space.
	//
	// Possible values: `1`, `0`.
	CanBackup int64 `json:"can_backup"`

	// Whether the document root is empty.
	// * `1` - Document root is empty.
	// * `0` - Document root is not empty.
	//
	// Possible values: `1`, `0`.
	IsDocRootEmpty int64 `json:"is_docroot_empty"`

	// The amount of space required in megabytes (MB) for a document root backup.
	RequiredSpace int64 `json:"required_space"`
}

// NovaEnsureAccountArgs are the parameters of the UAPI function `Nova::ensure_account`.
type NovaEnsureAccountArgs struct {
	// The color scheme Meridian is using, so Nova can match it.
	//
	// Possible values: `light`, `dark`, `auto`.
	ColorScheme *string `cpanel:"colorScheme,omitempty"`

	// The domain to use for the AI App Builder website.
	Domain *string `cpanel:"domain,omitempty"`

	// A base64-encoded prompt token to pre-populate the user's website generation goals.
	// This allows hosting companies to collect user intent before SSO and pass it through
	// to the Nova interface.
	//
	// **Requirements:**
	//
	//   * Valid base64 encoding — You can use standard or URL-safe variants.
	//   * Maximum 5000 characters after the system decodes it.
	//   * Non-empty content — The system ignores empty or whitespace-only prompts.
	//
	//
	// **Example use case:** …
	PromptToken *string `cpanel:"promptToken,omitempty"`

	// Where Nova's "Back to cPanel" control returns the user. Required for a
	// regular account and rejected for a standalone one. Must be an https URL
	// of at most 2048 characters, on the host the request was made to, with
	// the path "/frontend/meridian/index.html" (optionally prefixed by a
	// cPanel session token) and the in-product route in the fragment.
	ReturnURL *string `cpanel:"return_url,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// EnsureAccount calls the UAPI function `Nova::ensure_account` — Return Nova account SSO URL
//
// This function ensures that an AI App Builder account exists for the
// caller, then returns an SSO URL. The system reuses existing accounts.
// For entitled accounts of any tier, the system usually provisions the
// account eagerly, asynchronously, during account creation or package
// upgrades. This function is a fail-safe: it provisions the account on
// the spot for any entitled caller the eager provisioning hasn't
// already covered.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-ensure_account.md
func (c *NovaClient) EnsureAccount(ctx context.Context, args *NovaEnsureAccountArgs) (*cpanel.UAPIResult[NovaEnsureAccountData], error) {
	return cpanel.UAPICall[NovaEnsureAccountData](ctx, c.c, http.MethodGet, "Nova", "ensure_account", args)
}

// NovaEnsureAccountData is a generated payload type.
type NovaEnsureAccountData struct {
	// Whether the system created a new AI App Builder account.
	//
	// Possible values: `1`, `0`.
	Created int64 `json:"created"`

	// The SSO link to the AI App Builder.
	SSOURL string `json:"sso_url"`
}

// NovaGetAllUserNovaInfoArgs are the parameters of the UAPI function `Nova::get_all_user_nova_info`.
type NovaGetAllUserNovaInfoArgs struct {
	// The domain to use for the AI App Builder website. When you specify a
	// domain, the function returns information for that domain only.
	// Otherwise, it returns information for every domain on the account.
	Domain *string `cpanel:"domain,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetAllUserNovaInfo calls the UAPI function `Nova::get_all_user_nova_info` — Return AI App Builder domains
//
// This function returns the AI App Builder domains' information for the cPanel account.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_all_user_nova_info.md
func (c *NovaClient) GetAllUserNovaInfo(ctx context.Context, args *NovaGetAllUserNovaInfoArgs) (*cpanel.UAPIResult[[]NovaGetAllUserNovaInfoDataItem], error) {
	return cpanel.UAPICall[[]NovaGetAllUserNovaInfoDataItem](ctx, c.c, http.MethodGet, "Nova", "get_all_user_nova_info", args)
}

// NovaGetAllUserNovaInfoDataItemMetadata is a generated payload type.
type NovaGetAllUserNovaInfoDataItemMetadata struct {
	// The website's company.
	Company string `json:"company"`

	// The cPanel user's domain.
	CpanelDomainGuid string `json:"cpanelDomainGUID"`

	// The absolute path to the domain's document root directory.
	DocumentRoot string `json:"document_root"`

	// Whether the full AI App Builder Content Management System is enabled.
	// * `1` - Full CMS is enabled.
	// * `0` - Full CMS is disabled.
	//
	// Possible values: `1`, `0`.
	Fullcms int64 `json:"fullcms"`

	// The language selection for the AI App Builder Content Management System.
	Language string `json:"language"`

	// The last successful publication of the AI App Builder domain in Unix time format.
	LatestPublishDate int64 `json:"latest_publish_date"`

	// Whether the AI App Builder domain is published.
	// * `1` - Website is published.
	// * `0` - Website is not published.
	//
	// Possible values: `1`, `0`.
	PublishStatus int64 `json:"publish_status"`

	// When an AI App Builder session was last created for this domain, in Unix time format.
	SessionMintedAt int64 `json:"session_minted_at"`

	// The website ID of the created website.
	WebsiteID int64 `json:"websiteId"`
}

// NovaGetAllUserNovaInfoDataItemQuota is a generated payload type.
type NovaGetAllUserNovaInfoDataItemQuota struct {
	// The amount of space available in megabytes (MB).
	AvailableSpace int64 `json:"available_space"`

	// Whether the document root has enough space to make a backup.
	// * `1` - There is enough space.
	// * `0` - There is not enough space.
	//
	// Possible values: `1`, `0`.
	CanBackup int64 `json:"can_backup"`

	// Whether the document root is empty.
	// * `1` - Document root is empty.
	// * `0` - Document root is not empty.
	//
	// Possible values: `1`, `0`.
	IsDocRootEmpty int64 `json:"is_docroot_empty"`

	// The amount of space required in megabytes (MB) for a document root backup.
	RequiredSpace int64 `json:"required_space"`
}

// NovaGetAllUserNovaInfoDataItemStatus is a generated payload type.
type NovaGetAllUserNovaInfoDataItemStatus struct {
	// Whether the AI App Builder website is published.
	// * `1` - AI App Builder website is published.
	// * `0` - AI App Builder website is not published.
	//
	// Possible values: `1`, `0`.
	HasNovaPublished int64 `json:"has_nova_published"`

	// Whether an AI App Builder session has been started for this domain.
	// True from the moment a magic link is minted for the domain, before
	// anything is published, and independent of `has_nova_website`.
	// * `1` - User has started an AI App Builder session.
	// * `0` - User has not started an AI App Builder session.
	//
	// Possible values: `1`, `0`.
	HasNovaSession int64 `json:"has_nova_session"`

	// Whether an AI App Builder website exists for this domain.
	// * `1` - An AI App Builder website exists.
	// * `0` - No AI App Builder website exists.
	//
	// Possible values: `1`, `0`.
	HasNovaWebsite int64 `json:"has_nova_website"`

	// Whether the domain's document root directory's `index.html` file contains AI App Builder deployed content.
	// * `1` - User has an AI App Builder website.
	// * `0` - User does not have an AI App Builder website.
	//
	// Possible values: `1`, `0`.
	IsNova int64 `json:"is_nova"`

	// Whether the domain has a valid SSL certificate.
	// * `1` - Domain has a valid SSL certificate.
	// * `0` - Domain does not have a valid SSL certificate or certificate is invalid.
	//
	// Possible values: `1`, `0`.
	SSLStatus int64 `json:"ssl_status"`
}

// NovaGetAllUserNovaInfoDataItem is a generated payload type.
type NovaGetAllUserNovaInfoDataItem struct {
	// The name of the cPanel user's domain.
	Domain string `json:"domain"`

	Metadata NovaGetAllUserNovaInfoDataItemMetadata `json:"metadata"`

	Quota NovaGetAllUserNovaInfoDataItemQuota `json:"quota"`

	// Whether the domain redirects to another URL.
	// * `1` - Redirects.
	// * `0` - Doesn't redirect.
	//
	// Possible values: `1`, `0`.
	RedirectionEnabled int64 `json:"redirection_enabled"`

	// Whether the AI App Builder domain shares its document root.
	// * `1` - The document root is shared.
	// * `0` - The document root is not shared.
	//
	// Possible values: `1`, `0`.
	SharedDocRoot int64 `json:"shared_doc_root"`

	Status NovaGetAllUserNovaInfoDataItemStatus `json:"status"`
}

// NovaGetSSOLinkArgs are the parameters of the UAPI function `Nova::get_sso_link`.
type NovaGetSSOLinkArgs struct {
	// The color scheme Meridian is using, so Nova can match it.
	//
	// Possible values: `light`, `dark`, `auto`.
	ColorScheme *string `cpanel:"colorScheme,omitempty"`

	// The domain to use for the AI App Builder website.
	Domain *string `cpanel:"domain,omitempty"`

	// A base64-encoded prompt token to pre-populate the user's website generation goals.
	// This allows hosting companies to collect user intent before SSO and pass it through
	// to the Nova interface.
	//
	// **Requirements:**
	//
	//   * Valid base64 encoding — You can use standard or URL-safe variants.
	//   * Maximum 5000 characters after the system decodes it.
	//   * Non-empty content — The system ignores empty or whitespace-only prompts.
	//
	//
	// **Example use case:** …
	PromptToken *string `cpanel:"promptToken,omitempty"`

	// Where Nova's "Back to cPanel" control returns the user. Required for a
	// regular account and rejected for a standalone one. Must be an https URL
	// of at most 2048 characters, on the host the request was made to, with
	// the path "/frontend/meridian/index.html" (optionally prefixed by a
	// cPanel session token) and the in-product route in the fragment.
	ReturnURL *string `cpanel:"return_url,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetSSOLink calls the UAPI function `Nova::get_sso_link` — Return AI App Builder SSO URL
//
// This function returns an AI App Builder website's SSO URL.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_sso_link.md
func (c *NovaClient) GetSSOLink(ctx context.Context, args *NovaGetSSOLinkArgs) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "Nova", "get_sso_link", args)
}

// GetTier calls the UAPI function `Nova::get_tier` — Return the user's Nova tier snapshot
//
// This function returns the cPanel user's AI App Builder (Nova) tier snapshot for tier display and upsell.
//
// **Notes:**
//
//   - This function **requires** that your package includes the AI App Builder feature.
//   - The Meridian theme gates the Nova interface on the `nova` feature itself; this read-only call only feeds tier-aware display.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_tier.md
func (c *NovaClient) GetTier(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[NovaGetTierData], error) {
	return cpanel.UAPICall[NovaGetTierData](ctx, c.c, http.MethodGet, "Nova", "get_tier", cpanel.CombineArgs(extra...))
}

// The user's Nova tier snapshot.
type NovaGetTierData struct {
	// Whether the user has been provisioned on Nova.
	//   * `1` - The user has a Nova account.
	//   * `0` - The user does not have a Nova account.
	//
	// Possible values: `1`, `0`.
	AccountExists int64 `json:"account_exists"`

	// The user's effective AI App Builder tier (the AI_APP_BUILDER_TIER value from the cpuser file), or an empty string if none.
	Tier string `json:"tier"`
}

// NovaPollPublishArgs are the parameters of the UAPI function `Nova::poll_publish`.
type NovaPollPublishArgs struct {
	// The publish process's log file name.
	//
	// **Note:**
	//
	// This is the full path to the log file.
	//
	// This parameter is required.
	FileName string `cpanel:"file_name"`

	// The publish action's process ID, as returned by the `publish` function.
	//
	// **Note:**
	//
	//   This value must be a positive integer. The system reports `is_running`
	//   as `0` unless this process ID belongs to a running process on this
	//   account.
	//
	// This parameter is required.
	Pid int64 `cpanel:"pid"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// PollPublish calls the UAPI function `Nova::poll_publish` — Return AI App Builder publication process
//
// This function polls the publishing progress information.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-poll_publish.md
func (c *NovaClient) PollPublish(ctx context.Context, args *NovaPollPublishArgs) (*cpanel.UAPIResult[NovaPollPublishData], error) {
	return cpanel.UAPICall[NovaPollPublishData](ctx, c.c, http.MethodGet, "Nova", "poll_publish", args)
}

// NovaPollPublishData is a generated payload type.
type NovaPollPublishData struct {
	// Tracks the publishing process failure status.
	// * `1` - AI App Builder publishing process failed.
	// * `0` - AI App Builder publishing process succeeded.
	//
	// Possible values: `1`, `0`.
	Failed int64 `json:"failed"`

	// Whether the publishing process is running.
	// * `1` - AI App Builder publishing process is currently running.
	// * `0` - AI App Builder publishing process is not running.
	//
	// Possible values: `1`, `0`.
	IsRunning int64 `json:"is_running"`

	// The publishing log's content as an array of lines.
	Log []string `json:"log"`

	// Tracks the publishing process completion percentage.
	Progress int64 `json:"progress"`
}

// NovaPublishArgs are the parameters of the UAPI function `Nova::publish`.
type NovaPublishArgs struct {
	// URL to download the website archive from.
	//
	// This parameter is required.
	ArchiveURL string `cpanel:"archiveUrl"`

	// The domain to use for the AI App Builder website.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Security signature for request validation.
	//
	// This parameter is required.
	Signature string `cpanel:"signature"`

	// Unique identifier for the website.
	//
	// This parameter is required.
	UserID string `cpanel:"userId"`

	// Whether to cleanup the domain's `document_root` directory during the publication process.
	// * `1` — Remove previous files in domain's `document_root` directory during the publication process.
	// * `0` — Do **not** remove any files in domain's `document_root` directory during the publication process.
	//
	// Defaults to `0`.
	Cleanup *int64 `cpanel:"cleanup,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// Publish calls the UAPI function `Nova::publish` — Run AI App Builder domain publication
//
// This function publishes an AI App Builder website to the document root directory for the selected domain.
//
// **Note:**
//
//	This function **requires** that your package includes the AI App Builder feature.
//
// **Important:**
//
//	When you disable the AI App Builder feature, the system **disables** this function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-publish.md
func (c *NovaClient) Publish(ctx context.Context, args *NovaPublishArgs) (*cpanel.UAPIResult[NovaPublishData], error) {
	return cpanel.UAPICall[NovaPublishData](ctx, c.c, http.MethodGet, "Nova", "publish", args)
}

// NovaPublishData is a generated payload type.
type NovaPublishData struct {
	// The publish process's log file name.
	//
	// **Note:**
	//
	// This is the full path to the log file.
	FileName string `json:"file_name"`

	// The publish action's process ID.
	Pid int64 `json:"pid"`

	// The cPanel account's username.
	User string `json:"user"`
}
