// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// PostgresqlCreateDatabaseArgs are the parameters of the UAPI function `Postgresql::create_database`.
type PostgresqlCreateDatabaseArgs struct {
	// The database's name.
	//
	// **Note**:
	//
	//   If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Name string `cpanel:"name"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateDatabase calls the UAPI function `Postgresql::create_database` — Create PostgreSQL database
//
// This function creates a PostgreSQL® database.
//
// **Important:**
//
// When you disable the [PostgreSQL role](https://go.cpanel.net/howtouseserverprofiles#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-database-management/postgresql-create_database.md
func (c *PostgresqlClient) CreateDatabase(ctx context.Context, args *PostgresqlCreateDatabaseArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "create_database", args)
}


// PostgresqlCreateUserArgs are the parameters of the UAPI function `Postgresql::create_user`.
type PostgresqlCreateUserArgs struct {
	// The database user's name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Name string `cpanel:"name"`

	// The new user's password.
	//
	// This parameter is required.
	Password string `cpanel:"password"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateUser calls the UAPI function `Postgresql::create_user` — Create PostgreSQL user
//
// This function creates a PostgreSQL® database user.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-create_user.md
func (c *PostgresqlClient) CreateUser(ctx context.Context, args *PostgresqlCreateUserArgs) (*cpanel.UAPIResult[*int64], error) {
	return cpanel.UAPICall[*int64](ctx, c.c, http.MethodGet, "Postgresql", "create_user", args)
}


// PostgresqlDeleteDatabaseArgs are the parameters of the UAPI function `Postgresql::delete_database`.
type PostgresqlDeleteDatabaseArgs struct {
	// The database's name.
	//
	// This parameter is required.
	Name string `cpanel:"name"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeleteDatabase calls the UAPI function `Postgresql::delete_database` — Delete PostgreSQL database
//
// This function deletes a PostgreSQL® database.
//
// **Important:**
//
//   When you disable the [Postgres role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 54.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-database-management/postgresql-delete_database.md
func (c *PostgresqlClient) DeleteDatabase(ctx context.Context, args *PostgresqlDeleteDatabaseArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "delete_database", args)
}


// PostgresqlDeleteUserArgs are the parameters of the UAPI function `Postgresql::delete_user`.
type PostgresqlDeleteUserArgs struct {
	// The PostgreSQL user's name.
	//
	// This parameter is required.
	Name string `cpanel:"name"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeleteUser calls the UAPI function `Postgresql::delete_user` — Delete PostgreSQL user
//
// This function deletes a PostgreSQL® user.
//
// **Important:**
//
//   When you disable the [PostgreSQL role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-delete_user.md
func (c *PostgresqlClient) DeleteUser(ctx context.Context, args *PostgresqlDeleteUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "delete_user", args)
}


// GetRestrictions calls the UAPI function `Postgresql::get_restrictions` — Return PostgreSQL name length restrictions
//
// This function retrieves the PostgreSQL® user and database name length restrictions.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-database-management/postgresql-get_restrictions.md
func (c *PostgresqlClient) GetRestrictions(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[PostgresqlGetRestrictionsData], error) {
	return cpanel.UAPICall[PostgresqlGetRestrictionsData](ctx, c.c, http.MethodGet, "Postgresql", "get_restrictions", cpanel.CombineArgs(extra...))
}


// PostgresqlGetRestrictionsData is a generated payload type.
type PostgresqlGetRestrictionsData struct {
	// The maximum length of a database name.
	MaxDatabaseNameLength int64 `json:"max_database_name_length"`

	// The maximum length of a database username.
	MaxUsernameLength     int64 `json:"max_username_length"`

	// If database prefixing is enabled, this return outputs the database prefix. A valid string up to eight characters and an underscore (`_`).
	Prefix                string `json:"prefix"`
}

// PostgresqlGrantAllPrivilegesArgs are the parameters of the UAPI function `Postgresql::grant_all_privileges`.
type PostgresqlGrantAllPrivilegesArgs struct {
	// The database's name.
	//
	// **Note**
	//
	// If database prefixing is enabled, this value **must** include the database prefix for the account.
	//
	// This parameter is required.
	Database string `cpanel:"database"`

	// The database user's name.
	//
	// **Note**
	//
	// If database prefixing is enabled, this value **must** include the database prefix for the account.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GrantAllPrivileges calls the UAPI function `Postgresql::grant_all_privileges` — Enable all user privileges on PostgreSQL database
//
// This function grants all privileges for a PostgreSQL® database to a database user.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/howtouseserverprofiles#roles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-grant_all_privileges.md
func (c *PostgresqlClient) GrantAllPrivileges(ctx context.Context, args *PostgresqlGrantAllPrivilegesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "grant_all_privileges", args)
}


// ListDatabases calls the UAPI function `Postgresql::list_databases` — Return PostgreSQL databases
//
// This function lists an account's PostgreSQL® databases.
//
// **Important:**
//
//   When you disable the [*Postgres* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-database-management/postgresql-list_databases.md
func (c *PostgresqlClient) ListDatabases(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]PostgresqlListDatabasesDataItem], error) {
	return cpanel.UAPICall[[]PostgresqlListDatabasesDataItem](ctx, c.c, http.MethodGet, "Postgresql", "list_databases", cpanel.CombineArgs(extra...))
}


// PostgresqlListDatabasesDataItem is a generated payload type.
type PostgresqlListDatabasesDataItem struct {
	// The database name.
	Database  string `json:"database"`

	// The disk space that the database uses, in bytes.
	DiskUsage int64 `json:"disk_usage"`

	// An array of database usernames.
	//
	// **Note:**
	//
	//   If no users exist on a database, the function returns an empty array
	Users     []string `json:"users"`
}

// ListUsers calls the UAPI function `Postgresql::list_users` — Return PostgreSQL users
//
// This function lists an account's PostgreSQL® database users.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-list_users.md
func (c *PostgresqlClient) ListUsers(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]string], error) {
	return cpanel.UAPICall[[]string](ctx, c.c, http.MethodGet, "Postgresql", "list_users", cpanel.CombineArgs(extra...))
}


// PostgresqlRenameDatabaseArgs are the parameters of the UAPI function `Postgresql::rename_database`.
type PostgresqlRenameDatabaseArgs struct {
	// The database's new name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Newname string `cpanel:"newname"`

	// The database's current name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Oldname string `cpanel:"oldname"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RenameDatabase calls the UAPI function `Postgresql::rename_database` — Update PostgreSQL database name
//
// This function renames a PostgreSQL® database.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-database-management/postgresql-rename_database.md
func (c *PostgresqlClient) RenameDatabase(ctx context.Context, args *PostgresqlRenameDatabaseArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "rename_database", args)
}


// PostgresqlRenameUserArgs are the parameters of the UAPI function `Postgresql::rename_user`.
type PostgresqlRenameUserArgs struct {
	// The database user's new name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Newname string `cpanel:"newname"`

	// The database user's current name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Oldname string `cpanel:"oldname"`

	// The database user's new password.
	//
	// This parameter is required.
	Password string `cpanel:"password"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RenameUser calls the UAPI function `Postgresql::rename_user` — Update PostgreSQL username
//
// This function renames a PostgreSQL® database user.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-rename_user.md
func (c *PostgresqlClient) RenameUser(ctx context.Context, args *PostgresqlRenameUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "rename_user", args)
}


// PostgresqlRenameUserNoPasswordArgs are the parameters of the UAPI function `Postgresql::rename_user_no_password`.
type PostgresqlRenameUserNoPasswordArgs struct {
	// The database user's new name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Newname string `cpanel:"newname"`

	// The database user's current name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	Oldname string `cpanel:"oldname"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RenameUserNoPassword calls the UAPI function `Postgresql::rename_user_no_password` — Update PostgreSQL username without password
//
// This function renames a PostgreSQL® database user.
//
// **Warning:**
//
// * If you rename a PostgreSQL user, you **must** set the password for the database user. This is required because of the md5 hash that PostgreSQL creates to store user passwords.
// * We **strongly** recommend that you use the `Postgresql::rename_user function` instead of this one.
//
// **Important:**
//
// When you disable the  [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-rename_user_no_password.md
func (c *PostgresqlClient) RenameUserNoPassword(ctx context.Context, args *PostgresqlRenameUserNoPasswordArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "rename_user_no_password", args)
}


// PostgresqlRevokeAllPrivilegesArgs are the parameters of the UAPI function `Postgresql::revoke_all_privileges`.
type PostgresqlRevokeAllPrivilegesArgs struct {
	// The database's name.
	//
	// **Note**
	//
	// If database prefixing is enabled, this value **must** include the database prefix for the account.
	//
	// This parameter is required.
	Database string `cpanel:"database"`

	// The database user's name.
	//
	// **Note**
	//
	// If database prefixing is enabled, this value **must** include the database prefix for the account.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RevokeAllPrivileges calls the UAPI function `Postgresql::revoke_all_privileges` — Remove PostgreSQL user privileges
//
// This function revokes all privileges for a PostgreSQL® database from a database user.
//
// **Important:**
//
// When you disable the [*PostgreSQL* role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-revoke_all_privileges.md
func (c *PostgresqlClient) RevokeAllPrivileges(ctx context.Context, args *PostgresqlRevokeAllPrivilegesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "revoke_all_privileges", args)
}


// PostgresqlSetPasswordArgs are the parameters of the UAPI function `Postgresql::set_password`.
type PostgresqlSetPasswordArgs struct {
	// The user's new password.
	//
	// This parameter is required.
	Password string `cpanel:"password"`

	// The database user's name.
	//
	// **Note:**
	//
	// If database prefixing is enabled, this parameter **must** include the database prefix for the account.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetPassword calls the UAPI function `Postgresql::set_password` — Update PostgreSQL user password
//
// This function changes a PostgreSQL® database user's password.
//
// **Important:**
//
//   When you disable the [Postgres role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-set_password.md
func (c *PostgresqlClient) SetPassword(ctx context.Context, args *PostgresqlSetPasswordArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "set_password", args)
}


// UpdatePrivileges calls the UAPI function `Postgresql::update_privileges` — Update PostgreSQL® privileges
//
// This function synchronizes PostgreSQL® database user privileges on an account.
//
// Some versions of PostgreSQL are ANSI SQL-92 compliant and do not support recursive grants,
// wildcard grants, or future grants. If you use phpPgAdmin, or manually create new tables, and
// you want multiple PostgreSQL users to access your PostgreSQL tables, you may either call this
// API function or click _Synchronize Grants_ in the _PostgreSQL Databases_ interface
// (_Home >> Databases >> PostgreSQL Databases_) after you add a table.
//
// **Important:**
//
// When you disable the [PostgreSQL role](https://go.cpanel.net/serverroles), the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 84.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/postgresql-user-management/postgresql-update_privileges.md
func (c *PostgresqlClient) UpdatePrivileges(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Postgresql", "update_privileges", cpanel.CombineArgs(extra...))
}

