// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// GetUsages calls the UAPI function `ResourceUsage::get_usages` — Return resource usage and custom statistics
//
// This function retrieves resource usage and custom statistics for a cPanel user account.
//
// Available since cPanel & WHM version cPanel 70.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/resource-usage-and-statistics/resourceusage-get_usages.md
func (c *ResourceUsageClient) GetUsages(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]ResourceUsageGetUsagesDataItem], error) {
	return cpanel.UAPICall[[]ResourceUsageGetUsagesDataItem](ctx, c.c, http.MethodGet, "ResourceUsage", "get_usages", cpanel.CombineArgs(extra...))
}

// ResourceUsageGetUsagesDataItem is a generated payload type.
type ResourceUsageGetUsagesDataItem struct {
	// The resource's UI display name.
	Description string `json:"description"`

	// An error message, if applicable.
	Error *string `json:"error"`

	// The resource's defined output format.
	//
	// * `format_bytes`
	// * `format_bytes_per_second`
	// * `percent`
	// * `null` — No defined output format.
	//
	// **Note:**
	//
	// Third-party modules will return their defined formatter value.
	FormatTer string `json:"formatter"`

	// The resource's reference name.
	// * `disk_usage`
	// * `filesusage` - This function **only** returns this value if the *Display File Usage information in the cPanel stats bar* setting is enabled in the *Display* section of WHM's [*Tweak Settings*](https://go.cpanel.net/whmdocsTweakSettings#display) interface (*WHM >> Home >> Server Configuration >> Tweak Settings*).
	// * `cachedmysqldiskusage`
	// * `cachedpost …
	ID string `json:"id"`

	// The resources's maximum usage value.
	//
	// **Note:**
	//
	//  This function returns an null value for an (unlimited) quota.
	Maximum *int64 `json:"maximum"`

	// The resource's defined URL link to its corresponding interface, in applicable.
	URL string `json:"url"`

	// The resource's current usage value.
	Usage int64 `json:"usage"`
}
