// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// SitejetAddAPITokenArgs are the parameters of the UAPI function `Sitejet::add_api_token`.
type SitejetAddAPITokenArgs struct {
	// The Sitejet API token to add.
	//
	// This parameter is required.
	APIToken string `cpanel:"api_token"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddAPIToken calls the UAPI function `Sitejet::add_api_token` — Add an existing Sitejet API token.
//
// This function adds an existing Sitejet API token to a cPanel user.
//
// **Note:**
//
// You can create a Sitejet API token with the `Sitejet:create_account` function.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/add_sitejet_api_token.md
func (c *SitejetClient) AddAPIToken(ctx context.Context, args *SitejetAddAPITokenArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Sitejet", "add_api_token", args)
}


// CanCreateDomains calls the UAPI function `Sitejet::can_create_domains` — Return Domain Availability
//
// This function returns whether a cPanel account can create new subdomains or addon domains.
//
// **Note:**
//
// Creating a new addon domain is dependent on the creation of subdomains. If the cPanel account has reached its limit for subdomains, you cannot create a new addon domain, even if the limit for addon domains has not been reached.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/can_create_domains.md
func (c *SitejetClient) CanCreateDomains(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Sitejet", "can_create_domains", cpanel.CombineArgs(extra...))
}


// CreateAccount calls the UAPI function `Sitejet::create_account` — Generate a Sitejet API key.
//
// This function creates a Sitejet API token for a cPanel account.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/create_sitejet_account.md
func (c *SitejetClient) CreateAccount(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[SitejetCreateAccountData], error) {
	return cpanel.UAPICall[SitejetCreateAccountData](ctx, c.c, http.MethodGet, "Sitejet", "create_account", cpanel.CombineArgs(extra...))
}


// SitejetCreateAccountData is a generated payload type.
type SitejetCreateAccountData struct {
	// The Sitejet API token for the cPanel account.
	Key string `json:"key"`
}

// SitejetCreateRestorePointArgs are the parameters of the UAPI function `Sitejet::create_restore_point`.
type SitejetCreateRestorePointArgs struct {
	// A cPanel account's domain.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateRestorePoint calls the UAPI function `Sitejet::create_restore_point` — Create a restore point.
//
// This function creates a restore point for a domain's document root and removes the domain's files.
//
// Available since cPanel & WHM version 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/create_restore_point.md
func (c *SitejetClient) CreateRestorePoint(ctx context.Context, args *SitejetCreateRestorePointArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Sitejet", "create_restore_point", args)
}


// SitejetCreateWebsiteArgs are the parameters of the UAPI function `Sitejet::create_website`.
type SitejetCreateWebsiteArgs struct {
	// The name of the company the website represents.
	//
	// This parameter is required.
	Company string `cpanel:"company"`

	// A cPanel account's domain.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Assign website to other user.
	AssignTo *string `cpanel:"assignTo,omitempty"`

	// The city where the company or website owner is located.
	City *string `cpanel:"city,omitempty"`

	// The country where the company or website owner is located.
	Country *string `cpanel:"country,omitempty"`

	// The email address of the website owner.
	Email *string `cpanel:"email,omitempty"`

	// The first name of the website owner.
	FirstName *string `cpanel:"firstname,omitempty"`

	// The language to use for the Sitejet Website Builder.
	Language *string `cpanel:"language,omitempty"`

	// The last name of the website owner.
	Lastname *string `cpanel:"lastname,omitempty"`

	// Additional metadata for the website.
	Metadata *string `cpanel:"metadata,omitempty"`

	// Additional notes about the website.
	Note *string `cpanel:"note,omitempty"`

	// The phone number of the company or website owner.
	Phone *string `cpanel:"phone,omitempty"`

	// The street address of the company or website owner.
	Street *string `cpanel:"street,omitempty"`

	// The website title.
	Title *string `cpanel:"title,omitempty"`

	// The zip code where the company or website owner is located.
	Zip *string `cpanel:"zip,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateWebsite calls the UAPI function `Sitejet::create_website` — Create Sitejet domain ID
//
// This function creates a Sitejet ID for the specified domain.
//
// **Note:**
//
// A unique Sitejet ID is assigned to each domain on the cPanel account.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/create_sitejet_website.md
func (c *SitejetClient) CreateWebsite(ctx context.Context, args *SitejetCreateWebsiteArgs) (*cpanel.UAPIResult[SitejetCreateWebsiteData], error) {
	return cpanel.UAPICall[SitejetCreateWebsiteData](ctx, c.c, http.MethodGet, "Sitejet", "create_website", args)
}


// SitejetCreateWebsiteData is a generated payload type.
type SitejetCreateWebsiteData struct {
	// The website ID of the created website.
	WebsiteID int64 `json:"websiteID"`
}

// SitejetGetAllUserSitejetInfoArgs are the parameters of the UAPI function `Sitejet::get_all_user_sitejet_info`.
type SitejetGetAllUserSitejetInfoArgs struct {
	// The single domain to return Sitejet information.
	Domain *string `cpanel:"domain,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetAllUserSitejetInfo calls the UAPI function `Sitejet::get_all_user_sitejet_info` — Return Sitejet domains
//
// This function returns the Sitejet domains' information for the cPanel account.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/get_all_user_sitejet_info.md
func (c *SitejetClient) GetAllUserSitejetInfo(ctx context.Context, args *SitejetGetAllUserSitejetInfoArgs) (*cpanel.UAPIResult[[]SitejetGetAllUserSitejetInfoDataItem], error) {
	return cpanel.UAPICall[[]SitejetGetAllUserSitejetInfoDataItem](ctx, c.c, http.MethodGet, "Sitejet", "get_all_user_sitejet_info", args)
}


// SitejetGetAllUserSitejetInfoDataItemMetadata is a generated payload type.
type SitejetGetAllUserSitejetInfoDataItemMetadata struct {
	// The website's comapany.
	Company           string `json:"company"`

	// The cPanel user's domain.
	CpanelDomainGuid  string `json:"cpanelDomainGUID"`

	// Whether the full Sitejet Content Management System is enabled.
	// * `1` - Full CMS is enabled.
	// * `0` - Full CMS is disabled.
	//
	// Possible values: `1`, `0`.
	Fullcms           json.RawMessage `json:"fullcms"`

	// The language selection for the Sitejet Content Management System.
	Language          string `json:"language"`

	// The last successful publication of the Sitejet domain in Unix time format.
	LatestPublishDate int64 `json:"latest_publish_date"`

	// Whether the Sitejet domain is published.
	// * `1` - Website is published.
	// * `0` - Website is not published.
	//
	// Possible values: `1`, `0`.
	PublishStatus     int64 `json:"publish_status"`

	// The website ID of the created website.
	WebsiteID         int64 `json:"websiteId"`
}

// SitejetGetAllUserSitejetInfoDataItemQuota is a generated payload type.
type SitejetGetAllUserSitejetInfoDataItemQuota struct {
	// The amount of space available in megabytes (MB).
	AvailableSpace int64 `json:"available_space"`

	// Whether the document root has enough space to make a backup.
	// * `1` - There is enough space.
	// * `0` - There is not enough space.
	//
	// Possible values: `1`, `0`.
	CanBackup      json.RawMessage `json:"can_backup"`

	// Whether the document root is empty.
	// * `1` - Document root is empty.
	// * `0` - Document root is not empty.
	//
	// Possible values: `1`, `0`.
	IsEmptyDocRoot json.RawMessage `json:"is_empty_docroot"`

	// The amount of space required in megabytes (MB) for a document root backup.
	RequiredSpace  int64 `json:"required_space"`
}

// SitejetGetAllUserSitejetInfoDataItemStatus is a generated payload type.
type SitejetGetAllUserSitejetInfoDataItemStatus struct {
	// Whether the Sitejet website is published.
	// * `1` - Sitejet website is published.
	// * `0` - Sitejet website is not published.
	//
	// Possible values: `1`, `0`.
	HasSitejetPublished int64 `json:"has_sitejet_published"`

	// Whether the domain's document root diretory contains a Sitejet directory.
	// * `1` - User has created a Sitejet website.
	// * `0` - User has not created a Sitejet website.
	//
	// Possible values: `1`, `0`.
	HasSitejetWebsite   int64 `json:"has_sitejet_website"`

	// Whether the domain's document root diretory's `index.html` file contains Sitejet deployed content.
	// * `1` - User has a Sitejet website.
	// * `0` - User does not have a Sitejet website.
	//
	// Possible values: `1`, `0`.
	IsSitejet           int64 `json:"is_sitejet"`

	// Whether the domain has a valid SSL certificate.
	// * `1` - Domain has a valid SSL certificate.
	// * `0` - Domain does not have a valid SSL certificate or certificate is invalid.
	//
	// Possible values: `1`, `0`.
	SSLStatus           int64 `json:"ssl_status"`
}

// SitejetGetAllUserSitejetInfoDataItem is a generated payload type.
type SitejetGetAllUserSitejetInfoDataItem struct {
	// The name of the cPanel user's domain.
	Domain                  string `json:"domain"`

	// Whether the sitejet domain has a restore point.
	// * `1` – Restore point is available.
	// * `0` – Restore point is not available.
	//
	// Possible values: `1`, `0`.
	IsRestorePointAvailable int64 `json:"is_restore_point_available"`

	// Whether the domain is a temporary domain (for example, cpanel.site).
	// * `1` – Domain is a temporary domain.
	// * `0` – Domain is not a temporary domain.
	//
	// Possible values: `1`, `0`.
	IsTemporaryDomain       int64 `json:"is_temporary_domain"`

	Metadata                SitejetGetAllUserSitejetInfoDataItemMetadata `json:"metadata"`

	Quota                   SitejetGetAllUserSitejetInfoDataItemQuota `json:"quota"`

	// Whether the domain redirects to another URL.
	// * 1 - Redirects.
	// * 0 - Doesn't redirect.
	//
	// Possible values: `1`, `0`.
	RedirectionEnabled      int64 `json:"redirection_enabled"`

	// whether the sitejet domain is sharing the document_root.
	// * 1 - document_root is shared.
	// * 0 - document_root is not shared.
	//
	// Possible values: `1`, `0`.
	SharedDocRoot           int64 `json:"shared_doc_root"`

	Status                  SitejetGetAllUserSitejetInfoDataItemStatus `json:"status"`
}

// GetAPIToken calls the UAPI function `Sitejet::get_api_token` — Return Sitejet API token
//
// This function returns the cPanel account's Sitejet API token.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/get_sitejet_api_token.md
func (c *SitejetClient) GetAPIToken(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "Sitejet", "get_api_token", cpanel.CombineArgs(extra...))
}


// SitejetGetPreviewURLArgs are the parameters of the UAPI function `Sitejet::get_preview_url`.
type SitejetGetPreviewURLArgs struct {
	// The Sitejet website ID for the domain.
	//
	// This parameter is required.
	WebsiteID int64 `cpanel:"websiteId"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetPreviewURL calls the UAPI function `Sitejet::get_preview_url` — Return Sitejet preview URL
//
// This function returns a Sitejet website's preview URL.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/get_sitejet_preview_url.md
func (c *SitejetClient) GetPreviewURL(ctx context.Context, args *SitejetGetPreviewURLArgs) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "Sitejet", "get_preview_url", args)
}


// SitejetGetSSOLinkArgs are the parameters of the UAPI function `Sitejet::get_sso_link`.
type SitejetGetSSOLinkArgs struct {
	// The cPanel account's Sitejet domain.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// The cPanel interface referral URL.
	//
	// This parameter is required.
	Referrer string `cpanel:"referrer"`

	// Specifies which Sitejet SaaS user interface mode the user will be redirected to.
	//
	// Possible values: `prompt`, `ai`, `template`.
	UIMode *string `cpanel:"ui_mode,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetSSOLink calls the UAPI function `Sitejet::get_sso_link` — Return Sitejet SSO URL
//
// This function returns a Sitejet website's SSO URL.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/get_sitejet_sso_link.md
func (c *SitejetClient) GetSSOLink(ctx context.Context, args *SitejetGetSSOLinkArgs) (*cpanel.UAPIResult[string], error) {
	return cpanel.UAPICall[string](ctx, c.c, http.MethodGet, "Sitejet", "get_sso_link", args)
}


// GetTemplates calls the UAPI function `Sitejet::get_templates` — Return Sitejet templates
//
// This function fetches the list of available Sitejet templates.
//
// This function is deprecated upstream.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/get_sitejet_templates.md
//
// Deprecated: cPanel & WHM mark this function as deprecated.
func (c *SitejetClient) GetTemplates(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]SitejetGetTemplatesDataItem], error) {
	return cpanel.UAPICall[[]SitejetGetTemplatesDataItem](ctx, c.c, http.MethodGet, "Sitejet", "get_templates", cpanel.CombineArgs(extra...))
}


// SitejetGetTemplatesDataItem is a generated payload type.
type SitejetGetTemplatesDataItem struct {
	// The templates creation date.
	CreatedAt   string `json:"createdAt"`

	// The template's description.
	Description string `json:"description"`

	// The template's ID.
	ID          int64 `json:"id"`

	// The relative path to the template image on the SiteJet CMS website.
	Image       string `json:"image"`

	// The template's name.
	Name        string `json:"name"`

	// The website's preview URL.
	PreviewURL  string `json:"previewUrl"`

	// The template's catagory search tags.
	Tags        []string `json:"tags"`
}

// SitejetRestoreDocumentRootArgs are the parameters of the UAPI function `Sitejet::restore_document_root`.
type SitejetRestoreDocumentRootArgs struct {
	// A cPanel account's domain.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RestoreDocumentRoot calls the UAPI function `Sitejet::restore_document_root` — Restore a domain from the restore point.
//
// This function reverts a document root to the restore point.
//
// Available since cPanel & WHM version 120.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/restore_document_root.md
func (c *SitejetClient) RestoreDocumentRoot(ctx context.Context, args *SitejetRestoreDocumentRootArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Sitejet", "restore_document_root", args)
}


// SitejetSetTemplateArgs are the parameters of the UAPI function `Sitejet::set_template`.
type SitejetSetTemplateArgs struct {
	// A cPanel account's domain.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// The Sitejet template's ID.
	//
	// This parameter is required.
	TemplateID string `cpanel:"templateId"`

	// The Sitejet template name.
	//
	// This parameter is required.
	TemplateName string `cpanel:"templateName"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetTemplate calls the UAPI function `Sitejet::set_template` — Update Sitejet template
//
// This function sets a Sitejet website's template.
//
// This function is deprecated upstream.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/set_sitejet_template.md
//
// Deprecated: cPanel & WHM mark this function as deprecated.
func (c *SitejetClient) SetTemplate(ctx context.Context, args *SitejetSetTemplateArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Sitejet", "set_template", args)
}


// SitejetStartPublishArgs are the parameters of the UAPI function `Sitejet::start_publish`.
type SitejetStartPublishArgs struct {
	// The domain for the Sitejet website.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Whether to cleanup the domain's `document_root` directory during the publication process.
	// * `1` — Remove previous files in domain's `document_root` directory during the publication process.
	// * `0` — Do **not** remove any files in domain's `document_root` directory during the publication process.
	Cleanup *int64 `cpanel:"cleanup,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// StartPublish calls the UAPI function `Sitejet::start_publish` — Publish Sitejet domain
//
// This function publishes a domain's Sitejet website.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/start_publish_sitejet.md
func (c *SitejetClient) StartPublish(ctx context.Context, args *SitejetStartPublishArgs) (*cpanel.UAPIResult[SitejetStartPublishData], error) {
	return cpanel.UAPICall[SitejetStartPublishData](ctx, c.c, http.MethodGet, "Sitejet", "start_publish", args)
}


// SitejetStartPublishData is a generated payload type.
type SitejetStartPublishData struct {
	// **Deprecated.** The publish process's log file name.
	//
	// The `poll_publish` function no longer requires this value; it derives the log path server-side from `pid`. This field is retained for backward compatibility and may be removed in a future release.
	//
	// The system stores this file in the `logs/` directory, relative to the cPanel account's home directory.
	FileName string `json:"file_name"`

	// The publish action's process ID.
	Pid      int64 `json:"pid"`
}
