// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// TeamAddRolesArgs are the parameters of the UAPI function `Team::add_roles`.
type TeamAddRolesArgs struct {
	// The role or roles to add to the team user. Current roles include admin, database, email, web.
	//
	// This parameter is required.
	Role string `cpanel:"role"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddRoles calls the UAPI function `Team::add_roles` — Add roles to a team user
//
// This function adds roles to a team user.
//
// **Note:**
//
//	This action may result in team users gaining access to team owner level privileges.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-add_roles.md
func (c *TeamClient) AddRoles(ctx context.Context, args *TeamAddRolesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "add_roles", args)
}

// TeamAddTeamUserArgs are the parameters of the UAPI function `Team::add_team_user`.
type TeamAddTeamUserArgs struct {
	// The contact email for the new team user.
	//
	// This parameter is required.
	Email1 string `cpanel:"email1"`

	// The username of the team user. Follows cPanel standards.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Send an email to the team user that allows them to set their own password.
	// * `1` - Enabled.
	//
	// **Note:**
	//
	//  * You must pass either the `password` or `activation_email` parameter.
	ActivationEmail *int64 `cpanel:"activation_email,omitempty"`

	// The secondary email for the new team user.
	Email2 *string `cpanel:"email2,omitempty"`

	// The epoch time on which the team user account expires, or the offset from the current time, in days. Integers are treated as Unix Epoch Time unless followed by 'days'.
	ExpireDate any `cpanel:"expire_date,omitempty"`

	// The reason for expiration.
	ExpireReason *string `cpanel:"expire_reason,omitempty"`

	// Notes about the new team user. This field should not contain private information. Maximum of 100 characters.
	Notes *string `cpanel:"notes,omitempty"`

	// The password to set for the new team user.
	//
	// **Note:**
	//
	//  * You must pass either the `password` or `activation_email` parameter.
	Password *string `cpanel:"password,omitempty"`

	// A comma-separated list of roles assigned to the new team user. Current roles include admin, database, email, web.
	//
	// **Note:**
	//
	//  * This parameter is named `roles`, not `role`. This function rejects the `role` parameter with an error.
	//  * A team user with no roles **cannot** use any features. To assign roles after you create the team user, use the `set_roles` or `add_roles` functions.
	Roles *string `cpanel:"roles,omitempty"`

	// Whether to create an email subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create an email subaccount.
	// * `0` - **Do Not** create an email subaccount.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesEmailEnabled *int64 `cpanel:"services.email.enabled,omitempty"`

	// The maximum amount of disk space, in megabytes (MB), allocated to the team user's email account.
	//
	// * `0` or `unlimited` - The subaccount has unlimited disk space.
	//
	// This value defaults to the defined system value.
	//
	// **Note:**
	//
	// This value **cannot** be larger than the system's maximum email quota.
	ServicesEmailQuota *string `cpanel:"services.email.quota,omitempty"`

	// Whether to create an FTP subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create an FTP subaccount.
	// * `0` - **Do Not** create an FTP subaccount.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesFTPEnabled *int64 `cpanel:"services.ftp.enabled,omitempty"`

	// The team user's FTP home directory, relative to the cPanel account's home directory.
	//
	// **Note:**
	//
	// * This parameter is **required** if you enabled the `services.ftp.homedir` parameter.
	// * The directory **must** exist.
	ServicesFTPHomedir *string `cpanel:"services.ftp.homedir,omitempty"`

	// Whether to create a Web Disk subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create a Web Disk subaccount.
	// * `0` - **Do Not** create a Web Disk subaccount.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskEnabled *int64 `cpanel:"services.webdisk.enabled,omitempty"`

	// Whether to enable the Web Disk Digest Authentication.
	//
	// * `1` - Enabled.
	// * `0` - Disabled.
	//
	// **Note:**
	//
	// * **Only** enable Digest Authentication for clients that require additional compatibility support on
	//   certain versions of Windows® operating systems. This compatibility support is **only** required on servers
	//   that use a self-signed certificate for the `cpsrvd` and `cpdavd` daemons.
	// * We recommend that you do **not** use Digest Authentication.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskEnabledigest *int64 `cpanel:"services.webdisk.enabledigest,omitempty"`

	// The team user's Web Disk home directory, relative to the cPanel account's home directory.
	//
	// **Note:**
	//
	// This parameter is **required** if you enable the `services.webdisk.enabled` parameter.
	ServicesWebdiskHomedir *string `cpanel:"services.webdisk.homedir,omitempty"`

	// The team user's file permissions for its Web Disk home directory.
	//
	// * `ro` - Read-only permissions.
	// * `rw` - Read and write permissions.
	//
	// **Note:**
	//
	//  The `services.webdisk.homedir` parameter determines the team user's Web Disk home directory.
	//
	// Defaults to `rw`.
	ServicesWebdiskPerms *string `cpanel:"services.webdisk.perms,omitempty"`

	// Whether to set the directory's permissions to public or private.
	//
	// * `1` - Private (`0700`).
	// * `0` - Public (`0755`).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskPrivate *int64 `cpanel:"services.webdisk.private,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AddTeamUser calls the UAPI function `Team::add_team_user` — Add a team user
//
// This function creates and adds a new team user.
//
// **Note:**
//
//	This action may result in team users gaining access to team owner level privileges.
//
// Available since cPanel & WHM version 104.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-add_team_user.md
func (c *TeamClient) AddTeamUser(ctx context.Context, args *TeamAddTeamUserArgs) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "Team", "add_team_user", args)
}

// TeamCancelExpireArgs are the parameters of the UAPI function `Team::cancel_expire`.
type TeamCancelExpireArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CancelExpire calls the UAPI function `Team::cancel_expire` — Stop a team user from expiring
//
// This function stops a team user from expiring.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-cancel_expire.md
func (c *TeamClient) CancelExpire(ctx context.Context, args *TeamCancelExpireArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "cancel_expire", args)
}

// TeamEditTeamUserArgs are the parameters of the UAPI function `Team::edit_team_user`.
type TeamEditTeamUserArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The role or roles to add to the team user.
	AddRole *string `cpanel:"add_role,omitempty"`

	// The primary contact email address to set for the team user.
	Email1 *string `cpanel:"email1,omitempty"`

	// The secondary contact email address to set for the team user.
	Email2 *string `cpanel:"email2,omitempty"`

	// The reason for expiration.
	ExpireReason *string `cpanel:"expire_reason,omitempty"`

	// Notes about the new team user. This field should not contain private information.
	Notes *string `cpanel:"notes,omitempty"`

	// The password to set for the team user.
	Password *string `cpanel:"password,omitempty"`

	// The role or roles to remove from the team user.
	RemoveRole *string `cpanel:"remove_role,omitempty"`

	// Whether to create or remove an email subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create and associate an email subaccount.
	// * `0` - Remove any associated email subaccounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesEmailEnabled *int64 `cpanel:"services.email.enabled,omitempty"`

	// The maximum amount of disk space, in megabytes (MB), allocated to the team user's email account.
	//
	// * `0` or `unlimited` - The subaccount has unlimited disk space.
	//
	// This value defaults to the defined system value.
	//
	// **Note:**
	//
	// This value **cannot** be larger than the system's maximum email quota.
	ServicesEmailQuota *string `cpanel:"services.email.quota,omitempty"`

	// Whether to create or remove an FTP subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create and associate an FTP subaccount.
	// * `0` - Remove any associated FTP subaccounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesFTPEnabled *int64 `cpanel:"services.ftp.enabled,omitempty"`

	// The team user's FTP home directory, relative to the cPanel account's home directory.
	//
	// **Note:**
	//
	// * This parameter is **required** if you enabled the `services.ftp.homedir` parameter.
	// * The directory **must** exist.
	ServicesFTPHomedir *string `cpanel:"services.ftp.homedir,omitempty"`

	// Whether to create or remove a Web Disk subaccount for the team user. A subaccount is always created for a team user, but it does not have any associated service subaccounts by default.
	//
	// * `1` - Create and associate a Web Disk subaccount.
	// * `0` - Remove any associated Web Disk subaccounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskEnabled *int64 `cpanel:"services.webdisk.enabled,omitempty"`

	// Whether to enable the Web Disk Digest Authentication.
	//
	// * `1` - Enabled.
	// * `0` - Disabled.
	//
	// **Note:**
	//
	// * **Only** enable Digest Authentication for clients that require additional compatibility support on
	//   certain versions of Windows® operating systems. This compatibility support is **only** required on servers
	//   that use a self-signed certificate for the `cpsrvd` and `cpdavd` daemons.
	// * We recommend that you do **not** use Digest Authentication.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskEnabledigest *int64 `cpanel:"services.webdisk.enabledigest,omitempty"`

	// The team user's Web Disk home directory, relative to the cPanel account's home directory.
	//
	// **Note:**
	//
	// This parameter is **required** if you enable the `services.webdisk.enabled` parameter.
	ServicesWebdiskHomedir *string `cpanel:"services.webdisk.homedir,omitempty"`

	// The team user's file permissions for its Web Disk home directory.
	//
	// * `ro` - Read-only permissions.
	// * `rw` - Read and write permissions.
	//
	// **Note:**
	//
	//  The `services.webdisk.homedir` parameter determines the team user's Web Disk home directory.
	//
	// Defaults to `rw`.
	ServicesWebdiskPerms *string `cpanel:"services.webdisk.perms,omitempty"`

	// Whether to set the directory's permissions to public or private.
	//
	// * `1` - Private (`0700`).
	// * `0` - Public (`0755`).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ServicesWebdiskPrivate *int64 `cpanel:"services.webdisk.private,omitempty"`

	// The epoch time the team user account expires on or the offset in days.
	SetExpire any `cpanel:"set_expire,omitempty"`

	// The role or roles to set for the team user.
	SetRole *string `cpanel:"set_role,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// EditTeamUser calls the UAPI function `Team::edit_team_user` — Edit a team user
//
// This function modifies a team user.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-edit_team_user.md
func (c *TeamClient) EditTeamUser(ctx context.Context, args *TeamEditTeamUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "edit_team_user", args)
}

// GetTeamUsersWithRolesCount calls the UAPI function `Team::get_team_users_with_roles_count` — Get number of team users with roles
//
// This function returns the current and maximum number of team users with roles.
//
// Available since cPanel & WHM version 118.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-get_team_users_with_roles_count.md
func (c *TeamClient) GetTeamUsersWithRolesCount(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[TeamGetTeamUsersWithRolesCountData], error) {
	return cpanel.UAPICall[TeamGetTeamUsersWithRolesCountData](ctx, c.c, http.MethodGet, "Team", "get_team_users_with_roles_count", cpanel.CombineArgs(extra...))
}

// TeamGetTeamUsersWithRolesCountData is a generated payload type.
type TeamGetTeamUsersWithRolesCountData struct {
	// Maximum number of team users with roles.
	//
	// **Note:**
	//
	// This value is stored in the package.
	Max int64 `json:"max"`

	// The current number of team users with roles.
	Used int64 `json:"used"`
}

// TeamListTeamArgs are the parameters of the UAPI function `Team::list_team`.
type TeamListTeamArgs struct {
	// The format in which the team data is listed.
	Format *string `cpanel:"format,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListTeam calls the UAPI function `Team::list_team` — List Team Users
//
// This function lists the team users connected to a cPanel account.
// This list is given in an array by default, but can be given in a hash.
//
// Available since cPanel & WHM version 104.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-list_team.md
func (c *TeamClient) ListTeam(ctx context.Context, args *TeamListTeamArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "list_team", args)
}

// TeamPasswordResetRequestArgs are the parameters of the UAPI function `Team::password_reset_request`.
type TeamPasswordResetRequestArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// PasswordResetRequest calls the UAPI function `Team::password_reset_request` — Sends a password reset request link to team user.
//
// This function enables a team user to reset the password by sending a password reset request link.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-password_reset_request.md
func (c *TeamClient) PasswordResetRequest(ctx context.Context, args *TeamPasswordResetRequestArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "password_reset_request", args)
}

// TeamReinstateTeamUserArgs are the parameters of the UAPI function `Team::reinstate_team_user`.
type TeamReinstateTeamUserArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ReinstateTeamUser calls the UAPI function `Team::reinstate_team_user` — Reinstate a team user
//
// This function reinstates a team user by removing any suspended or expired statuses. The reason field is also cleared.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-reinstate_team_user.md
func (c *TeamClient) ReinstateTeamUser(ctx context.Context, args *TeamReinstateTeamUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "reinstate_team_user", args)
}

// TeamRemoveRolesArgs are the parameters of the UAPI function `Team::remove_roles`.
type TeamRemoveRolesArgs struct {
	// The role or roles to remove from the team user.
	//
	// This parameter is required.
	Role string `cpanel:"role"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RemoveRoles calls the UAPI function `Team::remove_roles` — Remove roles from a team user
//
// This function removes roles from a team user.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-remove_roles.md
func (c *TeamClient) RemoveRoles(ctx context.Context, args *TeamRemoveRolesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "remove_roles", args)
}

// TeamRemoveTeamUserArgs are the parameters of the UAPI function `Team::remove_team_user`.
type TeamRemoveTeamUserArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RemoveTeamUser calls the UAPI function `Team::remove_team_user` — Remove a team user
//
// This function removes a team user.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-remove_team_user.md
func (c *TeamClient) RemoveTeamUser(ctx context.Context, args *TeamRemoveTeamUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "remove_team_user", args)
}

// TeamSetContactEmailArgs are the parameters of the UAPI function `Team::set_contact_email`.
type TeamSetContactEmailArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The primary contact email address to set for the team user.
	Email1 *string `cpanel:"email1,omitempty"`

	// The secondary contact email address to set for the team user.
	Email2 *string `cpanel:"email2,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetContactEmail calls the UAPI function `Team::set_contact_email` — Set a contact email address for a team user
//
// This function sets or changes primary and secondary email addresses.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_contact_email.md
func (c *TeamClient) SetContactEmail(ctx context.Context, args *TeamSetContactEmailArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "set_contact_email", args)
}

// TeamSetExpireArgs are the parameters of the UAPI function `Team::set_expire`.
type TeamSetExpireArgs struct {
	// The epoch time on which the team user account expires, or the offset from the current time, in days. Integers are treated as Unix Epoch Time unless followed by 'days'.
	//
	// This parameter is required.
	Date any `cpanel:"date"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The reason for expiration.
	Reason *string `cpanel:"reason,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetExpire calls the UAPI function `Team::set_expire` — Set a team user to expire
//
// This function expires a team user after a specified amount of time.
//
// If the team user already has an expire date set, it's replaced with a new date and reason.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_expire.md
func (c *TeamClient) SetExpire(ctx context.Context, args *TeamSetExpireArgs) (*cpanel.UAPIResult[int64], error) {
	return cpanel.UAPICall[int64](ctx, c.c, http.MethodGet, "Team", "set_expire", args)
}

// TeamSetLocaleArgs are the parameters of the UAPI function `Team::set_locale`.
type TeamSetLocaleArgs struct {
	// The new locale for the team user.
	//
	// This parameter is required.
	Locale string `cpanel:"locale"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetLocale calls the UAPI function `Team::set_locale` — Set locale for a team user
//
// This function sets locale for a team user.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_locale.md
func (c *TeamClient) SetLocale(ctx context.Context, args *TeamSetLocaleArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "set_locale", args)
}

// TeamSetNotesArgs are the parameters of the UAPI function `Team::set_notes`.
type TeamSetNotesArgs struct {
	// The content of the notes field.
	//
	// This parameter is required.
	Notes string `cpanel:"notes"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetNotes calls the UAPI function `Team::set_notes` — Set notes for a team user
//
// This function replaces the current notes field with new text.
//
// Available since cPanel & WHM version 110.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_notes.md
func (c *TeamClient) SetNotes(ctx context.Context, args *TeamSetNotesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "set_notes", args)
}

// TeamSetPasswordArgs are the parameters of the UAPI function `Team::set_password`.
type TeamSetPasswordArgs struct {
	// The password to set for the team user.
	//
	// This parameter is required.
	Password string `cpanel:"password"`

	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetPassword calls the UAPI function `Team::set_password` — Set password for a team user
//
// This function replaces the current password with a new one.
//
// Available since cPanel & WHM version 106.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_password.md
func (c *TeamClient) SetPassword(ctx context.Context, args *TeamSetPasswordArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "set_password", args)
}

// TeamSetRolesArgs are the parameters of the UAPI function `Team::set_roles`.
type TeamSetRolesArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The role or roles to set for the team user. Current roles include admin, database, email, web.
	//
	// **Note:**
	//
	//  * This function replaces the team user's current roles. If you omit this parameter, the team user loses every role and **cannot** use any features.
	Role *string `cpanel:"role,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetRoles calls the UAPI function `Team::set_roles` — Set roles for a team user
//
// This function sets roles for a team user.
//
// **Note:**
//
//	This action may result in team users gaining access to team owner level privileges.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-set_roles.md
func (c *TeamClient) SetRoles(ctx context.Context, args *TeamSetRolesArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "set_roles", args)
}

// TeamSuspendTeamUserArgs are the parameters of the UAPI function `Team::suspend_team_user`.
type TeamSuspendTeamUserArgs struct {
	// The username of the team user.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The reason for suspension.
	Reason *string `cpanel:"reason,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SuspendTeamUser calls the UAPI function `Team::suspend_team_user` — Suspend a team user
//
// This function immediately suspends a team user.
//
// Available since cPanel & WHM version 108.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/team-users/team-suspend_team_user.md
func (c *TeamClient) SuspendTeamUser(ctx context.Context, args *TeamSuspendTeamUserArgs) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "Team", "suspend_team_user", args)
}
