// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// ListDomains calls the UAPI function `WebVhosts::list_domains` — Return virtual host names for domains
//
// This function lists virtual host names for each domain.
//
// Available since cPanel & WHM version cPanel 56.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/virtual-host-information/webvhosts-list_domains.md
func (c *WebVhostsClient) ListDomains(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]WebVhostsListDomainsDataItem], error) {
	return cpanel.UAPICall[[]WebVhostsListDomainsDataItem](ctx, c.c, http.MethodGet, "WebVhosts", "list_domains", cpanel.CombineArgs(extra...))
}

// WebVhostsListDomainsDataItem is a generated payload type.
type WebVhostsListDomainsDataItem struct {
	// The domain name.
	Domain string `json:"domain"`

	// An array of service subdomains (proxy subdomains) listed for the domain.
	//
	// **Note:**
	//
	// This only returns values when `vhost_is_ssl` equals `1`.
	ProxySubdomains []string `json:"proxy_subdomains"`

	// Whether an SSL certificate secures the domain.
	// * `1` - Secured.
	// * `0` - **Not** secured.
	//
	// Possible values: `0`, `1`.
	VhostIsSSL int64 `json:"vhost_is_ssl"`

	// The name of the virtual host.
	VhostName string `json:"vhost_name"`
}

// WebVhostsListSSLCapableDomainsArgs are the parameters of the UAPI function `WebVhosts::list_ssl_capable_domains`.
type WebVhostsListSSLCapableDomainsArgs struct {
	// Whether to hide temporary domains from the returned values.
	// * `1` — Return an error if the requested domain is a temporary domain.
	// * `0` — Return all domains, including the temporary domains.
	// **Note:**
	//
	// If you set this parameter's value to `1` and the requested domain is temporary,
	// the function will return an error similar to the following example: `Domain [example.com] is a temporary
	// domain and `hide_temporary_domains` is enabled.`
	//
	// Possible values: `1`, `0`.
	//
	// Defaults to `0`.
	HideTemporaryDomains *int64 `cpanel:"hide_temporary_domains,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListSSLCapableDomains calls the UAPI function `WebVhosts::list_ssl_capable_domains` — Return domains that allow SSL certificate purchase
//
// This function lists every domain for which you may purchase an SSL certificate. The possible domains for the Secure Sockets Layer (SSL) certificate include applicable [service subdomains.](https://go.cpanel.net/ServiceProxySubdomains)
//
// Available since cPanel & WHM version cPanel 64.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/virtual-host-information/webvhosts-list_ssl_capable_domains.md
func (c *WebVhostsClient) ListSSLCapableDomains(ctx context.Context, args *WebVhostsListSSLCapableDomainsArgs) (*cpanel.UAPIResult[[]WebVhostsListSSLCapableDomainsDataItem], error) {
	return cpanel.UAPICall[[]WebVhostsListSSLCapableDomainsDataItem](ctx, c.c, http.MethodGet, "WebVhosts", "list_ssl_capable_domains", args)
}

// WebVhostsListSSLCapableDomainsDataItem is a generated payload type.
type WebVhostsListSSLCapableDomainsDataItem struct {
	// A valid domain name on the virtual host.
	Domain string `json:"domain"`

	// Whether the system automatically created the service subdomain or a user manually created the domain.
	// * `1` - The system automatically created the service subdomain.
	// * `0` - A user manually created the domain.
	//
	// **Note:**
	//
	// If a user manually creates a subdomain that matches a preassigned subdomain (for example, cpanel or whm), then the function returns `0`.
	//
	// Possible values: `0`, `1`.
	IsProxy int64 `json:"is_proxy"`

	// The name of the virtual host or website.
	VhostName string `json:"vhost_name"`
}
