// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// Create calls the UAPI function `WordPressSite::create` — Install WordPress site
//
// This function installs a WordPress site for cPanel user's primary domain.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/site-installation/wordpresssite-create.md
func (c *WordPressSiteClient) Create(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[json.RawMessage], error) {
	return cpanel.UAPICall[json.RawMessage](ctx, c.c, http.MethodGet, "WordPressSite", "create", cpanel.CombineArgs(extra...))
}


// Retrieve calls the UAPI function `WordPressSite::retrieve` — Return WordPress site information
//
// This function retrieves the installation status and detailed information of the WordPress site for cPanel user's primary domain.
//
// Available since cPanel & WHM version cPanel 11.42.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/site-information/wordpresssite-retrieve.md
func (c *WordPressSiteClient) Retrieve(ctx context.Context, extra ...cpanel.Args) (*cpanel.UAPIResult[[]WordPressSiteRetrieveDataItem], error) {
	return cpanel.UAPICall[[]WordPressSiteRetrieveDataItem](ctx, c.c, http.MethodGet, "WordPressSite", "retrieve", cpanel.CombineArgs(extra...))
}


// WordPressSiteRetrieveDataItem is a generated payload type.
type WordPressSiteRetrieveDataItem struct {
	// Detailed information of the WordPress site.
	Details       json.RawMessage `json:"details"`

	// Installation status of the WordPress site.
	InstallStatus string `json:"install_status"`
}
