// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package uapi

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// ZoneEditResetZoneArgs are the parameters of the UAPI function `ZoneEdit::resetzone`.
type ZoneEditResetZoneArgs struct {
	// The domain whose DNS zone to reset.
	//
	// This parameter is required.
	Domain string `cpanel:"domain"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ResetZone calls the UAPI function `ZoneEdit::resetzone` — Reset a DNS zone to the server defaults
//
// This function resets a domain's [DNS](https://go.cpanel.net/dnsrecords)
// zone to the server's default zone template.
//
// **Important:**
//
//   - This action **destroys** every custom record in the zone. Records that
//     the zone template does not recreate, for example `MX`, `TXT` and
//     `CNAME` records added by hand, are lost.
//   - The reset outcome is reported in the `data` field rather than in the
//     `status` field. A call can succeed at the API level while the zone
//     rebuild itself fails, so check the `result.status` field in the
//     returned data.
//
// When you disable the [DNS role](https://go.cpanel.net/serverroles#roles),
// the system **disables** this function.
//
// Available since cPanel & WHM version cPanel 138.
//
// Documentation: https://api.docs.cpanel.net/specifications/cpanel.openapi/zoneedit/zoneedit-resetzone.md
func (c *ZoneEditClient) ResetZone(ctx context.Context, args *ZoneEditResetZoneArgs) (*cpanel.UAPIResult[[]ZoneEditResetZoneDataItem], error) {
	return cpanel.UAPICall[[]ZoneEditResetZoneDataItem](ctx, c.c, http.MethodGet, "ZoneEdit", "resetzone", args)
}

// The reply from the zone rebuild.
type ZoneEditResetZoneDataItemResult struct {
	// The outcome of the mail exchanger check that the system runs after it rebuilds the zone. The system omits this field when the rebuild fails.
	Checkmx json.RawMessage `json:"checkmx"`

	// Whether the system rebuilt the zone.
	// * `1` - The system rebuilt the zone.
	// * `0` - The rebuild failed. Check the `statusmsg` field for more details.
	//
	// Possible values: `0`, `1`.
	Status int64 `json:"status"`

	// A message that describes the rebuild's outcome.
	StatusMsg string `json:"statusmsg"`
}

// ZoneEditResetZoneDataItem is a generated payload type.
type ZoneEditResetZoneDataItem struct {
	// The reply from the zone rebuild.
	Result ZoneEditResetZoneDataItemResult `json:"result"`
}
