// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// AccountSummaryArgs are the parameters of the WHM API 1 function `accountsummary`.
type AccountSummaryArgs struct {
	// The account's main domain.
	Domain *string `cpanel:"domain,omitempty"`

	// The search term.
	Search *string `cpanel:"search,omitempty"`

	// The search method to use.
	SearchMethod *string `cpanel:"searchmethod,omitempty"`

	// The type of search to perform.
	SearchType *string `cpanel:"searchtype,omitempty"`

	// The account's username.
	User *string `cpanel:"user,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AccountSummary calls the WHM API 1 function `accountsummary` — Return cPanel account summary
//
// This function retrieves a summary of a user's account.
//
// **Note:**
//
// You must use either the user or domain parameters.
//
// Available since cPanel & WHM version 11.32.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-accountsummary.md
func (c *Client) AccountSummary(ctx context.Context, args *AccountSummaryArgs) (*cpanel.WHMResult[AccountSummaryData], error) {
	return cpanel.WHMCall[AccountSummaryData](ctx, c.c, http.MethodGet, "accountsummary", args)
}


// AccountSummaryDataAcctItemChildNodesItem is a generated payload type.
type AccountSummaryDataAcctItemChildNodesItem struct {
	// The alias of the child node
	Alias    string `json:"alias"`

	// The workload delegated to the child node
	//
	// Possible values: `Mail`.
	Workload string `json:"workload"`
}

// AccountSummaryDataAcctItem is a generated payload type.
type AccountSummaryDataAcctItem struct {
	// Whether backups are enabled.
	// * `1` Enabled.
	// * `0` Disabled.
	//
	// Possible values: `0`, `1`.
	Backup                          int64 `json:"backup"`

	// An array that contains the the workload and alias values for each of the child nodes.
	ChildNodes                      []AccountSummaryDataAcctItemChildNodesItem `json:"child_nodes"`

	// The account's disk space quota.
	// * `unlimited`
	// * A maximum amount of disk space, in mebibyte (MiB).
	DiskLimit                       any `json:"disklimit"`

	// The account's current disk space usage. An integer that represents an amount of disk space, in mebibyte (MiB). For example, 14M represents 14 MiB of disk space.
	Diskused                        string `json:"diskused"`

	// The account's main domain. A valid domain name on the account.
	Domain                          string `json:"domain"`

	// The account's contact email address. A valid email address.
	Email                           string `json:"email"`

	// The limit on the number of files that the account owns.
	// * `unlimited`
	// * A maximum amount of files as an integer.
	InodesLimit                     any `json:"inodeslimit"`

	// The number of files that the account owns.
	InodesUsed                      int64 `json:"inodesused"`

	// The account's main domain's IP address.
	IP                              string `json:"ip"`

	// The account's main domain's IPv6 addresses.
	IPv6                            []string `json:"ipv6"`

	// Whether the account is currently locked.
	// * `1` Locked.
	// * `0` Not locked.
	//
	// Possible values: `0`, `1`.
	IsLocked                        int64 `json:"is_locked"`

	// Whether the main domain is a temporary domain.
	// * `1` - The account's main domain is a temporary domain.
	// * `0` - The account's main domain is not a temporary domain.
	//
	// **Note:**
	//
	// For more information about temporary domains, read our [Temporary Domains](https://go.cpanel.net/cp-temporary-domain) documentation.
	//
	// Possible values: `0`, `1`.
	IsTemporaryDomain               int64 `json:"is_temporary_domain"`

	// Whether legacy backups are enabled.
	// * `1` Enabled.
	// * `0` Disabled.
	//
	// Possible values: `0`, `1`.
	LegacyBackup                    int64 `json:"legacy_backup"`

	// The storage format that the account's email mailboxes use.
	// * `maildir` The account's mail is stored in `maildir` format.
	// * `mbox` The account's mail is stored in `mbox` format.
	//
	// Possible values: `maildir`, `mbox`.
	MailboxFormat                   string `json:"mailbox_format"`

	// The percentage of failed or deferred email messages that the account
	// can send per hour before outgoing mail is rate-limited.
	// * `unlimited`
	// * An integer that represents a percentage of messages.
	MaxDeferFailPercentage          any `json:"max_defer_fail_percentage"`

	// The maximum number of emails that the account can send in one hour.
	// * `unlimited`
	// * An integer that represents a number of sent emails.
	MaxEmailPerHour                 any `json:"max_email_per_hour"`

	// The maximum size that the cPanel account can define when it creates an email account.
	// * `unlimited`
	// * A positive integer that represents the allowable maximum size of an email account, in mebibyte (MiB).
	MaxEmailacctQuota               any `json:"max_emailacct_quota"`

	// The account's maximum number of addon domains.
	// * `unlimited`
	// * `*unknown*`  The account cannot use any addon domains.
	// * An integer that represents a number of addon domains.
	MaxAddons                       any `json:"maxaddons"`

	// The account's maximum number of FTP accounts.
	// * `unlimited`
	// * An integer that represents a number of FTP accounts.
	Maxftp                          any `json:"maxftp"`

	// The account's maximum number of mailing lists.
	// * `unlimited`
	// * An integer that represents a number of mailing lists.
	Maxlst                          any `json:"maxlst"`

	// The account's maximum number of parked domains (aliases).
	// * `unlimited`
	// * `*unknown*` The account cannot use any parked domains.
	// * An integer that represents a number of parked domains.
	MaxParked                       any `json:"maxparked"`

	// The account's maximum number of email addresses.
	// * `unlimited`
	// * An integer that represents a number of email accounts.
	Maxpop                          any `json:"maxpop"`

	// The account's maximum number of SQL databases.
	// * `unlimited`
	// * An integer that represents a number of SQL databases.
	Maxsql                          any `json:"maxsql"`

	// The account's maximum number of subdomains.
	// * `unlimited`
	// * `*unknown*` The account cannot use any subdomains.
	// * An integer that represents a number of subdomains.
	Maxsub                          any `json:"maxsub"`

	// The minimum number of failed or deferred messages that the account can send before
	// outgoing mail is subject to rate-limiting.
	// * `unlimited`
	// * An integer that represents a number of failed or deferred messages.
	MinDeferFailToTriggerProtection any `json:"min_defer_fail_to_trigger_protection"`

	// Whether to retain outgoing mail in the mail queue for the account's users.
	// * `1` Suspend and force failure of outgoing email.
	// * `0` Unsuspend outgoing email.
	//
	// Possible values: `0`, `1`.
	OutgoingMailHold                int64 `json:"outgoing_mail_hold"`

	// Whether to suspend outgoing email from the account's users and force failure of any of their mail currently in the mail queue.
	// * `1` - Suspend and force failure of outgoing email.
	// * `0` - Unsuspend outgoing email.
	//
	// **Note:**
	//
	// If mail for a cPanel user's account is suspended, the system will reject their email before the system puts it in the mail server queue.
	//
	// Possible values: `0`, `1`.
	OutgoingMailSuspended           int64 `json:"outgoing_mail_suspended"`

	// The account's owner.
	// * root
	// * A reseller account's username.
	Owner                           string `json:"owner"`

	// The partition that contains the account's home directory. The name of a partition on the server.
	Partition                       string `json:"partition"`

	// The account's hosting package. The name of a package on the server.
	Plan                            string `json:"plan"`

	// The account's shell. A shell location on the server.
	Shell                           string `json:"shell"`

	// The account creation date. The date in YY-Mon-DD HH-mm human-readable format, where:- YY represents the year.
	// * `Mon` represents the month.
	// * `DD` represents the date.
	// * `HH` represents the hour.
	// * `mm` represents the minute.
	Startdate                       string `json:"startdate"`

	// Whether the account is currently suspended.
	// * `1`  Suspended.
	// * `0`  Not suspended.
	//
	// Possible values: `0`, `1`.
	Suspended                       int64 `json:"suspended"`

	// The reason for account suspension, if one was provided.
	// * `null` The account is not currently suspended.
	// * A blank value, if the suspender did not provide a reason.
	// * A message that explains the suspension.
	SuspendReason                   *string `json:"suspendreason"`

	// The time of suspension.
	// * `null` The account is not currently suspended.
	// * The time at which the account became suspended.
	SuspendTime                     *string `json:"suspendtime"`

	// Whether the Customer Support Ticket process created this user for temporary access to the system.
	// * `1` - Temporary user.
	// * `0` - Regular user.
	//
	// Possible values: `0`, `1`.
	Temporary                       int64 `json:"temporary"`

	// The account's cPanel interface theme.
	// * Any valid theme on the server.
	Theme                           string `json:"theme"`

	// The account's user ID on the system.
	Uid                             int64 `json:"uid"`

	// The account creation date. The account creation date and time, in Unix time format.
	UnixStartdate                   int64 `json:"unix_startdate"`

	// The account username. A cPanel account or reseller username on the server.
	User                            string `json:"user"`
}

// AccountSummaryData is a generated payload type.
type AccountSummaryData struct {
	// An array of objects of account data.
	Acct []AccountSummaryDataAcctItem `json:"acct"`
}

// GetUpgradeOpportunitiesArgs are the parameters of the WHM API 1 function `get_upgrade_opportunities`.
type GetUpgradeOpportunitiesArgs struct {
	// A fixed number of blocks to use as an alternative disk usage threshold.
	//
	// Defaults to `2097152`.
	DiskThresholdBlocks *int64 `cpanel:"disk_threshold_blocks,omitempty"`

	// The fraction of 1 at which to consider usage "near".
	//
	// Defaults to `0.8`.
	NearnessFraction *float64 `cpanel:"nearness_fraction,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetUpgradeOpportunities calls the WHM API 1 function `get_upgrade_opportunities` — Get upgrade opportunities
//
// This function lists accounts that could benefit from upgrading to a different package.
// The listed accounts may be nearing (or exceeding) resource usage thresholds.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-get_upgrade_opportunities.md
func (c *Client) GetUpgradeOpportunities(ctx context.Context, args *GetUpgradeOpportunitiesArgs) (*cpanel.WHMResult[GetUpgradeOpportunitiesData], error) {
	return cpanel.WHMCall[GetUpgradeOpportunitiesData](ctx, c.c, http.MethodGet, "get_upgrade_opportunities", args)
}


// GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitLastMonth is a generated payload type.
type GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitLastMonth struct {
	// A fractional number ranging from 0.00 to 1.00 indicating the fraction of the resource limit that was consumed.
	Fraction float64 `json:"fraction"`

	// Whether the account is near this resource limit. Nearness is defined according to `nearness_fraction`.
	//
	// * `1` — Near.
	// * `0` — Not near.
	//
	// Possible values: `0`, `1`.
	Near     int64 `json:"near"`

	// Whether the account has reached this resource limit.
	//
	// * `1` — Reached.
	// * `0` — Not reached.
	//
	// Possible values: `0`, `1`.
	Reached  int64 `json:"reached"`
}

// GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitThisMonth is a generated payload type.
type GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitThisMonth struct {
	// A fractional number ranging from 0.00 to 1.00 indicating the fraction of the resource limit that was consumed.
	Fraction float64 `json:"fraction"`

	// Whether the account is near this resource limit. Nearness is defined according to `nearness_fraction`.
	//
	// * `1` — Near.
	// * `0` — Not near.
	//
	// Possible values: `0`, `1`.
	Near     int64 `json:"near"`

	// Whether the account has reached this resource limit.
	//
	// * `1` — Reached.
	// * `0` — Not reached.
	//
	// Possible values: `0`, `1`.
	Reached  int64 `json:"reached"`
}

// Upgrade opportunities related to bandwidth limits.
type GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimit struct {
	LastMonth GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitLastMonth `json:"last_month"`

	// An array of human-readable messages representing the facts listed in the other structured data in the `bw_limit` object.
	Messages  []string `json:"messages"`

	ThisMonth GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimitThisMonth `json:"this_month"`
}

// Upgrade opportunities related to disk usage.
type GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueDiskUsage struct {
	// An array of human-readable messages representing the facts listed in the other structured data in the `disk_usage` object.
	Messages              []string `json:"messages"`

	RelativeToFixedAmount json.RawMessage `json:"relative_to_fixed_amount"`

	RelativeToQuota       json.RawMessage `json:"relative_to_quota"`
}

// The property name is the cPanel account.
type GetUpgradeOpportunitiesDataUpgradeOpportunitiesValue struct {
	// Upgrade opportunities related to bandwidth limits.
	BwLimit   GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueBwLimit `json:"bw_limit"`

	// Upgrade opportunities related to disk usage.
	DiskUsage GetUpgradeOpportunitiesDataUpgradeOpportunitiesValueDiskUsage `json:"disk_usage"`

	// An array of human-readable messages representing the facts listed in the other structured data.
	Messages  []string `json:"messages"`
}

// GetUpgradeOpportunitiesData is a generated payload type.
type GetUpgradeOpportunitiesData struct {
	// The collection of accounts and information about their upgrade opportunities.
	UpgradeOpportunities map[string]GetUpgradeOpportunitiesDataUpgradeOpportunitiesValue `json:"upgrade_opportunities"`
}

// HasDigestAuthArgs are the parameters of the WHM API 1 function `has_digest_auth`.
type HasDigestAuthArgs struct {
	// The cPanel account username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// HasDigestAuth calls the WHM API 1 function `has_digest_auth` — Validate cPanel account Digest Authentication
//
// This function checks whether Digest Authentication is enabled for
// a cPanel user. Windows® Vista, Windows® 7, and Windows® 8 require Digest Authentication
// support in order to access [Web Disk](https://docs.cpanel.net/cpanel/files/web-disk/) over an unencrypted connection.
//
// Available since cPanel & WHM version 11.34.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/sys-has_digest_auth.md
func (c *Client) HasDigestAuth(ctx context.Context, args *HasDigestAuthArgs) (*cpanel.WHMResult[HasDigestAuthData], error) {
	return cpanel.WHMCall[HasDigestAuthData](ctx, c.c, http.MethodGet, "has_digest_auth", args)
}


// HasDigestAuthData is a generated payload type.
type HasDigestAuthData struct {
	// Whether Digest Authentication support is enabled.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	DigestAuth int64 `json:"digestauth"`
}

// HasMycnfForCpuserArgs are the parameters of the WHM API 1 function `has_mycnf_for_cpuser`.
type HasMycnfForCpuserArgs struct {
	// The cPanel account username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// HasMycnfForCpuser calls the WHM API 1 function `has_mycnf_for_cpuser` — Validate MySQL Configuration file
//
// This function checks whether a cPanel user's home directory contains
// a valid .my.cnf file.
//
// Available since cPanel & WHM version 11.40.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/sys-has_mycnf_for_cpuser.md
func (c *Client) HasMycnfForCpuser(ctx context.Context, args *HasMycnfForCpuserArgs) (*cpanel.WHMResult[HasMycnfForCpuserData], error) {
	return cpanel.WHMCall[HasMycnfForCpuserData](ctx, c.c, http.MethodGet, "has_mycnf_for_cpuser", args)
}


// HasMycnfForCpuserData is a generated payload type.
type HasMycnfForCpuserData struct {
	// Whether a valid .my.cnf file exists in the account's home directory.
	// - `1` -  Exists.
	// - `0` -  Does not exist.
	//
	// Possible values: `0`, `1`.
	HasMycnfForCpuser int64 `json:"has_mycnf_for_cpuser"`
}

// ListAcctsArgs are the parameters of the WHM API 1 function `listaccts`.
type ListAcctsArgs struct {
	// A [Perl Compatible Regular Expression (PCRE)](https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions) that filters the results.
	//
	// **Note:**
	//  * The system matches the PCRE against the `searchtype` parameter's specified type.
	//  * If you do not specify a value for both the `searchtype` and `search` parameters,
	//    the function returns all of the server's accounts.
	Search *string `cpanel:"search,omitempty"`

	// The function's search method.
	// * `exact` - The matched value and the `search` value **must** be identical.
	// * `regex` - The matched value must contain the `search` value.
	//
	// Possible values: `exact`, `regex`.
	SearchMethod *string `cpanel:"searchmethod,omitempty"`

	// The account information to query. If you do not specify a value
	// for both the `searchtype` and `search` parameters, the function returns all
	// of the server's accounts.
	// * `domain` - Match domains against the `search` regular expression.
	// * `owner` - Match the WHM user who owns the account against the `search` regular expression.
	// * `user` - Match usernames against the `search` regular expression.
	// * `ip` - Match IP addresses against the `search` regular expression.
	// * `package` - Match hosting plans (p …
	SearchType *string `cpanel:"searchtype,omitempty"`

	// The returns to include in the output for each account.
	//
	// If you do not specify a value, the function's output includes all of its returns.
	Want *string `cpanel:"want,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListAccts calls the WHM API 1 function `listaccts` — Return cPanel accounts
//
// This function lists the accounts on the server.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-listaccts.md
func (c *Client) ListAccts(ctx context.Context, args *ListAcctsArgs) (*cpanel.WHMResult[ListAcctsData], error) {
	return cpanel.WHMCall[ListAcctsData](ctx, c.c, http.MethodGet, "listaccts", args)
}


// ListAcctsDataAcctItemChildNodesItem is a generated payload type.
type ListAcctsDataAcctItemChildNodesItem struct {
	// The alias of the child node
	Alias    string `json:"alias"`

	// The workload delegated to the child node
	//
	// Possible values: `Mail`.
	Workload string `json:"workload"`
}

// ListAcctsDataAcctItem is a generated payload type.
type ListAcctsDataAcctItem struct {
	// Whether backups are enabled.
	// * `1` - Enabled.
	// * `0` - Disabled.
	//
	// Possible values: `0`, `1`.
	Backup                          int64 `json:"backup"`

	// An array that contains the the workload and alias values for each of the child nodes.
	ChildNodes                      []ListAcctsDataAcctItemChildNodesItem `json:"child_nodes"`

	// The account's disk space quota.
	// * `unlimited` — The account has unlimited disk space quota.
	// * A maximum amount of disk space, in megabytes (MB).
	DiskLimit                       any `json:"disklimit"`

	// The account's current disk space usage, in megabytes (MB), appended with `M`.
	//
	// For example, `14M` represents 14 megabytes of current disk space usage.
	Diskused                        string `json:"diskused"`

	// The account's main domain.
	Domain                          string `json:"domain"`

	// The account's contact email address.
	Email                           string `json:"email"`

	// Whether a backup of the account exists.
	// * `1` - A backup of the account exists.
	// * `0` - A backup of the account does **not** exist.
	//
	// Possible values: `0`, `1`.
	HasBackup                       int64 `json:"has_backup"`

	// The limit on the number of files that the account owns.
	// * `unlimited` — The account can own an unlimited number files.
	// * A positive integer.
	InodesLimit                     any `json:"inodeslimit"`

	// The number of files that the account owns.
	InodesUsed                      int64 `json:"inodesused"`

	// The IPv4 address of the account's main domain.
	IP                              string `json:"ip"`

	// The IPv6 address of the account's main domain.
	IPv6                            []string `json:"ipv6"`

	// Whether the account is currently locked.
	// * `1` - The account is locked.
	// * `0` - The account is **not** locked.
	//
	// Possible values: `0`, `1`.
	IsLocked                        int64 `json:"is_locked"`

	// Whether the main domain is a temporary domain.
	// * `1` - The account's main domain is a temporary domain.
	// * `0` - The account's main domain is not a temporary domain.
	//
	// **Note:**
	//
	// For more information about temporary domains, read our [Temporary Domains](https://go.cpanel.net/cp-temporary-domain) documentation.
	//
	// Possible values: `0`, `1`.
	IsTemporaryDomain               int64 `json:"is_temporary_domain"`

	// Whether legacy backups are enabled.
	// * `1` - Enabled.
	// * `0` - Disabled.
	//
	// Possible values: `0`, `1`.
	LegacyBackup                    int64 `json:"legacy_backup"`

	// The type of mailbox the account uses.
	//
	// * `mdbox`
	// * `maildir`
	//
	// Possible values: `mdbox`, `maildir`.
	MailboxFormat                   string `json:"mailbox_format"`

	// The [percentage of failed or deferred email
	// messages](https://go.cpanel.net/howtopreventspam)
	// that the account can send per hour before outgoing
	// mail is rate-limited.
	// * `unlimited` — The account can send unlimited emails per hour.
	// * An integer that represents a precentage of messages.
	MaxDeferFailPercentage          any `json:"max_defer_fail_percentage"`

	// The [maximum number of emails](https://go.cpanel.net/howtopreventspam)
	// that the account can send in one hour.
	// * `unlimited` — The account can send unlimited emails per hour.
	// * An integer that represents a number of sent emails.
	MaxEmailPerHour                 any `json:"max_email_per_hour"`

	// The maximum size, in megabytes (MB), that the account
	// can define when it creates an email account.
	//
	// * `unlimited` — The account can set unlimited quotas.
	// * A positive integer that represents the allowable maximum
	// size of an email account, in megabytes (MB).
	MaxEmailacctQuota               any `json:"max_emailacct_quota"`

	// The account's maximum number of addon domains.
	// * `unlimited` — The account can create unlimited addon domains.
	// * `*unknown*` — The account cannot create addon domains.
	// * An integer that represents a number of addon domains.
	MaxAddons                       any `json:"maxaddons"`

	// The account's maximum number of FTP accounts.
	// * `unlimited` — The account can create unlimited FTP accounts.
	// * An integer that represents a number of FTP accounts.
	Maxftp                          any `json:"maxftp"`

	// The account's maximum number of mailing lists.
	// * `unlimited` — The account can create unlimited mailing lists.
	// * An integer that represents a number of mailing lists.
	Maxlst                          any `json:"maxlst"`

	// The account's maximum number of parked domains (aliases).
	// * `unlimited` — The account can create unlimited parked domains.
	// * `*unknown*` — The account cannot use parked domains.
	// * An integer that represents a number of parked domains.
	MaxParked                       any `json:"maxparked"`

	// The account's maximum number of email addresses.
	// * `unlimited` — The account can create unlimited email addresses.
	// * An integer that represents a number of email accounts.
	Maxpop                          any `json:"maxpop"`

	// The account's maximum number of each available type of SQL database.
	//
	// For example, if you set this value to `5` and the system administrator allows MySQL® and PostgreSQL®
	// databases, users can create up to five MySQL databases and up to five PostgreSQL databases.
	//
	// * `unlimited` — The account can create unlimited SQL databases.
	// * An integer that represents a number of SQL databases.
	Maxsql                          any `json:"maxsql"`

	// The account's maximum number of subdomains.
	// * `unlimited` — The account can create unlimited subdomains.
	// * `*unknown*` - The account cannot use subdomains.
	// * An integer that represents a number of subdomains.
	Maxsub                          any `json:"maxsub"`

	// The [minimum number of failed or deferred messages](https://go.cpanel.net/howtopreventspam) that the
	// account can send before outgoing mail is subject to rate-limiting.
	// * `unlimited` — The account can send unlimited emails.
	// * An integer that represents a number of failed or deferred messages.
	MinDeferFailToTriggerProtection any `json:"min_defer_fail_to_trigger_protection"`

	// Whether to retain outgoing mail in the mail queue for the account's users.
	// * `1` - Hold outgoing email in the mail queue.
	// * `0` - Do **not** hold outgoingemail in the mail queue.
	//
	// Possible values: `1`, `0`.
	OutgoingMailHold                int64 `json:"outgoing_mail_hold"`

	// Whether to suspend outgoing email from the account's users and force failure of any of their mail currently in the mail queue.
	// * `1` - Suspend and forcefailure of outgoing email.
	// * `0` - Do **not** suspend and forcefailure of outgoing email.
	//
	// **Note:**
	//
	// If mail for a cPanel user's account is suspended, the system will reject their email before the system puts it in the mail server queue. …
	OutgoingMailSuspended           int64 `json:"outgoing_mail_suspended"`

	// The reseller account username or `root` user that owns the account.
	Owner                           string `json:"owner"`

	// The partition that contains the account's home directory.
	Partition                       string `json:"partition"`

	// The account's hosting package.
	Plan                            string `json:"plan"`

	// The absolute path of the account's shell location.
	Shell                           string `json:"shell"`

	// The unique ID of the standalone feature associated with the account's package, if any.
	// * An empty string if the package has no standalone features.
	StandaloneFeature               string `json:"standalone_feature"`

	// The name of the standalone feature associated with the account's package, if any.
	// * An empty string if the package has no standalone features.
	// * The feature's name if a standalone feature exists.
	StandaloneFeatureName           string `json:"standalone_feature_name"`

	// The account creation date, in `YY Mon DD HH:mm` format.
	Startdate                       string `json:"startdate"`

	// Whether the account is currently suspended.
	// * `1` - Suspended.
	// * `0` - **Not** suspended.
	//
	// Possible values: `0`, `1`.
	Suspended                       int64 `json:"suspended"`

	// The reason for account suspension, if one was provided.
	SuspendReason                   string `json:"suspendreason"`

	// The time of suspension.
	// * `null` - The account is not currently suspended.
	// * The time at which the account became suspended.
	SuspendTime                     *int64 `json:"suspendtime"`

	// Whether the Customer Support Ticket process created this user for temporary access to the system.
	// * `1` - Temporary user.
	// * `0` - Regular user.
	//
	// Possible values: `0`, `1`.
	Temporary                       int64 `json:"temporary"`

	// The account's cPanel interface theme.
	Theme                           string `json:"theme"`

	// The account's user ID on the system.
	Uid                             int64 `json:"uid"`

	// The account creation date.
	UnixStartdate                   int64 `json:"unix_startdate"`

	// The account username.
	User                            string `json:"user"`
}

// ListAcctsData is a generated payload type.
type ListAcctsData struct {
	// An array of objects containing account data.
	Acct []ListAcctsDataAcctItem `json:"acct"`
}

// MassModifyAcctArgs are the parameters of the WHM API 1 function `massmodifyacct`.
type MassModifyAcctArgs struct {
	// The account's current username.
	//
	// **Note:**
	//
	// To modify multiple users, duplicate or increment the parameter name. For example,
	// the `user-1`, `user-2`, and `user-3` parameters.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether backups are enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// This parameter **requires** `root` privileges.
	//
	// Possible values: `1`, `0`.
	Backup *string `cpanel:"BACKUP,omitempty"`

	// The account's maximum bandwidth use, in bytes.
	//
	// * `0`, `null` or `unlimited` — The account can use unlimited bandwidth.
	//
	// This parameter defaults to the defined system value.
	Bwlimit any `cpanel:"BWLIMIT,omitempty"`

	// The account's contact email address.
	//
	// This parameter defaults to the defined system value.
	ContactEmail *string `cpanel:"CONTACTEMAIL,omitempty"`

	// The owner of the account's MySQL® databases.
	//
	// This parameter defaults to the defined system value.
	Dbowner *string `cpanel:"DBOWNER,omitempty"`

	// The number of disk blocks for the account, in kilobytes (KB).
	//
	// This parameter defaults to the defined system value.
	DiskBlockLimit *int64 `cpanel:"DISK_BLOCK_LIMIT,omitempty"`

	// Whether CGI access is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// When a [server profile](https://go.cpanel.net/whmdocsServerProfile) disables the
	// [Web Server](https://go.cpanel.net/serverroles#roles) role, you **cannot** enable
	// CGI access.
	//
	// Possible values: `1`, `0`.
	Hascgi *int64 `cpanel:"HASCGI,omitempty"`

	// Whether DomainKeys Identified Mail (DKIM) is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	Hasdkim *int64 `cpanel:"HASDKIM,omitempty"`

	// Whether Domain-based Message Authentication, Reporting, and Conformance (DMARC) is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	Hasdmarc *int64 `cpanel:"HASDMARC,omitempty"`

	// Whether shell (SSH) access is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// We **strongly** recommend that you use the `shell` parameter to specify a shell for
	// SSH access.
	//
	// Possible values: `1`, `0`.
	Hasshell *int64 `cpanel:"HASSHELL,omitempty"`

	// Whether Sender Policy Framework (SPF) is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	Hasspf *int64 `cpanel:"HASSPF,omitempty"`

	// The account's display language.
	//
	// This parameter defaults to the defined system value.
	Lang *string `cpanel:"LANG,omitempty"`

	// The account's default locale.
	//
	// This parameter defaults to the defined system value.
	Locale *string `cpanel:"LOCALE,omitempty"`

	// The storage format that the account's mailboxes use.
	//
	// * `maildir`
	// * `mbox`
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `maildir`, `mbox`.
	MailboxFormat *string `cpanel:"MAILBOX_FORMAT,omitempty"`

	// The percentage of failed or deferred email messages that the account can send per hour
	// before outgoing mail is rate-limited.
	//
	// * `0` or `unlimited` — The account can send an unlimited number of failed or deferred
	// messages.
	//
	// This parameter defaults to the defined system value.
	MaxDeferFailPercentage any `cpanel:"MAX_DEFER_FAIL_PERCENTAGE,omitempty"`

	// The maximum number of emails that the account can send in one hour.
	//
	// * `0` or `unlimited` — The account can send an unlimited number of emails.
	//
	// This parameter defaults to the defined system value.
	MaxEmailPerHour any `cpanel:"MAX_EMAIL_PER_HOUR,omitempty"`

	// The maximum size, in megabytes (MB), that the account can define when it creates an
	// email account.
	//
	// * `unlimited` — The account possesses an unlimited quota.
	//
	// **Important:**
	//
	// * This value applies to each email account, **not** each cPanel account.
	// * If you specify a `MAX_EMAILACCT_QUOTA` value, the function will **overwrite** the
	// plan's defined value for that cPanel account.
	// * This parameter does **not** affect any existing email accounts
	// * We recommend that you allow the account's plan to deter …
	MaxEmailacctQuota any `cpanel:"MAX_EMAILACCT_QUOTA,omitempty"`

	// The account's maximum number of addon domains.
	//
	// * `0`, `null`, or `unlimited` — The account possesses unlimited addon domains.
	//
	// This parameter defaults to the defined system value.
	Maxaddon any `cpanel:"MAXADDON,omitempty"`

	// The account's maximum number of FTP accounts.
	//
	// * `null` or `unlimited` — The account possesses unlimited FTP accounts.
	//
	// This parameter defaults to the defined system value.
	Maxftp any `cpanel:"MAXFTP,omitempty"`

	// The account's maximum number of mailing lists.
	//
	// * `0`, `null`, or `unlimited` — The account possesses unlimited mailing lists.
	//
	// This parameter defaults to the defined system value.
	Maxlst any `cpanel:"MAXLST,omitempty"`

	// The account's maximum number of parked domains (aliases).
	//
	// * `null` or `unlimited` — The account possesses unlimited mailing lists.
	//
	// This parameter defaults to the defined system value.
	Maxpark any `cpanel:"MAXPARK,omitempty"`

	// The account's maximum number of Ruby applications.
	//
	// * `null` or `unlimited` — The account possesses unlimited Ruby applications.
	//
	// This parameter defaults to the defined system value.
	MaxPassengerApps any `cpanel:"MAXPASSENGERAPPS,omitempty"`

	// The maximum number of email accounts for the account.
	//
	// * `null` or `unlimited` — The account possesses unlimited email accounts.
	//
	// This parameter defaults to the defined system value.
	Maxpop any `cpanel:"MAXPOP,omitempty"`

	// The maximum number of each available type of SQL database for the account.
	//
	// For example, if you set this value to `5` and the system administrator allows MySQL®
	// and PostgreSQL® databases, users can create up to five MySQL databases and up to five
	// PostgreSQL databases.
	//
	// * `null` or `unlimited` — The account possesses unlimited databases.
	//
	// This parameter defaults to the defined system value.
	Maxsql any `cpanel:"MAXSQL,omitempty"`

	// The maximum number of subdomains for the account.
	//
	// * `null` or `unlimited` — The account possesses unlimited subdomains.
	//
	// This parameter defaults to the defined system value.
	Maxsub any `cpanel:"MAXSUB,omitempty"`

	// Whether to modify the firewall rules as part of the account modification.
	//
	// * `1` – Modify the firewall rules.
	// * `0` – Do **not** modify the firewall rules.
	//
	// **NOTE:**
	//
	// If you do not set this parameter, the system will modify the firewall based on the *Do not make changes to the firewall during account modification.* setting in WHM's [*Tweak Settings*](https://docs.cpanel.net/whm/server-configuration/tweak-settings/) interface (*WHM >> Home >> Server Configuration >> Tweak Settings*). …
	ModifyFirewall *int64 `cpanel:"modify_firewall,omitempty"`

	// The priority of the account's primary mail exchanger.
	//
	// **Note:**
	//
	// The parameter name consists of `MXCHECK`, a hyphen, and the primary domain of the
	// account.
	//
	// Example key and value:
	// * `MXCHECK-example.com=10`
	//
	// This parameter defaults to the define system value.
	Mxcheck *int64 `cpanel:"MXCHECK-*,omitempty"`

	// Whether to send a notification when someone links the account to an external
	// authentication account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAccountAuthnLink *int64 `cpanel:"notify_account_authn_link,omitempty"`

	// Whether to send a notification when someone disables notifications for external
	// authentication account links.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAccountAuthnLinkNotificationDisabled *int64 `cpanel:"notify_account_authn_link_notification_disabled,omitempty"`

	// Whether to send a notification when an AutoSSL certificate expires.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAutoSSLExpiry *int64 `cpanel:"notify_autossl_expiry,omitempty"`

	// Whether to send a notification AutoSSL cannot renew a certificate because domains
	// that fail Domain Control Validation (DCV) exist on the current certificate.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAutoSSLExpiryCoverage *int64 `cpanel:"notify_autossl_expiry_coverage,omitempty"`

	// Whether to send a notification when AutoSSL renews a certificate.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAutoSSLRenewal *int64 `cpanel:"notify_autossl_renewal,omitempty"`

	// Whether to send a notification when AutoSSL renews a certificate but the new
	// certificate lacks at least one domain that the previous certificate secured.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyAutoSSLRenewalCoverage *int64 `cpanel:"notify_autossl_renewal_coverage,omitempty"`

	// Whether to send a notification when someone changes the contact address for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyContactAddressChange *int64 `cpanel:"notify_contact_address_change,omitempty"`

	// Whether to send a notification when disables the notification for contact address
	//  changes.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyContactAddressChangeNotificationDisabled *int64 `cpanel:"notify_contact_address_change_notification_disabled,omitempty"`

	// Whether to send a notification when the account reaches its disk usage limit.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyDiskLimit *int64 `cpanel:"notify_disk_limit,omitempty"`

	// Whether to send a notification when someone changes the account's password.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyPasswordChange *int64 `cpanel:"notify_password_change,omitempty"`

	// Whether to send a notification when someone disables notifications for password changes.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifyPasswordChangeNotificationDisabled *int64 `cpanel:"notify_password_change_notification_disabled,omitempty"`

	// Whether to send a notification when an SSL certificate on the account expires.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	NotifySSLExpiry *int64 `cpanel:"notify_ssl_expiry,omitempty"`

	// Whether to suspend outgoing email on the account.
	//
	// * `1` — Suspend outgoing email.
	// * `0` — Do **not** suspend outgoing email.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	OutgoingEmailSuspended *int64 `cpanel:"OUTGOING_EMAIL_SUSPENDED,omitempty"`

	// A new owner's username or the `root` user, to change the account's owner.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// The authenticated user **must** have `root` privileges in order to assign the account
	// to a reseller other than that account.
	Owner *string `cpanel:"OWNER,omitempty"`

	// An access token for the account's [Pushbullet](https://www.pushbullet.com/)™
	// notifications.
	//
	// This parameter defaults to the defined system value.
	PushbulletAccessToken *string `cpanel:"PUSHBULLET_ACCESS_TOKEN,omitempty"`

	// The account's disk space quota, in multiples of 1,048,576 bytes.
	//
	// * `0`, `null`, or `unlimited` — The account's disk space is unlimited.
	//
	// This parameter defaults to the defined system value.
	Quota any `cpanel:"QUOTA,omitempty"`

	// A space-separated list of removed, missing, or uninstalled extensions.
	//
	// This parameter defaults to the defined system value.
	//
	// **Warning:**
	//
	// This parameter removes all of the extensions that you list from
	// the `_PACKAGE_EXTENSIONS` variable in the user file. It will **not** remove the
	// extensions' variables. For more information, read our
	// [Guide to Package Extensions](https://go.cpanel.net/GuidetoPackageExtensions).
	RemoveMissingExtensions *string `cpanel:"remove_missing_extensions,omitempty"`

	// Whether to rename the cPanel account's database objects to use a new username's
	// database prefix. This parameter **only** applies to servers that use database prefixing.
	//
	// * `1` — Rename the cPanel account's database objects.
	// * `0` — Do **not** rename the cPanel account's database objects.
	//
	// **Warning:**
	//
	// * The account owner **must** update any applications to use the new database object names.
	// * **Use this parameter carefully**. It can cause confusion for system administrators. …
	RenameDatabaseObjects *int64 `cpanel:"rename_database_objects,omitempty"`

	// Whether to grant reseller privileges to the account.
	//
	// * `1` — Grant reseller privileges.
	// * `0` — Do **not** grant reseller privileges.
	//
	// Possible values: `1`, `0`.
	//
	// Defaults to `0`.
	Reseller *int64 `cpanel:"reseller,omitempty"`

	// The account's cPanel interface theme.
	//
	// This parameter defaults to the defined system value.
	Rs *string `cpanel:"RS,omitempty"`

	// The absolute file path to the shell's location.
	//
	// This parameter defaults to the defined system value.
	Shell *string `cpanel:"shell,omitempty"`

	// Whether Apache SpamAssassin™ is enabled for the account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `1`, `0`.
	Spamassassin *int64 `cpanel:"spamassassin,omitempty"`

	// A timestamp for which to use as the account's creation date.
	//
	// This parameter defaults to the defined system value.
	Startdate *int64 `cpanel:"STARTDATE,omitempty"`

	// The account's cPanel interface style.
	//
	// This parameter defaults to the defined system value.
	Style *string `cpanel:"STYLE,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// MassModifyAcct calls the WHM API 1 function `massmodifyacct` — Update multiple cPanel accounts
//
// This function modifies multiple cPanel accounts.
//
// **Warning:**
//
// * We **strongly** recommend that you do not modify a cPanel account's settings
// if that account uses a hosting plan (package). If the package values change, the
// system will overwrite any of your custom values with the package's new values.
// * This function uses case-sensitive parameters. You **must** enter parameters in
// the correct case format. If you do not, the function will ignore that parameter.
//
// **Note:**
//
// On servers that run CentOS 7, you may see a `named` warning about the absence of
// SPF resource records on DNS.
//   * This warning is **not** relevant on CentOS 7 servers, because
//   [RFC 7208 deprecated SPF records](https://tools.ietf.org/html/rfc7208). CentOS 7
//   servers use TXT records instead of SPF records.
//   * Red Hat 7.1 and CentOS 7.1 both contain `bind-9.9.4-23.el7`, which is an updated
//   version of BIND that complies with RFC 7208. To resolve this issue, update your
//   operating system to a version that contains the updated version of BIND. For more
//   information, read the [Red Hat Bugzilla case about SPF record errors](https://bugzilla.redhat.com/show_bug.cgi?id=1215164).
//
// Available since cPanel & WHM version 88.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-massmodifyacct.md
func (c *Client) MassModifyAcct(ctx context.Context, args *MassModifyAcctArgs) (*cpanel.WHMResult[MassModifyAcctData], error) {
	return cpanel.WHMCall[MassModifyAcctData](ctx, c.c, http.MethodGet, "massmodifyacct", args)
}


// An object containing the account's modified settings.
type MassModifyAcctDataPayloadItemExtended struct {
	// An object containing the output of an account's `cpuser`
	// file. The system stores this file in the `/var/cpanel/users`
	// directory.
	//
	// **Note:**
	//
	// If the account or its hosting plan use
	// [package extensions](https://go.cpanel.net/GuidetoPackageExtensions),
	// the `cpuser` object will also include the extension's variables.
	Cpuser   map[string]json.RawMessage `json:"cpuser"`

	// The account's main domain.
	Domain   string `json:"domain"`

	// The absolute file path to the account's updated shell location.
	//
	// * `unmodified` — The shell's absolute filepath did not change.
	Setshell string `json:"setshell"`

	// The cPanel account's username.
	//
	// **Note:**
	//
	// If you changed the cPanel account's username, the function
	// returns the new value.
	User     string `json:"user"`
}

// MassModifyAcctDataPayloadItem is a generated payload type.
type MassModifyAcctDataPayloadItem struct {
	// An object containing the account's modified settings.
	Extended    MassModifyAcctDataPayloadItemExtended `json:"extended"`

	// A list containing account modification messages.
	Messages    []string `json:"messages"`

	// The hostnames of the
	// [linked cPanel server nodes](https://go.cpanel.net/serverroles)
	// from which the function proxied the return. The function returns
	// the hostnames in their proxied order.
	//
	// **Note:**
	//
	// The function **only** returns this value for
	// [distributed cPanel accounts](https://go.cpanel.net/cPanelGlossary#distributed-cpanel-account).
	ProxiedFrom []string `json:"proxied_from"`

	// The account's modification status.
	Reason      string `json:"reason"`

	// Whether the account modification succeeded.
	// * `1` — Success.
	// * `0` — Failure.
	//
	// Possible values: `1`, `0`.
	Result      int64 `json:"result"`

	// The modified account's username.
	User        string `json:"user"`

	// A list of warning messages for the modified account, if any exist.
	Warnings    []string `json:"warnings"`
}

// MassModifyAcctData is a generated payload type.
type MassModifyAcctData struct {
	// An array of objects containing data for each modified user.
	//
	// **Note:**
	//
	// If an account uses [linked cPanel server nodes](https://go.cpanel.net/whmdocsLinkServerNodes),
	// this object contains a return for each server on which the account exists.
	Payload []MassModifyAcctDataPayloadItem `json:"payload"`
}

// ModifyAcctArgs are the parameters of the WHM API 1 function `modifyacct`.
type ModifyAcctArgs struct {
	// The cPanel account's current username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// A list of names for [Account Enhancements](https://go.cpanel.net/account-enhancements) to assign to the cPanel account.
	//  To view your server's Account Enhancements, run WHM API 1's `list_account_enhancements` function.
	//
	// **Warning:**
	//
	// You must provide a complete list of Account Enhancements for the cPanel account. The parameter will add or remove Account Enhancements
	// based on the names that you provide.
	AccountEnhancements *string `cpanel:"account_enhancements,omitempty"`

	// Whether backups are enabled for the cPanel account.
	//
	// * `1` — Enable backups.
	// * `0` — Disable backups.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// You **must** have `root`-level privileges to set this parameter.
	//
	// Possible values: `0`, `1`.
	Backup *int64 `cpanel:"BACKUP,omitempty"`

	// The cPanel account's maximum bandwidth use, in bytes.
	//
	// * `0` or `unlimited` — The cPanel account can use unlimited bandwidth.
	//
	// This parameter defaults to the defined system value.
	Bwlimit any `cpanel:"BWLIMIT,omitempty"`

	// The cPanel account's contact email address.
	//
	// This parameter defaults to the defined system value.
	ContactEmail *string `cpanel:"contactemail,omitempty"`

	// The owner of the cPanel account's MySQL databases.
	//
	// This parameter defaults to the defined system value.
	Dbowner *string `cpanel:"DBOWNER,omitempty"`

	// The number of disk blocks for the cPanel account, in kilobytes (KB).
	//
	// This parameter defaults to the defined system value.
	DiskBlockLimit *int64 `cpanel:"DISK_BLOCK_LIMIT,omitempty"`

	// The cPanel account's main domain.
	//
	// This parameter is an alias of `domain`. If you set both
	// the `DNS` and `domain` parameters, the `DNS` parameter will
	// override the `domain` parameter.
	//
	// This parameter defaults to the defined system value.
	DNS *string `cpanel:"DNS,omitempty"`

	// The cPanel account's main domain.
	//
	// This parameter is an alias of `DNS`. If you set both
	// the `DNS` and `domain` parameters, the `DNS` parameter will
	// override the `domain` parameter.
	//
	// This parameter defaults to the defined system value.
	Domain *string `cpanel:"domain,omitempty"`

	// Whether CGI access is enabled for the cPanel account.
	//
	// * `1` — Enable CGI access.
	// * `0` — Disable CGI access.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// When a [server profile](https://go.cpanel.net/howtouseserverprofiles) disables the Web Server role, you **cannot** enable CGI access.
	//
	// Possible values: `0`, `1`.
	Hascgi *int64 `cpanel:"HASCGI,omitempty"`

	// Whether DKIM is enabled for the cPanel account.
	//
	// * `1` — Enable DKIM.
	// * `0` — Disable DKIM.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	Hasdkim *int64 `cpanel:"HASDKIM,omitempty"`

	// Whether DMARC is enabled for the cPanel account.
	//
	// * `1` — Enable DMARC.
	// * `0` — Disable DMARC.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	Hasdmarc *int64 `cpanel:"HASDMARC,omitempty"`

	// Whether shell (SSH) access is enabled for the cPanel account.
	//
	// * `1` — Enable shell access.
	// * `0` — Disable shell access.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// We **strongly** recommend that you use the `shell` parameter to specify a shell for SSH access.
	//
	// Possible values: `0`, `1`.
	Hasshell *int64 `cpanel:"HASSHELL,omitempty"`

	// Whether SPF is enabled for the cPanel account.
	//
	// * `1` — Enable SPF.
	// * `0` — Disable SPF.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	Hasspf *int64 `cpanel:"HASSPF,omitempty"`

	// The cPanel account's display language.
	//
	// This parameter defaults to the defined system value.
	Lang *string `cpanel:"LANG,omitempty"`

	// The cPanel account's default locale, in two-letter [ISO-3166 code](https://www.iso.org/iso-3166-country-codes.html) format.
	//
	// This parameter defaults to the defined system value.
	Locale *string `cpanel:"LOCALE,omitempty"`

	// The server that will manage the cPanel account's mail.
	//
	// * `.local` — Make the local server manage the cPanel account’s mail. If the account currently uses a [child node](https://go.cpanel.net/cPanelGlossary#child-node) for its mail, this will transfer the account’s mail to the local server.
	// * The alias (friendly name) of a child node that should manage the cPanel account’s mail. …
	MailNodeAlias *string `cpanel:"mail_node_alias,omitempty"`

	// The storage format that the cPanel account's mailboxes use.
	//
	// * `maildir`
	// * `mbox`
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `maildir`, `mbox`.
	MailboxFormat *string `cpanel:"MAILBOX_FORMAT,omitempty"`

	// The percentage of failed or deferred email messages that the
	// cPanel account can send per hour before outgoing mail is rate-limited.
	//
	// * `0` or `unlimited` — The cPanel account can send an unlimited number of failed or deferred messages.
	//
	// This parameter defaults to the defined system value.
	MaxDeferFailPercentage any `cpanel:"MAX_DEFER_FAIL_PERCENTAGE,omitempty"`

	// The maximum number of emails that the cPanel account can send in one hour.
	//
	// * `0` or `unlimited` — The cPanel account can send an unlimited number of emails.
	//
	// This parameter defaults to the defined system value.
	MaxEmailPerHour any `cpanel:"MAX_EMAIL_PER_HOUR,omitempty"`

	// The maximum quota, in megabytes (MB), that the cPanel account can define
	// when it creates an email account.
	//
	// * `unlimited` — The cPanel account can set unlimited quotas.
	//
	// This parameter defaults to the defined system value, or to `unlimited` if you do not define either the `plan` or `MAX_EMAILACCT_QUOTA` parameters.
	//
	// **Important:** …
	MaxEmailacctQuota any `cpanel:"MAX_EMAILACCT_QUOTA,omitempty"`

	// The maximum number of Team users for this account.
	// This parameter should be a number between 0 and the server's default value, inclusively.
	// This parameter can not be a number greater than the server's default value.
	MaxTeamUsers *int64 `cpanel:"max_team_users,omitempty"`

	// The cPanel account's maximum number of addon domains.
	//
	// * `0` or `unlimited` — The cPanel account can use unlimited addon domains.
	//
	// This parameter defaults to the defined system value.
	Maxaddon any `cpanel:"MAXADDON,omitempty"`

	// The cPanel account's maximum number of FTP accounts.
	//
	// * `unlimited` — The cPanel account can create unlimited FTP accounts.
	//
	// This parameter defaults to the defined system value.
	Maxftp any `cpanel:"MAXFTP,omitempty"`

	// The cPanel account's maximum number of mailing lists.
	//
	// * `0` or `unlimited` — The cPanel account can create unlimited mailing lists.
	//
	// This parameter defaults to the defined system value.
	Maxlst any `cpanel:"MAXLST,omitempty"`

	// The cPanel account's maximum number of parked domains (aliases).
	//
	// * `unlimited` — The cPanel account can use unlimited parked domains.
	//
	// This parameter defaults to the defined system value.
	Maxpark any `cpanel:"MAXPARK,omitempty"`

	// The cPanel account's maximum number of Ruby applications.
	//
	// * `unlimited` — The cPanel account can use unlimited Ruby applications.
	//
	// This parameter defaults to the defined system value.
	MaxPassengerApps any `cpanel:"MAXPASSENGERAPPS,omitempty"`

	// The maximum number of email accounts for the cPanel account.
	//
	// * `unlimited` — The cPanel account can create unlimited email accounts.
	//
	// This parameter defaults to the defined system value.
	Maxpop any `cpanel:"MAXPOP,omitempty"`

	// The maximum number of each available type of SQL database for
	// the cPanel account. For example, if you set this value to `5`
	// and the system administrator allows MySQL® and PostgreSQL®
	// databases, users can create up to five MySQL databases and up
	// to five PostgreSQL databases.
	//
	// * `unlimited` — The cPanel account can create unlimited databases.
	//
	// This parameter defaults to the defined system value.
	Maxsql any `cpanel:"MAXSQL,omitempty"`

	// The maximum number of subdomains for the cPanel account.
	//
	// * `unlimited` — The cPanel account can create unlimited subdomains.
	//
	// This parameter defaults to the defined system value.
	Maxsub any `cpanel:"MAXSUB,omitempty"`

	// Whether to modify the firewall rules as part of the cPanel account modification.
	//
	// * `1` — Modify the firewall rules.
	// * `0` — Do **not** modify the firewall rules.
	//
	// **Note:**
	//
	// If you do not set this parameter, the system will modify the firewall based on the *Do not make changes to the firewall during cPanel account modification.* setting in WHM's [*Tweak Settings*](https://go.cpanel.net/whmdocsTweakSettings) interface (*WHM >> Home >> Server Configuration >> Tweak Settings*). …
	ModifyFirewall *int64 `cpanel:"modify_firewall,omitempty"`

	// The priority of the cPanel account's primary mail exchanger.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// The parameter name consists of `MXCHECK`, a hyphen, and the primary domain name of
	// the cPanel account. For example, `MXCHECK-example.com=10`.
	Mxcheck *int64 `cpanel:"MXCHECK-*,omitempty"`

	// The cPanel account's new username.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// * Usernames **cannot** begin with a number or the string `test`.
	// * Usernames can contain 16 characters or fewer if database prefixes are enabled.
	// * The first eight characters of usernames **must** be unique. MySQL requires this due to potential conflicts with cPanel account transfers. However, this limit requirement does **not** exist on servers that use MariaDB.
	// * If you rename the cPanel accoun …
	Newuser *string `cpanel:"newuser,omitempty"`

	// Whether to send a notification when someone links the cPanel
	// account to an external authentication account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAccountAuthnLink *int64 `cpanel:"notify_account_authn_link,omitempty"`

	// Whether to send a notification when someone disables notifications
	// for external authentication account links.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAccountAuthnLinkNotificationDisabled *int64 `cpanel:"notify_account_authn_link_notification_disabled,omitempty"`

	// Whether to send a notification when an AutoSSL certificate expires.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAutoSSLExpiry *int64 `cpanel:"notify_autossl_expiry,omitempty"`

	// Whether to send a notification AutoSSL cannot renew a certificate
	// because domains that fail Domain Control Validation (DCV) exist on the current
	// certificate.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAutoSSLExpiryCoverage *int64 `cpanel:"notify_autossl_expiry_coverage,omitempty"`

	// Whether to send a notification when AutoSSL renews a certificate.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAutoSSLRenewal *int64 `cpanel:"notify_autossl_renewal,omitempty"`

	// Whether to send a notification when AutoSSL renews a certificate
	// but the new certificate lacks at least one domain that the previous certificate
	// secured.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyAutoSSLRenewalCoverage *int64 `cpanel:"notify_autossl_renewal_coverage,omitempty"`

	// Whether to send a notification when someone changes the contact
	// address for the cPanel account.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyContactAddressChange *int64 `cpanel:"notify_contact_address_change,omitempty"`

	// Whether to send a notification when disables the notification
	// for contact address changes.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyContactAddressChangeNotificationDisabled *int64 `cpanel:"notify_contact_address_change_notification_disabled,omitempty"`

	// Whether to send a notification when the cPanel account reaches its disk usage limit.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyDiskLimit *int64 `cpanel:"notify_disk_limit,omitempty"`

	// Whether to send a notification when someone changes the cPanel account's
	// password.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyPasswordChange *int64 `cpanel:"notify_password_change,omitempty"`

	// Whether to send a notification when someone disables notifications
	// for password changes.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifyPasswordChangeNotificationDisabled *int64 `cpanel:"notify_password_change_notification_disabled,omitempty"`

	// Whether to send a notification when an SSL certificate on the
	// cPanel account expires.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	NotifySSLExpiry *int64 `cpanel:"notify_ssl_expiry,omitempty"`

	// Whether to suspend outgoing email on the cPanel account.
	//
	// * `1` — Suspend outgoing email.
	// * `0` — Do **not** suspend outgoing email.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	OutgoingEmailSuspended *int64 `cpanel:"OUTGOING_EMAIL_SUSPENDED,omitempty"`

	// A new owner's username or the `root` user, to change the cPanel account's owner.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// The authenticated user must have `root` privileges in order to assign the cPanel account to a reseller other than that cPanel account.
	Owner *string `cpanel:"owner,omitempty"`

	// An access token for the cPanel account's Pushbullet™ notifications.
	//
	// This parameter defaults to the defined system value.
	PushbulletAccessToken *string `cpanel:"PUSHBULLET_ACCESS_TOKEN,omitempty"`

	// The cPanel account's disk space quota.
	//
	// * An integer in multiples of 1,048,576 bytes.
	// * `0` or `unlimited` — The cPanel account's disk space is unlimited.
	//
	// This parameter defaults to the defined system value.
	Quota any `cpanel:"QUOTA,omitempty"`

	// A space-separated list of removed, missing, or uninstalled package extensions.
	//
	// **Warning:**
	//
	// This parameter removes all of the extensions that you list from the `_PACKAGE_EXTENSIONS` variable in the user file. It will **not** remove the extensions' variables. For more information, read our [Guide to Package Extensions](https://go.cpanel.net/GuidetoPackageExtensions).
	//
	// Defaults to ``.
	RemoveMissingExtensions *string `cpanel:"remove_missing_extensions,omitempty"`

	// Whether to rename the cPanel account's database objects to use a new username's database prefix.
	//
	// * `1` — Rename the cPanel account's database objects.
	// * `0` — Do **not** rename the cPanel account's database objects.
	//
	// **Warning:**
	//
	// * The cPanel account owner must update any applications to use the new database object names.
	// * **Use this parameter carefully**, as it may cause confusion for system administrators. …
	RenameDatabaseObjects *int64 `cpanel:"rename_database_objects,omitempty"`

	// Whether to grant reseller privileges to the cPanel account.
	//
	// * `1` — Grant reseller privileges.
	// * `0` — Do **not** grant reseller privileges.
	//
	// **Note:**
	//
	// You **must** have `root`-level privileges to use this parameter.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	Reseller *int64 `cpanel:"reseller,omitempty"`

	// The cPanel account's cPanel theme.
	//
	// This parameter defaults to the defined system value.
	Rs *string `cpanel:"RS,omitempty"`

	// The absolute filepath to the shell's location.
	//
	// This parameter defaults to the defined system value.
	Shell *string `cpanel:"shell,omitempty"`

	// Whether Apache SpamAssassin™ is enabled for the cPanel account.
	//
	// This parameter defaults to the defined system value.
	//
	// Possible values: `0`, `1`.
	Spamassassin *int64 `cpanel:"spamassassin,omitempty"`

	// A timestamp to use as the cPanel account's creation date.
	//
	// This parameter defaults to the defined system value.
	//
	// **Note:**
	//
	// This parameter does **not** provide user access controls. For example, you cannot modify a
	// cPanel account's date to prevent a user from logging in to the server.
	Startdate *int64 `cpanel:"STARTDATE,omitempty"`

	// The cPanel account's cPanel interface theme style.
	//
	// This parameter defaults to the defined system value.
	Style *string `cpanel:"STYLE,omitempty"`

	// Whether to update the quota for existing email accounts to match the value of `MAX_EMAILACCT_QUOTA` setting.
	//
	// * `1` — Update quota for existing email accounts.
	// * `0` — Do not update quota for existing email accounts.
	//
	// **Important:**
	//
	// To use this parameter, you **must** also use the `MAX_EMAILACCT_QUOTA` parameter.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	UpdateExistingEmailAccountQuotas *int64 `cpanel:"update_existing_email_account_quotas,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ModifyAcct calls the WHM API 1 function `modifyacct` — Update cPanel account
//
// This function modifies a cPanel account.
//
// **Warning:**
//
// We **strongly** recommend that you **do not** modify a single cPanel account's settings if that cPanel account uses a hosting plan (package). If the package values change, **the system will overwrite any of your custom values with the package's new values**.
//
// **Note:**
//
// On servers that run CentOS 7, you may see a `named` warning about the absence of SPF resource records on DNS.
//   * This warning is **not** relevant on CentOS 7 servers, because [RFC 7208 deprecated SPF records](https://tools.ietf.org/html/rfc7208). CentOS 7 servers use TXT records instead of SPF records.
//   * Red Hat 7.1 and CentOS 7.1 both contain `bind-9.9.4-23.el7`, which is an updated version of BIND that complies with RFC 7208. To resolve this issue, update your operating system to a version that contains the updated version of BIND. For more information, read the [Red Hat Bugzilla case about SPF record errors](https://bugzilla.redhat.com/show_bug.cgi?id=1215164).
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-modifyacct.md
func (c *Client) ModifyAcct(ctx context.Context, args *ModifyAcctArgs) (*cpanel.WHMResult[ModifyAcctData], error) {
	return cpanel.WHMCall[ModifyAcctData](ctx, c.c, http.MethodGet, "modifyacct", args)
}


// ModifyAcctData is a generated payload type.
type ModifyAcctData struct {
	// An object that contains the cPanel account's modified information.
	//
	// **Note:**
	//
	// * The possible properties in this section are the same as the possible query parameters (the attributes of the cPanel account).
	// * These properties show up even if the query did **not** modify them.
	// * Some of these properties **only** appear under certain other conditions.
	// * If the cPanel account or its hosting plan use …
	Cpuser   map[string]json.RawMessage `json:"cpuser"`

	// The cPanel account's main domain.
	Domain   string `json:"domain"`

	// The absolute path to the cPanel account's shell.
	Setshell string `json:"setshell"`

	// The cPanel account username.
	//
	// **Note:**
	//
	// If you changed the cPanel account's username, the function returns the new value.
	User     string `json:"user"`
}

// Myprivs calls the WHM API 1 function `myprivs` — Return cPanel account system privileges
//
// This function retrieves the current user's [Access Control List (ACL)](https://go.cpanel.net/whmdocsEditResellerNameserversandPrivileges) privileges.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/acls-myprivs.md
func (c *Client) Myprivs(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[MyprivsData], error) {
	return cpanel.WHMCall[MyprivsData](ctx, c.c, http.MethodGet, "myprivs", cpanel.CombineArgs(extra...))
}


// MyprivsDataPrivilegesItem is a generated payload type.
type MyprivsDataPrivilegesItem struct {
	// Allows the user to view an account summary.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AcctSummary            int64 `json:"acct-summary"`

	// Allows the user to create packages.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AddPkg                 int64 `json:"add-pkg"`

	// Allows the user to create packages with dedicated IP addresses.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AddPkgIP               int64 `json:"add-pkg-ip"`

	// Allows the user to create packages with shell access.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AddPkgShell            int64 `json:"add-pkg-shell"`

	// Provides all access privileges to the user.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Warning:**
	//
	// If this value is set to `1` , the user has `root` access.
	//
	// Possible values: `0`, `1`.
	All                    int64 `json:"all"`

	// Allows the user to create packages with addon domains.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowAddoncreate       int64 `json:"allow-addoncreate"`

	// Allows the user to create packages with custom email limits.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowEmaillimitsPkgs   int64 `json:"allow-emaillimits-pkgs"`

	// Allows the user to create packages with parked domains (aliases).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowParkedcreate      int64 `json:"allow-parkedcreate"`

	// Allows the user to create an account with shell access.
	// * `1` — Enabled.
	// * `0` — Disabled.
	AllowShell             int64 `json:"allow-shell"`

	// Allows the user to create packages with unlimited bandwidth.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowUnlimitedBwPkgs   int64 `json:"allow-unlimited-bw-pkgs"`

	// Allows the user to create packages with unlimited disk space quotas.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowUnlimitedDiskPkgs int64 `json:"allow-unlimited-disk-pkgs"`

	// Allows the user to create packages with unlimited values for features (for example, unlimited email accounts).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	AllowUnlimitedPkgs     int64 `json:"allow-unlimited-pkgs"`

	// Allows the user to retrieve basic system information.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	BasicSystemInfo        int64 `json:"basic-system-info"`

	// Whether to give the reseller access to basic cPanel & WHM options.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	BasicWHMFunctions      int64 `json:"basic-whm-functions"`

	// Allows the user to configure DNS clusters.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Clustering             int64 `json:"clustering"`

	// Allows the user to perform Cross-Origin Resource Sharing (CORS) HTTP requests.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	CorsProxyGet           int64 `json:"cors-proxy-get"`

	// Allows the reseller to execute cPanel [UAPI](https://go.cpanel.net/uapi) functions via WHM.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	CpanelAPI              int64 `json:"cpanel-api"`

	// Allows the user to manage how their server and its services connect to other servers and services.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	CpanelIntegration      int64 `json:"cpanel-integration"`

	// Allows the user to create accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	CreateAcct             int64 `json:"create-acct"`

	// Allows the user to create DNS zones.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	CreateDNS              int64 `json:"create-dns"`

	// Allows the user to create a new temporary user session for a specified service.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Note:**
	//
	// This privilege allows an API token user to bypass any restrictions that you set on the API token. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `0`, `1`.
	CreateUserSession      int64 `json:"create-user-session"`

	// Allows the user to enable demo mode on accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	DemoSetup              int64 `json:"demo-setup"`

	// Allows the user to manage Digest Authentication support.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	DigestAuth             int64 `json:"digest-auth"`

	// Allows the user to modify accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Warning:**
	//
	// This privilege allows circumvention of account creation limits, gives shell access unless explicitly disallowed, and provides access to dedicated IP addresses, among other features.
	//
	// Possible values: `0`, `1`.
	EditAccount            int64 `json:"edit-account"`

	// Allows the user to edit DNS zones.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	EditDNS                int64 `json:"edit-dns"`

	// Allows the user to edit MX entries.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	EditMX                 int64 `json:"edit-mx"`

	// Allows the user to create and delete packages.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	EditPkg                int64 `json:"edit-pkg"`

	// Allows the user to restore specific files and directories from a backup.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	FileRestore            int64 `json:"file-restore"`

	// Allows the user to generate a mobile configuration profile for an email account.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	GenerateEmailConfig    int64 `json:"generate-email-config"`

	// Allows the user to delete their customers' accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	KillAcct               int64 `json:"kill-acct"`

	// Allows the user to delete DNS zones.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	KillDNS                int64 `json:"kill-dns"`

	// Allows the user to modify bandwidth limits on their accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Warning:**
	//
	//  This will allow circumvention of account package limits if you do not use resource limits.
	//
	// Possible values: `0`, `1`.
	LimitBandwidth         int64 `json:"limit-bandwidth"`

	// Allows the user to list owned accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ListAccts              int64 `json:"list-accts"`

	// Allows the user to view existing hosting plans (packages).
	// * `1` — Enabled.
	// * `0` — Disabled.
	ListPkgs               int64 `json:"list-pkgs"`

	// Allows the user to create and modify locales on the server.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	LocaleEdit             int64 `json:"locale-edit"`

	// Allows the user to access WHM's [_Mail Troubleshooter_](https://go.cpanel.net/whmdocsMailTroubleshooter) interface (_WHM >> Home >> Mail >> Mail Troubleshooter_).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Mailcheck              int64 `json:"mailcheck"`

	// Allows the user to manage API tokens.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Note:**
	//
	// This ACL privilege allows an API token user to bypass any restrictions that you set on the API token.
	//
	// Possible values: `0`, `1`.
	ManageAPITokens        int64 `json:"manage-api-tokens"`

	// Allows the user to manage DNS records.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ManageDNSRecords       int64 `json:"manage-dns-records"`

	// Allows the user to manage external authentication for their accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ManageOidc             int64 `json:"manage-oidc"`

	// Allows the user to manage their server's cPanel styles.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ManageStyles           int64 `json:"manage-styles"`

	// Allows the user to retrieve MySQL® database and user data.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	MysqlInfo              int64 `json:"mysql-info"`

	// Allows the user to send news messages to customers' accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	News                   int64 `json:"news"`

	// Allows the user to manage nameservers.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	NSConfig               int64 `json:"ns-config"`

	// Allows the user to park domains within WHM.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ParkDNS                int64 `json:"park-dns"`

	// Allows the user to modify passwords for customers' accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Note:**
	//
	//  This privilege allows an API token user to change account passwords and log in with a new password. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `0`, `1`.
	Passwd                 int64 `json:"passwd"`

	// Allows the user to modify disk space quotas for accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// **Warning:**
	//
	//  This ACL privilege allows circumvention of account package limits if you do not use resource limits.
	//
	// Possible values: `0`, `1`.
	Quota                  int64 `json:"quota"`

	// Allows the user to rearrange the locations of customer accounts in order to free up disk space.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	RearrangeAccts         int64 `json:"rearrange-accts"`

	// Allows the user to re-sync FTP account passwords.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Resftp                 int64 `json:"resftp"`

	// Allows the user to restart services on the server, such as Apache® or Exim.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Restart                int64 `json:"restart"`

	// Allows the user to view the bandwidth usage of accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ShowBandwidth          int64 `json:"show-bandwidth"`

	// Allows the user to manage the SSL certificates installed on domains.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SSL                    int64 `json:"ssl"`

	// Allows the user to use WHM's [_Purchase and Install an SSL Certificate_](https://go.cpanel.net/whmdocsPurchaseandInstallanSSLCertificate) interface (_WHM >> Home >> SSL/TLS >> Purchase and Install an SSL Certificate_).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SSLBuy                 int64 `json:"ssl-buy"`

	// Allows the user to use the SSL CSR/CRT generator.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SSLGencrt              int64 `json:"ssl-gencrt"`

	// Allows the user to view their server's SSL information.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SSLInfo                int64 `json:"ssl-info"`

	// Allows the user to view WHM's [_Server Information_](https://go.cpanel.net/whmdocsServerInformation) interface (_WHM >> Home >> Server Status >> Server Information_).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Stats                  int64 `json:"stats"`

	// Allows the user to view WHM's [_Service Status_](https://go.cpanel.net/whmdocsServiceStatus) interface (_WHM >> Home >> Server Status >> Service Status_).
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Status                 int64 `json:"status"`

	// Allows the user to suspend customers' accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SuspendAcct            int64 `json:"suspend-acct"`

	// Allows the user to manage third-party service offerings.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	Thirdparty             int64 `json:"thirdparty"`

	// Allows the user to view reports about email message delivery attempts from their account.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	TrackEmail             int64 `json:"track-email"`

	// Allows the user to upgrade and downgrade customers' domain accounts.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	UpgradeAccount         int64 `json:"upgrade-account"`

	// Whether to allow the reseller to use all global packages. For more information, read our [reseller packages](https://go.cpanel.net/resellerpackages) documentation.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	ViewGlobalPackages     int64 `json:"viewglobalpackages"`
}

// MyprivsData is a generated payload type.
type MyprivsData struct {
	// An array of objects that contains the privileges available to the user, including any third-party ACL privileges.
	Privileges []MyprivsDataPrivilegesItem `json:"privileges"`
}

// SetDigestAuthArgs are the parameters of the WHM API 1 function `set_digest_auth`.
type SetDigestAuthArgs struct {
	// Whether to enable Digest Authentication for the account.
	//
	// * `1` — Enable.
	// * `0` — Disable.
	//
	// Possible values: `0`, `1`.
	//
	// This parameter is required.
	Enabledigest int64 `cpanel:"enabledigest"`

	// The account's password.
	//
	// This parameter is required.
	Password string `cpanel:"password"`

	// The account's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to enable Digest Authentication for the account. This is an alias for the `enabledigest` parameter.
	//
	// * `1` — Enable.
	// * `0` — Disable.
	//
	// Possible values: `0`, `1`.
	DigestAuth *int64 `cpanel:"digestauth,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetDigestAuth calls the WHM API 1 function `set_digest_auth` — Enable or disable Digest Authentication
//
// This function enables or disables Digest Authentication for an account. Windows Vista®,
// Windows® 7, and Windows® 8 requires that you enable Digest Authentication support in order
// to access your [Web Disk](https://docs.cpanel.net/cpanel/files/web-disk/) over a clear text,
// unencrypted connection.
//
// **Note:**
//
// If the server has an SSL certificate that a recognized certificate authority signed and you
// can make an SSL connection over port `2078`, you do **not** need to enable Digest Authentication.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/sys-set_digest_auth.md
func (c *Client) SetDigestAuth(ctx context.Context, args *SetDigestAuthArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "set_digest_auth", args)
}


// UntrackAcctIDArgs are the parameters of the WHM API 1 function `untrack_acct_id`.
type UntrackAcctIDArgs struct {
	// Whether to prevent removal of user or group IDs currently in use.
	//
	// * `1` — Prevent removal.
	// * `0` — Do **not** prevent removal.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `1`.
	CheckExists *int64 `cpanel:"check_exists,omitempty"`

	// Whether to prevent removal of the user ID if the quota system tracks associated files.
	//
	// * `1` — Prevent removal.
	// * `0` — Do **not** prevent removal.
	//
	// **Note:**
	//
	// * This parameter **only** applies to user IDs and **not** group IDs.
	// * You cannot check filesystems if the quota system does **not** track them.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `1`.
	CheckQuota *int64 `cpanel:"check_quota,omitempty"`

	// The group ID to remove from the track list.
	//
	// **Note:**
	//
	//  You **must** include the `uid` parameter, the `gid` parameter, or both.
	Gid *int64 `cpanel:"gid,omitempty"`

	// Whether to prevent removal of system user or group IDs.
	//
	// * `1` — Prevent removal.
	// * `0` — Do **not** prevent removal.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `1`.
	ProtectSystem *int64 `cpanel:"protect_system,omitempty"`

	// The user ID to remove from the track list.
	//
	// **Note:**
	//
	//  You **must** include the `uid` parameter, the `gid` parameter, or both.
	Uid *int64 `cpanel:"uid,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UntrackAcctID calls the WHM API 1 function `untrack_acct_id` — Remove UID or GID from tracked list
//
// This function removes a user identification number (UID) or group
// identification number (GID) from the tracked ID list.
//
// Available since cPanel & WHM version 58.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-management/accounts-untrack_acct_id.md
func (c *Client) UntrackAcctID(ctx context.Context, args *UntrackAcctIDArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "untrack_acct_id", args)
}

