// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// DeleteCustomizationsArgs are the parameters of the WHM API 1 function `delete_customizations`.
type DeleteCustomizationsArgs struct {
	// The application name for the customization.
	//
	// Possible values: `cpanel`, `webmail`.
	//
	// This parameter is required.
	Application string `cpanel:"application"`

	// The theme name for the customization.
	//
	// This parameter is required.
	Theme string `cpanel:"theme"`

	// The JSONPath expression to reach to property you want to delete. We support only the
	// subset of JSONPath using the `.` style notation. There is presently no other JSONPath
	// features supported.
	Path *string `cpanel:"path,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeleteCustomizations calls the WHM API 1 function `delete_customizations` — Delete customization data
//
// This function deletes customization data.
//
// Customization data includes brand logos and colors.
//
// Server owners and resellers can supply customization data to whitelabel portions
// of the product or customize the cPanel experience for their users.
//
// This function is used to delete customization data for the Jupiter theme **only**.
//
// If you provide the optional `path` parameter, the API will removed only the specific element specified in the `.` separated path.
// See the parameter for more details.
//
// Available since cPanel & WHM version 100.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-delete_customizations.md
func (c *Client) DeleteCustomizations(ctx context.Context, args *DeleteCustomizationsArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "delete_customizations", args)
}


// RetrieveCustomizationsArgs are the parameters of the WHM API 1 function `retrieve_customizations`.
type RetrieveCustomizationsArgs struct {
	// The application name for the customization.
	//
	// Possible values: `cpanel`, `webmail`.
	//
	// This parameter is required.
	Application string `cpanel:"application"`

	// The theme for the customization.
	//
	// This parameter is required.
	Theme string `cpanel:"theme"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// RetrieveCustomizations calls the WHM API 1 function `retrieve_customizations` — Retrieve customization data
//
// This function retrieves customization data.
//
// Customization data includes brand logos and colors.
//
// This function is used to retrieve customization data for the Jupiter theme **only**.
//
// Available since cPanel & WHM version 100.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-retrieve_customizations.md
func (c *Client) RetrieveCustomizations(ctx context.Context, args *RetrieveCustomizationsArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "retrieve_customizations", args)
}


// UpdateCustomizationsArgs are the parameters of the WHM API 1 function `update_customizations`.
type UpdateCustomizationsArgs struct {
	// The application name for the customization.
	//
	// Possible values: `cpanel`, `webmail`.
	//
	// This parameter is required.
	Application string `cpanel:"application"`

	// The theme data to save.
	//
	// This parameter is required.
	Data string `cpanel:"data"`

	// The theme name for the customization.
	//
	// Possible values: `jupiter`.
	//
	// This parameter is required.
	Theme string `cpanel:"theme"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UpdateCustomizations calls the WHM API 1 function `update_customizations` — Update customization data
//
// This function supplies branding data for a specific application and theme.
//
// Customization data includes brand logos and colors.
//
// This function is used to save customization data for the Jupiter theme **only**.
//
// This function requires an HTTP POST request.
//
// Available since cPanel & WHM version 100.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-update_customizations.md
func (c *Client) UpdateCustomizations(ctx context.Context, args *UpdateCustomizationsArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodPost, "update_customizations", args)
}

