// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// GetTweaksettingArgs are the parameters of the WHM API 1 function `get_tweaksetting`.
type GetTweaksettingArgs struct {
	// The [*Tweak Settings*](https://go.cpanel.net/whmdocsTweakSettings) option.
	//
	// This parameter is required.
	Key string `cpanel:"key"`

	// One of the following *Tweak Settings* module names:
	// * `Apache`
	// * `Basic`
	// * `Mail`
	// * `Main`
	//
	// Possible values: `Apache`, `Basic`, `Mail`, `Main`.
	//
	// Defaults to `Main`.
	Module *string `cpanel:"module,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetTweaksetting calls the WHM API 1 function `get_tweaksetting` — Return Tweak Settings option's value
//
// This function retrieves values from the
// [`/var/cpanel/cpanel.config`](https://go.cpanel.net/ThecpanelconfigFile)
// file and the server's [Exim configuration](https://go.cpanel.net/whmdocsEximConfigurationManager).
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/configurations/cpanel-get_tweaksetting.md
func (c *Client) GetTweaksetting(ctx context.Context, args *GetTweaksettingArgs) (*cpanel.WHMResult[GetTweaksettingData], error) {
	return cpanel.WHMCall[GetTweaksettingData](ctx, c.c, http.MethodGet, "get_tweaksetting", args)
}


// A list of the *Tweak Settings* option's information.
type GetTweaksettingDataTweaksetting struct {
	// A key name in the `cpanel.config` file.
	Key   string `json:"key"`

	// The value. This value depends on the `key` value's requirements.
	Value string `json:"value"`
}

// GetTweaksettingData is a generated payload type.
type GetTweaksettingData struct {
	// A list of the *Tweak Settings* option's information.
	Tweaksetting GetTweaksettingDataTweaksetting `json:"tweaksetting"`
}

// SetTweaksettingArgs are the parameters of the WHM API 1 function `set_tweaksetting`.
type SetTweaksettingArgs struct {
	// The `cpanel.config` setting name that corresponds to the desired
	// setting in WHM's
	// [*Tweak Settings*](https://docs.cpanel.net/whm/server-configuration/tweak-settings/)
	// interface (*WHM >>Home >> Server Configuration >> Tweak Settings*).
	//
	// This parameter is required.
	Key string `cpanel:"key"`

	// The
	// [*Tweak Settings*](https://docs.cpanel.net/whm/server-configuration/tweak-settings/)
	// interface section.
	//
	// **Note:**
	//
	// The possible section names are:
	// * `Apache`
	// * `Basic`
	// * `Mail`
	// * `Main`
	//
	// Possible values: `Apache`, `Basic`, `Mail`, `Main`.
	//
	// Defaults to `Main`.
	Module *string `cpanel:"module,omitempty"`

	// The value to assign to the setting. If you include this parameter in the call but
	// do **not** set a value, the value defaults to an empty value.
	//
	// **Note:**
	//
	// For more information about the requirements for values in the `cpanel.config`
	// file settings, read our
	// [`cpanel.config` file](https://docs.cpanel.net/knowledge-base/cpanel-product/the-cpanel-config-file/)
	// documentation.
	Value *string `cpanel:"value,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetTweaksetting calls the WHM API 1 function `set_tweaksetting` — Update Tweak Settings option
//
// This function sets an option's value in WHM's
// [*Tweak Settings*](https://docs.cpanel.net/whm/server-configuration/tweak-settings/)
// interface (*WHM >> Home >> Server Configuration >> Tweak Settings*). The
// system stores the keys and values that this function updates in
// the
// [`/var/cpanel/cpanel.config`](https://docs.cpanel.net/knowledge-base/cpanel-product/the-cpanel-config-file/)
// file.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/configurations/cpanel-set_tweaksetting.md
func (c *Client) SetTweaksetting(ctx context.Context, args *SetTweaksettingArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "set_tweaksetting", args)
}

