// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// CPGreyListIsServerNetblockTrusted calls the WHM API 1 function `cpgreylist_is_server_netblock_trusted` — Return Greylisting trust status of server netblock
//
// This function returns the Greylisting trusted status of the server's netblock.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListIsServerNetblockTrusted(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[CPGreyListIsServerNetblockTrustedData], error) {
	return cpanel.WHMCall[CPGreyListIsServerNetblockTrustedData](ctx, c.c, http.MethodGet, "cpgreylist_is_server_netblock_trusted", cpanel.CombineArgs(extra...))
}

// CPGreyListIsServerNetblockTrustedData is a generated payload type.
type CPGreyListIsServerNetblockTrustedData struct {
	// A list containing the neighboring netblocks.
	IPBlocks map[string]int64 `json:"ip_blocks"`
}

// CPGreyListListEntriesForCommonMailProviderArgs are the parameters of the WHM API 1 function `cpgreylist_list_entries_for_common_mail_provider`.
type CPGreyListListEntriesForCommonMailProviderArgs struct {
	// The mail provider.
	//
	// **Note:**
	//
	//  * To list entries for multiple mail providers, increment the parameter name. For example, `provider-0`, `provider-1`, and `provider-2`.
	//  * Call WHM API 1's `cpgreylist_load_common_mail_providers_config` function to return a list of valid provider keys.
	//
	// This parameter is required.
	Provider string `cpanel:"provider"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CPGreyListListEntriesForCommonMailProvider calls the WHM API 1 function `cpgreylist_list_entries_for_common_mail_provider` — Return Greylisting IP addresses of mail providers
//
// This function lists Greylisting's IP addresses for the specified mail provider.
//
// Available since cPanel & WHM version 11.52.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListListEntriesForCommonMailProvider(ctx context.Context, args *CPGreyListListEntriesForCommonMailProviderArgs) (*cpanel.WHMResult[CPGreyListListEntriesForCommonMailProviderData], error) {
	return cpanel.WHMCall[CPGreyListListEntriesForCommonMailProviderData](ctx, c.c, http.MethodGet, "cpgreylist_list_entries_for_common_mail_provider", args)
}

// An object containing the mail provider's IP address data.
type CPGreyListListEntriesForCommonMailProviderDataProvidersValueIPs struct {
	// The date and time when the function created the record.
	CreateTime string `json:"create_time"`

	// The mail provider's IP address or range.
	HostIP string `json:"host_ip"`

	// Whether Greylisting trusts this mail provider's IP addresses.
	// - `1` — Trusted.
	// - `0` — Not trusted.
	//
	// Possible values: `0`, `1`.
	IsTrusted int64 `json:"is_trusted"`

	// The mail provider's identification number.
	ProviderID int64 `json:"provider_id"`
}

// An object containing an object that contains the mail provider's IP address data.
//
// **Note:**
//
// The return's name is the mail provider's display name.
type CPGreyListListEntriesForCommonMailProviderDataProvidersValue struct {
	// An object containing the mail provider's IP address data.
	IPs CPGreyListListEntriesForCommonMailProviderDataProvidersValueIPs `json:"ips"`
}

// CPGreyListListEntriesForCommonMailProviderData is a generated payload type.
type CPGreyListListEntriesForCommonMailProviderData struct {
	// An object containing mail providers and their IP addresses.
	Providers map[string]CPGreyListListEntriesForCommonMailProviderDataProvidersValue `json:"providers"`

	// An object containing mail providers that the system failed to retrieve data for.
	ProvidersFailed map[string]string `json:"providers_failed"`
}

// CPGreyListLoadCommonMailProvidersConfig calls the WHM API 1 function `cpgreylist_load_common_mail_providers_config` — Return Greylisting mail providers
//
// This function returns Greylisting's list of common mail service providers.
//
// Available since cPanel & WHM version 11.52.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListLoadCommonMailProvidersConfig(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[CPGreyListLoadCommonMailProvidersConfigData], error) {
	return cpanel.WHMCall[CPGreyListLoadCommonMailProvidersConfigData](ctx, c.c, http.MethodGet, "cpgreylist_load_common_mail_providers_config", cpanel.CombineArgs(extra...))
}

// An object containing the provider's data.
//
// **Note:**
//
//	The object's name is the provider's key name.
type CPGreyListLoadCommonMailProvidersConfigDataCommonMailProvidersValue struct {
	// Whether Greylisting automatically trusts new IP addresses that WebPros International, LLC adds for this mail provider.
	// * `1` - New IP addresses are automatically trusted.
	// * `0` - New IP addresses are **not** automatically trusted.
	//
	// Possible values: `0`, `1`.
	AutoUpdate int64 `json:"autoupdate"`

	// The mail provider's name.
	DisplayName string `json:"display_name"`

	// Whether Greylisting trusts this mail provider's IP addresses.
	// * `1` - The provider is trusted.
	// * `0` - The provider is **not** trusted.
	//
	// Possible values: `0`, `1`.
	IsTrusted int64 `json:"is_trusted"`
}

// CPGreyListLoadCommonMailProvidersConfigData is a generated payload type.
type CPGreyListLoadCommonMailProvidersConfigData struct {
	// Whether Greylisting automatically trusts new mail providers that WebPros International, LLC adds to the common mail providers list.
	// * `1` - New mail providers are automatically trusted.
	// * `0` - New mail providers are **not** automatically trusted.
	//
	// Possible values: `0`, `1`.
	AutotrustNewCommonMailProviders int64 `json:"autotrust_new_common_mail_providers"`

	// An object containing common mail provider settings.
	CommonMailProviders map[string]CPGreyListLoadCommonMailProvidersConfigDataCommonMailProvidersValue `json:"common_mail_providers"`
}

// CPGreyListSaveCommonMailProvidersConfigArgs are the parameters of the WHM API 1 function `cpgreylist_save_common_mail_providers_config`.
type CPGreyListSaveCommonMailProvidersConfigArgs struct {
	// Whether Greylisting automatically trusts new mail providers that cPanel adds to the common mail providers list.
	//
	// * `1` — Automatically trust new mail providers cPanel adds to the common mail providers list.
	// * `0` — Do **not** automatically trust new mail providers cPanel adds to the common mail providers list.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `1`.
	AutotrustNewCommonMailProviders *int64 `cpanel:"autotrust_new_common_mail_providers,omitempty"`

	// Whether Greylisting automatically trusts new IP addresses that cPanel adds to this mail provider.
	//
	// * `1` — Automatically trust new IP addresses cPanel adds to this mail provider.
	// * `0` — Do **not** automatically trust new IP addresses cPanel adds to this mail provider.
	//
	// If you do not specify this parameter, the system will **not** change Greylisting settings for **any** existing provider.
	//
	// **Note:**
	//
	//  The parameter's name is the provider's key name.
	//  Example key and value:
	//  * `google=0` …
	ProviderKey *int64 `cpanel:"PROVIDERKEY,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CPGreyListSaveCommonMailProvidersConfig calls the WHM API 1 function `cpgreylist_save_common_mail_providers_config` — Update Greylisting new mail provider handling
//
// This function sets whether Greylisting trusts new entries to cPanel's common mail providers list.
//
// Available since cPanel & WHM version 11.52.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListSaveCommonMailProvidersConfig(ctx context.Context, args *CPGreyListSaveCommonMailProvidersConfigArgs) (*cpanel.WHMResult[CPGreyListSaveCommonMailProvidersConfigData], error) {
	return cpanel.WHMCall[CPGreyListSaveCommonMailProvidersConfigData](ctx, c.c, http.MethodGet, "cpgreylist_save_common_mail_providers_config", args)
}

// An object containing the provider's data.
//
// **Note:**
//
//	The object's name is the provider's key name.
type CPGreyListSaveCommonMailProvidersConfigDataCommonMailProvidersValue struct {
	// Whether Greylisting automatically trusts new IP addresses that WebPros International, LLC adds for this mail provider.
	//
	// * `1` - New IP addresses are automatically trusted.
	// * `0` - New IP addresses are **not** automatically trusted.
	//
	// Possible values: `0`, `1`.
	AutoUpdate int64 `json:"autoupdate"`

	// The mail provider's name.
	DisplayName string `json:"display_name"`

	// Whether Greylisting trusts this mail provider's IP addresses.
	//
	// * `1` - The provider is trusted.
	// * `0` - The provider is **not** trusted.
	//
	// Possible values: `0`, `1`.
	IsTrusted int64 `json:"is_trusted"`
}

// CPGreyListSaveCommonMailProvidersConfigData is a generated payload type.
type CPGreyListSaveCommonMailProvidersConfigData struct {
	// Whether Greylisting automatically trusts new mail providers that WebPros International, LLC adds to the common mail providers list.
	//
	// * `1` - New mail providers are automatically trusted.
	// * `0` - New mail providers are **not** automatically trusted.
	//
	// Possible values: `0`, `1`.
	AutotrustNewCommonMailProviders int64 `json:"autotrust_new_common_mail_providers"`

	// An object containing common mail provider settings.
	CommonMailProviders map[string]CPGreyListSaveCommonMailProvidersConfigDataCommonMailProvidersValue `json:"common_mail_providers"`
}

// CPGreyListStatus calls the WHM API 1 function `cpgreylist_status` — Return Greylisting status
//
// This function returns the status of Greylisting.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListStatus(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[CPGreyListStatusData], error) {
	return cpanel.WHMCall[CPGreyListStatusData](ctx, c.c, http.MethodGet, "cpgreylist_status", cpanel.CombineArgs(extra...))
}

// CPGreyListStatusData is a generated payload type.
type CPGreyListStatusData struct {
	// Whether Greylisting is enabled.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	IsEnabled int64 `json:"is_enabled"`

	// Whether Exim is enabled.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	IsEximEnabled int64 `json:"is_exim_enabled"`

	// The name of the service.
	Service string `json:"service"`
}

// CPGreyListTrustEntriesForCommonMailProviderArgs are the parameters of the WHM API 1 function `cpgreylist_trust_entries_for_common_mail_provider`.
type CPGreyListTrustEntriesForCommonMailProviderArgs struct {
	// The mail providers’ names.
	//
	// Call the `cpgreylist_load_common_mail_providers_config` API function
	// to retrieve the system’s recognized provider names.
	//
	// **Note:**
	//
	//  To trust multiple mail providers, increment the parameter name (for example: `provider-0`, `provider-1`, and `provider-2`).
	//
	// This parameter is required.
	Provider string `cpanel:"provider"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CPGreyListTrustEntriesForCommonMailProvider calls the WHM API 1 function `cpgreylist_trust_entries_for_common_mail_provider` — Add mail provider to Greylisting trusted hosts
//
// This function marks the IP addresses for the specified mail provider as trusted. Greylisting will not defer emails from trusted IP addresses.
//
// Available since cPanel & WHM version 11.52.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListTrustEntriesForCommonMailProvider(ctx context.Context, args *CPGreyListTrustEntriesForCommonMailProviderArgs) (*cpanel.WHMResult[CPGreyListTrustEntriesForCommonMailProviderData], error) {
	return cpanel.WHMCall[CPGreyListTrustEntriesForCommonMailProviderData](ctx, c.c, http.MethodGet, "cpgreylist_trust_entries_for_common_mail_provider", args)
}

// The providers whose configuration changes succeeded.
//
// **Note:**
//
// The property’s keys are the provider name.
type CPGreyListTrustEntriesForCommonMailProviderDataProvidersTrustedValue struct {
	// The total number of the mail provider's IP addresses that Greylisting trusts.
	IPsTrusted int64 `json:"ips_trusted"`
}

// CPGreyListTrustEntriesForCommonMailProviderData is a generated payload type.
type CPGreyListTrustEntriesForCommonMailProviderData struct {
	// The providers whose configuration changes failed.
	ProvidersFailed map[string]string `json:"providers_failed"`

	// The mail providers that Greylisting trusts.
	ProvidersTrusted map[string]CPGreyListTrustEntriesForCommonMailProviderDataProvidersTrustedValue `json:"providers_trusted"`
}

// CPGreyListUntrustEntriesForCommonMailProviderArgs are the parameters of the WHM API 1 function `cpgreylist_untrust_entries_for_common_mail_provider`.
type CPGreyListUntrustEntriesForCommonMailProviderArgs struct {
	// The mail provider.
	//
	// **Note:**
	//
	// To trust multiple mail providers,
	//  increment the parameter name. For example, provider-0, provider-1, provider-2.
	//
	// This parameter is required.
	Provider string `cpanel:"provider"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CPGreyListUntrustEntriesForCommonMailProvider calls the WHM API 1 function `cpgreylist_untrust_entries_for_common_mail_provider` — Add mail provider to Greylisting non-trusted hosts
//
// This function marks the IP addresses for the specified mail provider as not trusted.
// Greylisting defers emails from non-trusted IP addresses.
//
// Available since cPanel & WHM version 11.52.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CPGreyListUntrustEntriesForCommonMailProvider(ctx context.Context, args *CPGreyListUntrustEntriesForCommonMailProviderArgs) (*cpanel.WHMResult[CPGreyListUntrustEntriesForCommonMailProviderData], error) {
	return cpanel.WHMCall[CPGreyListUntrustEntriesForCommonMailProviderData](ctx, c.c, http.MethodGet, "cpgreylist_untrust_entries_for_common_mail_provider", args)
}

// The mail provider's data.
type CPGreyListUntrustEntriesForCommonMailProviderDataProvidersFailedValue struct {
	// The mail providers that failed to update.
	IPsUntrusted int64 `json:"ips_untrusted"`
}

// CPGreyListUntrustEntriesForCommonMailProviderData is a generated payload type.
type CPGreyListUntrustEntriesForCommonMailProviderData struct {
	ProvidersFailed map[string]CPGreyListUntrustEntriesForCommonMailProviderDataProvidersFailedValue `json:"providers_failed"`

	// The mail providers that Greylisting does not trust.
	ProvidersUntrusted map[string]string `json:"providers_untrusted"`
}

// CreateCPGreyListTrustedHostArgs are the parameters of the WHM API 1 function `create_cpgreylist_trusted_host`.
type CreateCPGreyListTrustedHostArgs struct {
	// The record's IP address, or a range of IP addresses.
	//
	// **Note:**
	//
	// To add multiple IP addresses, increment the parameter name. For example, `ip-1`, `ip-2`, and `ip-3`.
	//
	// This parameter is required.
	IP string `cpanel:"ip"`

	// A comment.
	Comment *string `cpanel:"comment,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// CreateCPGreyListTrustedHost calls the WHM API 1 function `create_cpgreylist_trusted_host` — Add IP address to Greylisting trusted hosts
//
// This function adds an IP address to the *Greylisting Trusted Hosts* list.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) CreateCPGreyListTrustedHost(ctx context.Context, args *CreateCPGreyListTrustedHostArgs) (*cpanel.WHMResult[CreateCPGreyListTrustedHostData], error) {
	return cpanel.WHMCall[CreateCPGreyListTrustedHostData](ctx, c.c, http.MethodGet, "create_cpgreylist_trusted_host", args)
}

// CreateCPGreyListTrustedHostDataIPsAddedItem is a generated payload type.
type CreateCPGreyListTrustedHostDataIPsAddedItem struct {
	// Comment for the individual record.
	Comment string `json:"comment"`

	// The date and time at which the function created the record.
	CreateTime string `json:"create_time"`

	// The trusted host's IP address.
	HostIP string `json:"host_ip"`

	// The host's record number.
	ID int64 `json:"id"`
}

// An object that contains the IP addresses that the function failed to add to the Trusted Hosts list.
type CreateCPGreyListTrustedHostDataIPsFailed struct {
	// The reason for the failure.
	Comment string `json:"comment"`
}

// CreateCPGreyListTrustedHostData is a generated payload type.
type CreateCPGreyListTrustedHostData struct {
	// Comment for the batch.
	Comment string `json:"comment"`

	// An array of objects that contains the IP addresses that the function added to the Trusted Hosts list.
	IPsAdded []CreateCPGreyListTrustedHostDataIPsAddedItem `json:"ips_added"`

	// An object that contains the IP addresses that the function failed to add to the Trusted Hosts list.
	IPsFailed CreateCPGreyListTrustedHostDataIPsFailed `json:"ips_failed"`
}

// DeleteCPGreyListTrustedHostArgs are the parameters of the WHM API 1 function `delete_cpgreylist_trusted_host`.
type DeleteCPGreyListTrustedHostArgs struct {
	// The record's IP address, or a range of IP addresses.
	//
	// **Note:**
	//
	// To add multiple IP addresses, increment the parameter name (for example, `ip-1`, `ip-2`, `ip-3`).
	//
	// This parameter is required.
	IP string `cpanel:"ip"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// DeleteCPGreyListTrustedHost calls the WHM API 1 function `delete_cpgreylist_trusted_host` — Remove IP address from Greylisting trusted hosts
//
// This function deletes an IP address from the Greylisting _Trusted Hosts_ list.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) DeleteCPGreyListTrustedHost(ctx context.Context, args *DeleteCPGreyListTrustedHostArgs) (*cpanel.WHMResult[DeleteCPGreyListTrustedHostData], error) {
	return cpanel.WHMCall[DeleteCPGreyListTrustedHostData](ctx, c.c, http.MethodGet, "delete_cpgreylist_trusted_host", args)
}

// DeleteCPGreyListTrustedHostData is a generated payload type.
type DeleteCPGreyListTrustedHostData struct {
	// An object that contains the IP addresses that the function failed to remove from the _Trusted Hosts_ list.
	IPsFailed map[string]string `json:"ips_failed"`

	// An array of IP addresses that the function removed from the _Trusted Hosts_ list.
	IPsRemoved []string `json:"ips_removed"`
}

// DisableCPGreyList calls the WHM API 1 function `disable_cpgreylist` — Disable Greylisting
//
// This function disables Greylisting.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) DisableCPGreyList(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "disable_cpgreylist", cpanel.CombineArgs(extra...))
}

// EnableCPGreyList calls the WHM API 1 function `enable_cpgreylist` — Enable Greylisting
//
// This function enables Greylisting.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) EnableCPGreyList(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "enable_cpgreylist", cpanel.CombineArgs(extra...))
}

// LoadCPGreyListConfig calls the WHM API 1 function `load_cpgreylist_config` — Return Greylisting settings
//
// This function returns Greylisting's current settings.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) LoadCPGreyListConfig(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[LoadCPGreyListConfigData], error) {
	return cpanel.WHMCall[LoadCPGreyListConfigData](ctx, c.c, http.MethodGet, "load_cpgreylist_config", cpanel.CombineArgs(extra...))
}

// An object that contains Greylisting settings.
type LoadCPGreyListConfigDataCPGreyListConfig struct {
	// The maximum amount of seconds that Greylisting waits for a child process to time out.
	ChildTimeoutSecs int64 `json:"child_timeout_secs"`

	// The number of minutes during which Greylisting defers email from an unknown triplet.
	InitialBlockTimeMins int64 `json:"initial_block_time_mins"`

	// Whether Greylisting is enabled.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	IsEnabled int64 `json:"is_enabled"`

	// Whether Exim is enabled.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	IsEximEnabled int64 `json:"is_exim_enabled"`

	// The maximum amount of child processes.
	MaxChildProcs int64 `json:"max_child_procs"`

	// The number of minutes during which Greylisting accepts a re-sent email from an unknown triplet.
	MustTryTimeMins int64 `json:"must_try_time_mins"`

	// The number of minutes before Greylisting deletes the records in the Greylisting database.
	PurgeIntervalMins int64 `json:"purge_interval_mins"`

	// The number of minutes before Greylisting deletes the triplet record and treats a re-sent email as a new, unknown triplet.
	RecordExpTimeMins int64 `json:"record_exp_time_mins"`

	// Whether emails with SPF bypass Greylisting.
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `0`, `1`.
	SPFBypass int64 `json:"spf_bypass"`
}

// LoadCPGreyListConfigData is a generated payload type.
type LoadCPGreyListConfigData struct {
	// An object that contains Greylisting settings.
	CPGreyListConfig LoadCPGreyListConfigDataCPGreyListConfig `json:"cpgreylist_config"`
}

// ReadCPGreyListDeferredEntries calls the WHM API 1 function `read_cpgreylist_deferred_entries` — Return Greylisting deferred incoming email triplets
//
// This function lists Greylisting's deferred triplets.
// Greylisting identifies incoming email by triplets.
//
// A triplet is a collection of three pieces of data:
// * the IP address
// * the sender's address
// * the recipient's address
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) ReadCPGreyListDeferredEntries(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ReadCPGreyListDeferredEntriesData], error) {
	return cpanel.WHMCall[ReadCPGreyListDeferredEntriesData](ctx, c.c, http.MethodGet, "read_cpgreylist_deferred_entries", cpanel.CombineArgs(extra...))
}

// ReadCPGreyListDeferredEntriesDataGreylistDeferredEntriesItem is a generated payload type.
type ReadCPGreyListDeferredEntriesDataGreylistDeferredEntriesItem struct {
	// The number of times that Greylisting accepted the triplet.
	AcceptedCount int64 `json:"accepted_count"`

	// The date and time when Greylisting will no longer defer the triplet.
	BlockExpTime string `json:"block_exp_time"`

	// The date and time when Greylisting created the triplet.
	CreateTime string `json:"create_time"`

	// The number of times Greylisting deferred the triplet.
	DeferredCount int64 `json:"deferred_count"`

	// The email address that the system identified as the triplet's sender.
	FromAddr string `json:"from_addr"`

	// The identification number that the system assigned to the triplet.
	ID int64 `json:"id"`

	// The date and time when Greylisting will no longer accept the resent triplet.
	MustRetryBy string `json:"must_retry_by"`

	// The date and time when Greylisting will purge the triplet from the database.
	RecordExpTime string `json:"record_exp_time"`

	// The IP address that the system identified as the triplet's sender.
	SenderIP string `json:"sender_ip"`

	// The email address that the system identified as the triplet's recipient.
	ToAddr string `json:"to_addr"`
}

// ReadCPGreyListDeferredEntriesData is a generated payload type.
type ReadCPGreyListDeferredEntriesData struct {
	// An object of deferred triplet data.
	GreylistDeferredEntries []ReadCPGreyListDeferredEntriesDataGreylistDeferredEntriesItem `json:"greylist_deferred_entries"`

	// The number of triplets in the interface.
	Limit int64 `json:"limit"`

	// The number of triplets to skip from the beginning of the query in the interface.
	Offset int64 `json:"offset"`

	// The standard letter code abbreviation for the time zone.
	ServerTimezone string `json:"server_timezone"`

	// The time zone offset in minutes.
	ServerTzoffset int64 `json:"server_tzoffset"`

	// The total number of triplets in the database.
	TotalRows int64 `json:"total_rows"`
}

// ReadCPGreyListTrustedHosts calls the WHM API 1 function `read_cpgreylist_trusted_hosts` — Return Greylisting trusted hosts
//
// This function retrieves the entries on the Greylisting Trusted Hosts list.
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) ReadCPGreyListTrustedHosts(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ReadCPGreyListTrustedHostsData], error) {
	return cpanel.WHMCall[ReadCPGreyListTrustedHostsData](ctx, c.c, http.MethodGet, "read_cpgreylist_trusted_hosts", cpanel.CombineArgs(extra...))
}

// ReadCPGreyListTrustedHostsDataGreylistTrustedHostsItem is a generated payload type.
type ReadCPGreyListTrustedHostsDataGreylistTrustedHostsItem struct {
	// The IP address' comment.
	Comment string `json:"comment"`

	// The date and time when the system added the IP address to the _Trusted Hosts_ list.
	CreateTime string `json:"create_time"`

	// The IP address of the host that the system added to the _Trusted Hosts_ list.
	HostIP string `json:"host_ip"`

	// The identification number that the system assigned to the IP address.
	ID int64 `json:"id"`
}

// ReadCPGreyListTrustedHostsData is a generated payload type.
type ReadCPGreyListTrustedHostsData struct {
	// An array of objects that contain identification information for the trusted hosts.
	GreylistTrustedHosts []ReadCPGreyListTrustedHostsDataGreylistTrustedHostsItem `json:"greylist_trusted_hosts"`
}

// SaveCPGreyListConfigArgs are the parameters of the WHM API 1 function `save_cpgreylist_config`.
type SaveCPGreyListConfigArgs struct {
	// The maximum of seconds that Greylisting waits for a child process to timeout.
	//
	// **Note:**
	//
	// This parameter affects the function of the `cPGreyList` daemon. Do **not** change this
	// value unless it is absolutely necessary.
	ChildTimeoutSecs *int64 `cpanel:"child_timeout_secs,omitempty"`

	// The number of minutes during which Greylisting defers email from an unknown triplet. The maximum value for this parameter is four hours (`240` minutes).
	InitialBlockTimeMins *int64 `cpanel:"initial_block_time_mins,omitempty"`

	// The maximum number of child processes.
	//
	// **Notes:**
	//
	//  This parameter affects the function of the `cPGreyList` daemon. Do **not** change this
	//  value unless it is absolutely necessary.
	MaxChildProcs *int64 `cpanel:"max_child_procs,omitempty"`

	// The number of minutes during which Greylisting accepts a re-sent email from an unknown triplet. The maximum value for this parameter is one day (`1440` minutes).
	MustTryTimeMins *int64 `cpanel:"must_try_time_mins,omitempty"`

	// The number of minutes before Greylisting deletes the records in the Greylisting database.
	//
	// **Note:**
	//
	// This parameter affects the function of the `cPGreyList` daemon. Do **not** change this
	// value unless it is absolutely necessary.
	PurgeIntervalMins *int64 `cpanel:"purge_interval_mins,omitempty"`

	// The number of minutes before Greylisting deletes the triplet record and treats a
	// re-sent email as coming from a new, unknown triplet. The maximum value for this
	// parameter is 30 days (`43200` minutes).
	RecordExpTimeMins *int64 `cpanel:"record_exp_time_mins,omitempty"`

	// Whether emails with SPF bypass Greylisting.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `1`, `0`.
	SPFBypass *int64 `cpanel:"spf_bypass,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SaveCPGreyListConfig calls the WHM API 1 function `save_cpgreylist_config` — Update Greylisting settings
//
// This function modifies the server's Greylisting configuration settings.
//
// **Important:**
//
// When you call this function, you **must** include at least one of the
// following parameters:
//
// * `spf_bypass`
// * `child_timeout_secs`
// * `record_exp_time_mins`
// * `initial_block_time_mins`
// * `max_child_procs`
// * `purge_interval_mins`
// * `must_try_time_mins`
//
// Available since cPanel & WHM version 11.50.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/spam-protection-(greylisting
func (c *Client) SaveCPGreyListConfig(ctx context.Context, args *SaveCPGreyListConfigArgs) (*cpanel.WHMResult[SaveCPGreyListConfigData], error) {
	return cpanel.WHMCall[SaveCPGreyListConfigData](ctx, c.c, http.MethodGet, "save_cpgreylist_config", args)
}

// A list of Greylisting settings.
type SaveCPGreyListConfigDataCPGreyListConfig struct {
	// The maximum amount of seconds that Greylisting waits for child process to time out.
	ChildTimeoutSecs int64 `json:"child_timeout_secs"`

	// The number of minutes during which Greylisting defers email from an unknown triplet.
	InitialBlockTimeMins int64 `json:"initial_block_time_mins"`

	// Whether Greylisting is enabled.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `1`, `0`.
	IsEnabled int64 `json:"is_enabled"`

	// Whether Exim is enabled.
	//
	// * `1` — Enabled.
	// * `0` — Disabled.
	//
	// Possible values: `1`, `0`.
	IsEximEnabled int64 `json:"is_exim_enabled"`

	// The maximum amount of child processes.
	MaxChildProcs int64 `json:"max_child_procs"`

	// The number of minutes during which Greylisting accepts a re-sent email from an unknown triplet.
	MustTryTimeMins int64 `json:"must_try_time_mins"`

	// The number of minutes before Greylisting deletes the records in the Greylisting database.
	PurgeIntervalMins int64 `json:"purge_interval_mins"`

	// The number of minutes before Greylisting deletes the triplet record and treats a re-sent email as a new, unknown triplet.
	RecordExpTimeMins int64 `json:"record_exp_time_mins"`

	// Whether emails with SPF bypass Greylisting.
	//
	// * `1` — Bypass.
	// * `0` — Do **not** bypass.
	//
	// Possible values: `1`, `0`.
	SPFBypass int64 `json:"spf_bypass"`
}

// SaveCPGreyListConfigData is a generated payload type.
type SaveCPGreyListConfigData struct {
	// A list of Greylisting settings.
	CPGreyListConfig SaveCPGreyListConfigDataCPGreyListConfig `json:"cpgreylist_config"`
}
