// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// AcctCountsArgs are the parameters of the WHM API 1 function `acctcounts`.
type AcctCountsArgs struct {
	// A reseller's username, to query that reseller. If you do not specify a value, the function lists information for the authenticated account.
	User *string `cpanel:"user,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// AcctCounts calls the WHM API 1 function `acctcounts` — Return reseller's owned accounts' information
//
// This function lists a reseller's total accounts, suspended accounts, and account creation limit.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-acctcounts.md
func (c *Client) AcctCounts(ctx context.Context, args *AcctCountsArgs) (*cpanel.WHMResult[AcctCountsData], error) {
	return cpanel.WHMCall[AcctCountsData](ctx, c.c, http.MethodGet, "acctcounts", args)
}

// An object that contains information for an account.
type AcctCountsDataReseller struct {
	// The number of active accounts that the reseller account owns.
	Active int64 `json:"active"`

	// The maximum number of accounts that the reseller account may create, if a maximum exists.
	//
	// **NOTE:**
	//
	// A null value indicates that the reseller does not have an account creation limit.
	Limit *int64 `json:"limit"`

	// The number of suspended accounts that the reseller account owns.
	Suspended *int64 `json:"suspended"`

	// The reseller account's username or the `root` user.
	User string `json:"user"`
}

// AcctCountsData is a generated payload type.
type AcctCountsData struct {
	// An object that contains information for an account.
	Reseller AcctCountsDataReseller `json:"reseller"`
}

// GetPublicContact calls the WHM API 1 function `get_public_contact` — Return current user's public contact information
//
// This function retrieves an account's [public contact information](https://docs.cpanel.net/whm/cpanel/customization/#public-contact).
//
// Available since cPanel & WHM version 68.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/publiccontact-get_public_contact.md
func (c *Client) GetPublicContact(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[GetPublicContactData], error) {
	return cpanel.WHMCall[GetPublicContactData](ctx, c.c, http.MethodGet, "get_public_contact", cpanel.CombineArgs(extra...))
}

// GetPublicContactData is a generated payload type.
type GetPublicContactData struct {
	// The public contact name of the reseller.
	Name string `json:"name"`

	// The public contact URL.
	URL string `json:"url"`
}

// GetResellerIPsArgs are the parameters of the WHM API 1 function `getresellerips`.
type GetResellerIPsArgs struct {
	// A reseller's username, to query only that reseller.
	//
	// **Note:**
	//
	// If you do **not** specify a value, the function lists available IP addresses for the `root`
	// user.
	User *string `cpanel:"user,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// GetResellerIPs calls the WHM API 1 function `getresellerips` — Return reseller's available IP addresses
//
// This function lists a reseller's available IP addresses.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-getresellerips.md
func (c *Client) GetResellerIPs(ctx context.Context, args *GetResellerIPsArgs) (*cpanel.WHMResult[GetResellerIPsData], error) {
	return cpanel.WHMCall[GetResellerIPsData](ctx, c.c, http.MethodGet, "getresellerips", args)
}

// GetResellerIPsData is a generated payload type.
type GetResellerIPsData struct {
	// Whether all of the reseller's IP addresses are available.
	// * `1` — All of the reseller's IP addresses are available.
	// * `0` — Some or all IP addresses are unavailable.
	//
	// Possible values: `0`, `1`.
	All int64 `json:"all"`

	// The reseller's available IP addresses.
	IP []string `json:"ip"`
}

// ListEnhancementLimitsArgs are the parameters of the WHM API 1 function `list_enhancement_limits`.
type ListEnhancementLimitsArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ListEnhancementLimits calls the WHM API 1 function `list_enhancement_limits` — Return account enhancement limits
//
// This function returns a reseller's account enhancement limits.
//
// Available since cPanel & WHM version 11.98.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-enhancement-limit/accountenhancements-list_enhancement_limits.md
func (c *Client) ListEnhancementLimits(ctx context.Context, args *ListEnhancementLimitsArgs) (*cpanel.WHMResult[ListEnhancementLimitsData], error) {
	return cpanel.WHMCall[ListEnhancementLimitsData](ctx, c.c, http.MethodGet, "list_enhancement_limits", args)
}

// The reseller's limit for the account enhancement.
type ListEnhancementLimitsDataLimitsValue struct {
	// The assignment limit amount.
	Limit int64 `json:"limit"`

	// Whether the assignment limit is unlimited.
	//
	// Possible values: `1`, `0`.
	Limited int64 `json:"limited"`

	// The total of cPanel accounts that have the specified Account Enhancement.
	Usage int64 `json:"usage"`
}

// ListEnhancementLimitsData is a generated payload type.
type ListEnhancementLimitsData struct {
	Limits map[string]ListEnhancementLimitsDataLimitsValue `json:"limits"`
}

// Listacls calls the WHM API 1 function `listacls` — Return all privilege lists and settings
//
// This function lists the server's
// [Access Control Lists (ACLs)](https://go.cpanel.net/GuidetoWHMPluginsAccessControlLists)
// and each list's privileges.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-permissions/acls-listacls.md
func (c *Client) Listacls(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ListaclsData], error) {
	return cpanel.WHMCall[ListaclsData](ctx, c.c, http.MethodGet, "listacls", cpanel.CombineArgs(extra...))
}

// A list of ACL privileges, including any third-party ACL privileges
// that exist for the user.
type ListaclsDataAclItemPrivileges struct {
	// Whether to allow the reseller to view an account summary.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AcctSummary int64 `json:"acct-summary"`

	// Whether to allow the reseller to add and remove hosting plans
	// (packages).
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AddPkg int64 `json:"add-pkg"`

	// Whether to allow the reseller to create packages with a
	// dedicated IP address.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AddPkgIP int64 `json:"add-pkg-ip"`

	// Whether to allow the reseller to create packages with shell
	// access.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AddPkgShell int64 `json:"add-pkg-shell"`

	// Whether to grant the reseller **all** ACL privileges.
	//
	// **Warning:**
	//
	// A value of `1` grants `root`-level privileges to the reseller.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	All int64 `json:"all"`

	// Whether to allow the reseller to create packages with addon
	// domains.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowAddoncreate int64 `json:"allow-addoncreate"`

	// Whether to allow the reseller to create packages with email quotas
	// that are **not** the default quotas.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowEmaillimitsPkgs int64 `json:"allow-emaillimits-pkgs"`

	// Whether to allow the reseller to create packages with parked
	// domains (aliases).
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowParkedcreate int64 `json:"allow-parkedcreate"`

	// Whether to allow the reseller to create accounts with shell
	// access.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowShell int64 `json:"allow-shell"`

	// Whether to allow the reseller to create packages with unlimited
	// bandwidth.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowUnlimitedBwPkgs int64 `json:"allow-unlimited-bw-pkgs"`

	// Whether to allow the reseller to create packages with unlimited
	// disk space.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowUnlimitedDiskPkgs int64 `json:"allow-unlimited-disk-pkgs"`

	// Whether to allow the reseller to create packages with unlimited
	// features.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	AllowUnlimitedPkgs int64 `json:"allow-unlimited-pkgs"`

	// Whether to allow the user to retrieve basic system information.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	BasicSystemInfo int64 `json:"basic-system-info"`

	// Whether to allow the reseller to access basic cPanel & WHM
	// options.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	BasicWHMFunctions int64 `json:"basic-whm-functions"`

	// Whether to allow the reseller to use DNS clusters.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Clustering int64 `json:"clustering"`

	// Whether to allow the reseller to perform Cross-Origin Resource
	// Sharing (CORS) HTTP requests.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	CorsProxyGet int64 `json:"cors-proxy-get"`

	// Whether to allow the reseller to execute cPanel API 1, cPanel
	// API 2 and UAPI functions via WHM.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	CpanelAPI int64 `json:"cpanel-api"`

	// Whether to allow the reseller to manage cPanel integration
	// links.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	CpanelIntegration int64 `json:"cpanel-integration"`

	// Whether to allow the reseller to create accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	CreateAcct int64 `json:"create-acct"`

	// Whether to allow the reseller to add DNS zones.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	CreateDNS int64 `json:"create-dns"`

	// Whether to allow the reseller to create a new temporary user
	// session for a specified service.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Note:**
	//
	// This ACL privilege allows an API token user to bypass any
	// restrictions that you set on the API token. For more information,
	// read our
	// [Manage API Tokens](https://go.cpanel.net/ManageAPITokens)
	// documentation.
	//
	// Possible values: `1`, `0`.
	CreateUserSession int64 `json:"create-user-session"`

	// Whether to allow the reseller to enable demo mode for accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	DemoSetup int64 `json:"demo-setup"`

	// Whether to allow the reseller to manage Digest Authentication.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	DigestAuth int64 `json:"digest-auth"`

	// Whether to allow the reseller to edit accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	EditAccount int64 `json:"edit-account"`

	// Whether to allow the reseller to edit DNS zones.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	EditDNS int64 `json:"edit-dns"`

	// Whether to allow the reseller to edit MX entries.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	EditMX int64 `json:"edit-mx"`

	// Whether to allow the reseller to edit hosting plans (packages).
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	EditPkg int64 `json:"edit-pkg"`

	// Whether to allow the reseller to manage Microsoft® FrontPage®
	// Extensions.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Note:**
	//
	// cPanel & WHM ignores all Microsoft FrontPage settings and parameters.
	//
	// Possible values: `1`, `0`.
	FrontPage int64 `json:"frontpage"`

	// Whether to allow the reseller to generate a mobile configuration
	// profile for an email account.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	GenerateEmailConfig int64 `json:"generate-email-config"`

	// Whether to allow the reseller to terminate accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	KillAcct int64 `json:"kill-acct"`

	// Whether to allow the reseller to remove DNS zones.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	KillDNS int64 `json:"kill-dns"`

	// Whether to allow the reseller to modify bandwidth limits
	// (quotas).
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Warning:**
	//
	// If you do not use resource limits, a value of `1` allows
	// resellers to circumvent package limits for disk space.
	//
	// Possible values: `1`, `0`.
	LimitBandwidth int64 `json:"limit-bandwidth"`

	// Whether to allow the reseller to view the list of accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ListAccts int64 `json:"list-accts"`

	// Whether to allow the reseller to view existing hosting plans.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ListPkgs int64 `json:"list-pkgs"`

	// Whether to allow the reseller to create and modify locales on
	// the server.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	LocaleEdit int64 `json:"locale-edit"`

	// Whether to allow the reseller to troubleshoot mail delivery.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Mailcheck int64 `json:"mailcheck"`

	// Whether to allow the reseller to manage API tokens.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Note:**
	//
	// This ACL privilege allows an API token user to bypass any
	// restrictions that you set on the API token. For more information,
	// read our
	// [Manage API Tokens](https://go.cpanel.net/ManageAPITokens)
	// documentation.
	//
	// Possible values: `1`, `0`.
	ManageAPITokens int64 `json:"manage-api-tokens"`

	// Whether to allow the reseller to manage DNS records.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ManageDNSRecords int64 `json:"manage-dns-records"`

	// Whether to allow the reseller to manage external authentication
	// for their accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ManageOidc int64 `json:"manage-oidc"`

	// Whether to allow the reseller to manage their server's cPanel
	// styles.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ManageStyles int64 `json:"manage-styles"`

	// Whether to allow the reseller to retrieve MySQL® database and
	// user data.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	MysqlInfo int64 `json:"mysql-info"`

	// Whether to allow the reseller to modify the server's news.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	News int64 `json:"news"`

	// Whether to allow the reseller to manage nameserver records.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	NSConfig int64 `json:"ns-config"`

	// Whether to allow the reseller to park DNS zones.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ParkDNS int64 `json:"park-dns"`

	// Whether to allow the reseller to change passwords.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Note:**
	//
	// This privilege allows an API token user to change account
	// passwords and log in with a new password. For more information,
	// read our
	// [Manage API Tokens](https://go.cpanel.net/ManageAPITokens)
	// documentation.
	//
	// Possible values: `1`, `0`.
	Passwd int64 `json:"passwd"`

	// Whether to allow the reseller to modify quotas.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// **Warning:**
	//
	// If you do not use resource limits, a value of `1`
	// allows resellers to circumvent package limits for disk space.
	//
	// Possible values: `1`, `0`.
	Quota int64 `json:"quota"`

	// Whether to allow the reseller to rearrange accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	RearrangeAccts int64 `json:"rearrange-accts"`

	// Whether to allow the reseller to resync FTP passwords.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Resftp int64 `json:"resftp"`

	// Whether to allow the reseller to restart services.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Restart int64 `json:"restart"`

	// Whether to allow the reseller to view account bandwidth usage.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ShowBandwidth int64 `json:"show-bandwidth"`

	// Whether to allow the reseller to perform SSL site management.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	SSL int64 `json:"ssl"`

	// Whether to allow the reseller to purchase SSL certificates.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	SSLBuy int64 `json:"ssl-buy"`

	// Whether to allow the reseller to generate SSL certificates.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	SSLGencrt int64 `json:"ssl-gencrt"`

	// Whether to allow the reseller to view their server's SSL
	// information.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	SSLInfo int64 `json:"ssl-info"`

	// Whether to allow the reseller to view server information.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Stats int64 `json:"stats"`

	// Whether to allow the reseller to view the server's status.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Status int64 `json:"status"`

	// Whether to allow the reseller to suspend or unsuspend accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	SuspendAcct int64 `json:"suspend-acct"`

	// Whether to allow the reseller to manage third-party services.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	Thirdparty int64 `json:"thirdparty"`

	// Whether to allow resellers to view reports about email message
	// delivery attempts from their account.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	TrackEmail int64 `json:"track-email"`

	// Whether to allow the reseller to upgrade or downgrade accounts.
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	UpgradeAccount int64 `json:"upgrade-account"`

	// Whether to allow the reseller to use all
	// [global packages](https://go.cpanel.net/resellerpackages).
	//
	// * `1` — Allow.
	// * `0` — Do not allow.
	//
	// Possible values: `1`, `0`.
	ViewGlobalPackages int64 `json:"viewglobalpackages"`
}

// ListaclsDataAclItem is a generated payload type.
type ListaclsDataAclItem struct {
	// The ACL's name.
	Name string `json:"name"`

	// A list of ACL privileges, including any third-party ACL privileges
	// that exist for the user.
	Privileges ListaclsDataAclItemPrivileges `json:"privileges"`
}

// ListaclsData is a generated payload type.
type ListaclsData struct {
	// An array of objects containing ACL settings.
	Acl []ListaclsDataAclItem `json:"acl"`
}

// ListResellers calls the WHM API 1 function `listresellers` — Return all resellers
//
// This function lists the reseller accounts on the server.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-listresellers.md
func (c *Client) ListResellers(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ListResellersData], error) {
	return cpanel.WHMCall[ListResellersData](ctx, c.c, http.MethodGet, "listresellers", cpanel.CombineArgs(extra...))
}

// ListResellersData is a generated payload type.
type ListResellersData struct {
	// An array of the server's reseller accounts.
	Reseller []string `json:"reseller"`
}

// ResellerStatsArgs are the parameters of the WHM API 1 function `resellerstats`.
type ResellerStatsArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Do not display the reseller's deleted cPanel accounts in the function's `acct` return. This parameter modifies the data output in the `acct` return.
	//
	// * `1` — Do **not** display.
	// * `0` — Display.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	FilterDeleted *int64 `cpanel:"filter_deleted,omitempty"`

	// Do not display the reseller's suspended cPanel accounts in the function's `acct` return. This parameter modifies the data output in the `acct` return.
	//
	// * `1` — Do **not** display.
	// * `0` — Display.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	FilterSuspended *int64 `cpanel:"filter_suspended,omitempty"`

	// The month to query, in numeric format.
	//
	// This parameter defaults to the current month.
	Month *int64 `cpanel:"month,omitempty"`

	// The year to query, in numeric format.
	//
	// This parameter defaults to the current year.
	Year *int64 `cpanel:"year,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// ResellerStats calls the WHM API 1 function `resellerstats` — Return reseller's information
//
// This function lists data about a reseller's accounts.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-resellerstats.md
func (c *Client) ResellerStats(ctx context.Context, args *ResellerStatsArgs) (*cpanel.WHMResult[ResellerStatsData], error) {
	return cpanel.WHMCall[ResellerStatsData](ctx, c.c, http.MethodGet, "resellerstats", args)
}

// ResellerStatsDataResellerAcctItem is a generated payload type.
type ResellerStatsDataResellerAcctItem struct {
	// The account's bandwidth limit.
	//
	// * A positive numeric value, encoded as a string, that represents the account's bandwidth limit, in megabytes (MB).
	// * `0.00` — The account has unlimited bandwidth.
	BandwidthLimit string `json:"bandwidthlimit"`

	// The account's current bandwidth use.
	// A positive numeric value, encoded as a string, that represents the account's bandwidth use, in megabytes (MB).
	BandwidthUsed string `json:"bandwidthused"`

	// Whether the account has been deleted.
	//
	// * `1` — Deleted.
	// * `0` — **Not** deleted.
	//
	// Possible values: `0`, `1`.
	Deleted int64 `json:"deleted"`

	// The account's disk space quota.
	//
	// * A positive numeric value, encoded as a string, that represents the account's disk space quota, in megabytes (MB).
	// * `0.00` — The account has unlimited disk space.
	DiskQuota string `json:"diskquota"`

	// The account's current disk space use.
	// A positive numeric value, encoded as a string, that represents the account's current disk space use, in megabytes (MB).
	Diskused string `json:"diskused"`

	// The account's main domain.
	Domain string `json:"domain"`

	// The account's hosting plan (package).
	Package2 string `json:"package"`

	// Whether the account is suspended.
	//
	// * `1` — Suspended.
	// * `0` — Not suspended.
	//
	// Possible values: `0`, `1`.
	Suspended int64 `json:"suspended"`

	// The account's username.
	User string `json:"user"`
}

// Object containing data about a reseller account.
type ResellerStatsDataReseller struct {
	// Array of objects that contains data about all of the reseller's accounts.
	//
	// **Note:**
	//
	// This array also returns the reseller account.
	Acct []ResellerStatsDataResellerAcctItem `json:"acct"`

	// The reseller's total bandwidth limit.
	//
	// * A positive integer that represents the reseller's bandwidth limit, in megabytes (MB).
	// * `0` — The reseller has unlimited bandwidth.
	BandwidthLimit int64 `json:"bandwidthlimit"`

	// Whether the reseller can oversell bandwidth.
	//
	// * `1` — The reseller can oversell bandwidth.
	// * `0` — The reseller **cannot** oversell bandwidth.
	//
	// Possible values: `0`, `1`.
	BwOverselling int64 `json:"bwoverselling"`

	// Whether the reseller can oversell disk space.
	//
	// * `1` — The reseller can oversell disk space.
	// * `0` — The reseller **cannot** oversell disk space.
	//
	// Possible values: `0`, `1`.
	DiskOverselling int64 `json:"diskoverselling"`

	// The reseller's total disk space quota.
	//
	// * A positive integer that represents the reseller's disk space quota, in megabytes (MB).
	// * `0` — The reseller has unlimited disk space.
	DiskQuota int64 `json:"diskquota"`

	// The total amount of disk space that the reseller and all of its accounts use, in megabytes (MB).
	//
	// **Note:**
	//
	// This value does not include disk space the reseller account uses if the root account owns it.
	Diskused float64 `json:"diskused"`

	// The current month or a queried month.
	Month int64 `json:"month"`

	// The total amount of bandwidth that the reseller has given to its accounts, in megabytes (MB), encoded as a string.
	TotalBWallOc string `json:"totalbwalloc"`

	// The total amount of bandwidth that the reseller's accounts have used, in megabytes (MB), encoded as a string.
	TotalBwused string `json:"totalbwused"`

	// The total amount of disk space that the reseller has given to its accounts, in megabytes (MB), encoded as a string.
	TotalDiskALLoc string `json:"totaldiskalloc"`

	// The reseller account's username.
	User string `json:"user"`

	// The current year or a queried year.
	Year int64 `json:"year"`
}

// ResellerStatsData is a generated payload type.
type ResellerStatsData struct {
	// Object containing data about a reseller account.
	Reseller ResellerStatsDataReseller `json:"reseller"`
}

// SaveAcllistArgs are the parameters of the WHM API 1 function `saveacllist`.
type SaveAcllistArgs struct {
	// The ACL to assign to the reseller.
	//
	// **Note:**
	//
	//  To modify an existing ACL, set this value to that ACL's name.
	//
	// This parameter is required.
	Acllist string `cpanel:"acllist"`

	// Whether to allow the reseller to view an account summary.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAcctSummary *int64 `cpanel:"acl-acct-summary,omitempty"`

	// Whether to allow the reseller to add and remove hosting plans (packages).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAddPkg *int64 `cpanel:"acl-add-pkg,omitempty"`

	// Whether to allow the reseller to create packages with a dedicated IP address.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAddPkgIP *int64 `cpanel:"acl-add-pkg-ip,omitempty"`

	// Whether to allow the reseller to create packages with shell access.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAddPkgShell *int64 `cpanel:"acl-add-pkg-shell,omitempty"`

	// Whether to grant the reseller all privileges.
	//
	// **Warning:**
	//
	//  A value of `1` grants root-level privileges to the reseller.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAll *int64 `cpanel:"acl-all,omitempty"`

	// Whether to allow the reseller to create packages with addon domains.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowAddoncreate *int64 `cpanel:"acl-allow-addoncreate,omitempty"`

	// Whether to allow the reseller to create packages with custom email quotas.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowEmaillimitsPkgs *int64 `cpanel:"acl-allow-emaillimits-pkgs,omitempty"`

	// Whether to allow the reseller to create packages with parked domains (aliases).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowParkedcreate *int64 `cpanel:"acl-allow-parkedcreate,omitempty"`

	// Whether to allow the reseller to create accounts with shell access.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowShell *int64 `cpanel:"acl-allow-shell,omitempty"`

	// Whether to allow the reseller to create packages with unlimited bandwidth.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowUnlimitedBwPkgs *int64 `cpanel:"acl-allow-unlimited-bw-pkgs,omitempty"`

	// Whether to allow the reseller to create packages with unlimited disk space.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowUnlimitedDiskPkgs *int64 `cpanel:"acl-allow-unlimited-disk-pkgs,omitempty"`

	// Whether to allow the reseller to create packages with unlimited features.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclAllowUnlimitedPkgs *int64 `cpanel:"acl-allow-unlimited-pkgs,omitempty"`

	// Whether to allow the reseller to retrieve basic system information.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclBasicSystemInfo *int64 `cpanel:"acl-basic-system-info,omitempty"`

	// Whether to allow the reseller to access basic cPanel & WHM options.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclBasicWHMFunctions *int64 `cpanel:"acl-basic-whm-functions,omitempty"`

	// Whether to allow the reseller to use DNS clusters.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclClustering *int64 `cpanel:"acl-clustering,omitempty"`

	// Whether to allow the reseller to perform Cross-Origin Resource Sharing (CORS) HTTP requests.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCorsProxyGet *int64 `cpanel:"acl-cors-proxy-get,omitempty"`

	// Whether to allow the reseller to execute cPanel API 1, cPanel API 2 and UAPI functions via WHM.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCpanelAPI *int64 `cpanel:"acl-cpanel-api,omitempty"`

	// Whether to allow the reseller to manage how their server and its services connect to other servers and services.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCpanelIntegration *int64 `cpanel:"acl-cpanel-integration,omitempty"`

	// Whether to allow the reseller to create accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCreateAcct *int64 `cpanel:"acl-create-acct,omitempty"`

	// Whether to allow the reseller to add DNS zones.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCreateDNS *int64 `cpanel:"acl-create-dns,omitempty"`

	// Whether to allow the reseller to create a temporary user session for a specified service.
	//
	// **Notes:**
	//
	//  This privilege allows an API token user to bypass any restrictions that you set on the API token. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclCreateUserSession *int64 `cpanel:"acl-create-user-session,omitempty"`

	// Whether to allow the reseller to enable demo mode for accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclDemoSetup *int64 `cpanel:"acl-demo-setup,omitempty"`

	// Whether to allow the reseller to manage Digest Authentication support.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclDigestAuth *int64 `cpanel:"acl-digest-auth,omitempty"`

	// Whether to allow the reseller to edit accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclEditAccount *int64 `cpanel:"acl-edit-account,omitempty"`

	// Whether to allow the reseller to edit DNS zones.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclEditDNS *int64 `cpanel:"acl-edit-dns,omitempty"`

	// Whether to allow the reseller to edit MX entries.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclEditMX *int64 `cpanel:"acl-edit-mx,omitempty"`

	// Whether to allow the reseller to edit hosting plans (packages).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclEditPkg *int64 `cpanel:"acl-edit-pkg,omitempty"`

	// Whether to allow the reseller to generate a mobile configuration profile for an email account.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclGenerateEmailConfig *int64 `cpanel:"acl-generate-email-config,omitempty"`

	// Whether to allow the reseller to terminate accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclKillAcct *int64 `cpanel:"acl-kill-acct,omitempty"`

	// Whether to allow the reseller to remove DNS zones.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclKillDNS *int64 `cpanel:"acl-kill-dns,omitempty"`

	// Whether to allow the reseller to modify bandwidth limits (quotas).
	//
	// **Warning:**
	//
	//  If you do not use resource limits, a value of `1` allows resellers to circumvent package limits for disk space.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclLimitBandwidth *int64 `cpanel:"acl-limit-bandwidth,omitempty"`

	// Whether to allow the reseller to view the list of accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclListAccts *int64 `cpanel:"acl-list-accts,omitempty"`

	// Whether to allow the reseller to view existing hosting plans (packages).
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclListPkgs *int64 `cpanel:"acl-list-pkgs,omitempty"`

	// Whether to allow the reseller to create and modify locales on the server.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclLocaleEdit *int64 `cpanel:"acl-locale-edit,omitempty"`

	// Whether to allow the reseller to troubleshoot mail delivery.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclMailcheck *int64 `cpanel:"acl-mailcheck,omitempty"`

	// Whether to allow the reseller to manage API tokens.
	//
	// **Notes:**
	//
	//  This privilege allows an API token user to bypass any restrictions that you set on the API token. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclManageAPITokens *int64 `cpanel:"acl-manage-api-tokens,omitempty"`

	// Whether to allow the reseller to manage DNS records.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclManageDNSRecords *int64 `cpanel:"acl-manage-dns-records,omitempty"`

	// Whether to allow the reseller to manage external authentication for their accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclManageOidc *int64 `cpanel:"acl-manage-oidc,omitempty"`

	// Whether to allow the reseller to manage their server's cPanel styles.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclManageStyles *int64 `cpanel:"acl-manage-styles,omitempty"`

	// Whether to allow the reseller to retrieve MySQL® database and user data.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclMysqlInfo *int64 `cpanel:"acl-mysql-info,omitempty"`

	// Whether to allow the reseller to modify the server's news.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclNews *int64 `cpanel:"acl-news,omitempty"`

	// Whether to allow the reseller to manage nameservers.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclNSConfig *int64 `cpanel:"acl-ns-config,omitempty"`

	// Whether to allow the reseller to park DNS zones.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclParkDNS *int64 `cpanel:"acl-park-dns,omitempty"`

	// Whether to allow the reseller to change passwords.
	//
	// **Note:**
	//
	//  This privilege allows an API token user to change account passwords and log in with a new password. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclPasswd *int64 `cpanel:"acl-passwd,omitempty"`

	// Whether to allow the reseller to modify quotas.
	//
	// **Warning:**
	//
	//  If you do not use resource limits, this privilege allows resellers to circumvent package limits for disk space.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclQuota *int64 `cpanel:"acl-quota,omitempty"`

	// Whether to allow the reseller to rearrange accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclRearrangeAccts *int64 `cpanel:"acl-rearrange-accts,omitempty"`

	// Whether to allow the reseller to resync FTP passwords.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclResftp *int64 `cpanel:"acl-resftp,omitempty"`

	// Whether to allow the reseller to restart services.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclRestart *int64 `cpanel:"acl-restart,omitempty"`

	// Whether to allow the reseller to view account bandwidth usage.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclShowBandwidth *int64 `cpanel:"acl-show-bandwidth,omitempty"`

	// Whether to allow the reseller to perform SSL site management.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclSSL *int64 `cpanel:"acl-ssl,omitempty"`

	// Whether to allow the reseller to purchase SSL certificates.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclSSLBuy *int64 `cpanel:"acl-ssl-buy,omitempty"`

	// Whether to allow the reseller to generate SSL certificates.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclSSLGencrt *int64 `cpanel:"acl-ssl-gencrt,omitempty"`

	// Whether to allow the reseller to view their server's SSL information.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclSSLInfo *int64 `cpanel:"acl-ssl-info,omitempty"`

	// Whether to allow the reseller to view server information.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclStats *int64 `cpanel:"acl-stats,omitempty"`

	// Whether to allow the reseller to view the server's status.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclStatus *int64 `cpanel:"acl-status,omitempty"`

	// Whether to allow the reseller to suspend or unsuspend accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclSuspendAcct *int64 `cpanel:"acl-suspend-acct,omitempty"`

	// Whether to allow the reseller to manage third-party services.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclThirdparty *int64 `cpanel:"acl-thirdparty,omitempty"`

	// Whether to allow the reseller to view reports about email message delivery attempts from their account.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclTrackEmail *int64 `cpanel:"acl-track-email,omitempty"`

	// Whether to allow the reseller to upgrade or downgrade accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclUpgradeAccount *int64 `cpanel:"acl-upgrade-account,omitempty"`

	// Whether to allow the reseller to use all global packages. For more information, read our [reseller packages](https://go.cpanel.net/GuidetoResellerAccounts#which-packages-can-resellers-view-and-assign) documentation.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	AclViewGlobalPackages *int64 `cpanel:"acl-viewglobalpackages,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SaveAcllist calls the WHM API 1 function `saveacllist` — Create or update privilege list and settings
//
// This function creates or modifies an Access Control List (ACL).
//
// **Note:**
//
//	For each `acl-*` parameter, a value of `1` adds that privilege to the ACL list and a value of `0` removes that privilege from the ACL list.
//
// **Warning:**
//
//	We **strongly** recommend that WHM users create and edit ACLs and ACL privileges through WHM's [*Edit Reseller Nameservers and Privileges*](https://go.cpanel.net/whmdocsEditResellerNameserversandPrivileges) interface ( *WHM >> Home >> Resellers >> Edit Reseller Nameservers and Privileges* ).
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-permissions/acls-saveacllist.md
func (c *Client) SaveAcllist(ctx context.Context, args *SaveAcllistArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "saveacllist", args)
}

// SetEnhancementLimitArgs are the parameters of the WHM API 1 function `set_enhancement_limit`.
type SetEnhancementLimitArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	Account string `cpanel:"account"`

	// The account enhancement's identifier.
	//
	// **Note:**
	// * You must use an [account enhancement](https://go.cpanel.net/account-enhancements) ID that a 3rd-party plugin defines.
	// * To return a list of valid account enhancement IDs, run the WHM API 1 `list_account_enhancements` function.
	//
	// This parameter is required.
	ID string `cpanel:"id"`

	// Whether the Account Enhancement assignment limit is unlimited.
	// * `0` - The assignment is unlimited.
	// * `1` - The assignment is limited.
	//
	// Possible values: `1`, `0`.
	//
	// This parameter is required.
	Limited int64 `cpanel:"limited"`

	// The account enhancement limit amount. This parameter is only
	// required if the `limited` parameter is `1`.
	Limit *int64 `cpanel:"limit,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetEnhancementLimit calls the WHM API 1 function `set_enhancement_limit` — Update account enhancement limit
//
// This function sets account enhancement limits for a reseller account.
//
// Available since cPanel & WHM version 11.98.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-enhancement-limit/accountenhancements-set_enhancement_limit.md
func (c *Client) SetEnhancementLimit(ctx context.Context, args *SetEnhancementLimitArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "set_enhancement_limit", args)
}

// SetPublicContactArgs are the parameters of the WHM API 1 function `set_public_contact`.
type SetPublicContactArgs struct {
	// The public contact name of the reseller. If you do not use this
	// parameter, the system retains the current setting.
	Name *string `cpanel:"name,omitempty"`

	// The public contact URL. If you do not use this parameter, the
	// system retains the current setting.
	URL *string `cpanel:"url,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetPublicContact calls the WHM API 1 function `set_public_contact` — Update current user's public contact information
//
// This function sets an account's public contact information.
//
// Available since cPanel & WHM version 68.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/publiccontact-set_public_contact.md
func (c *Client) SetPublicContact(ctx context.Context, args *SetPublicContactArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "set_public_contact", args)
}

// SetaclsArgs are the parameters of the WHM API 1 function `setacls`.
type SetaclsArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	Reseller string `cpanel:"reseller"`

	// Whether to allow the reseller to view an account summary.
	//
	// Possible values: `1`.
	AclAcctSummary *int64 `cpanel:"acl-acct-summary,omitempty"`

	// Whether to allow the reseller to add and remove hosting plans (packages).
	//
	// Possible values: `1`.
	AclAddPkg *int64 `cpanel:"acl-add-pkg,omitempty"`

	// Whether to allow the reseller to create packages with a dedicated IP address.
	//
	// Possible values: `1`.
	AclAddPkgIP *int64 `cpanel:"acl-add-pkg-ip,omitempty"`

	// Whether to allow the reseller to create packages with shell access.
	//
	// Possible values: `1`.
	AclAddPkgShell *int64 `cpanel:"acl-add-pkg-shell,omitempty"`

	// Whether to grant the reseller all ACL privileges.
	//
	// **Warning:**
	//
	//  A value of `1` grants `root`-level privileges to the reseller.
	//
	// Possible values: `1`.
	AclAll *int64 `cpanel:"acl-all,omitempty"`

	// Whether to allow the reseller to create packages with addon domains.
	//
	// Possible values: `1`.
	AclAllowAddoncreate *int64 `cpanel:"acl-allow-addoncreate,omitempty"`

	// Whether to allow the reseller to create packages with parked domains (aliases).
	//
	// Possible values: `1`.
	AclAllowParkedcreate *int64 `cpanel:"acl-allow-parkedcreate,omitempty"`

	// Whether to allow the reseller to create packages with unlimited bandwidth.
	//
	// Possible values: `1`.
	AclAllowUnlimitedBwPkgs *int64 `cpanel:"acl-allow-unlimited-bw-pkgs,omitempty"`

	// Whether to allow the reseller to create packages with unlimited disk space.
	//
	// Possible values: `1`.
	AclAllowUnlimitedDiskPkgs *int64 `cpanel:"acl-allow-unlimited-disk-pkgs,omitempty"`

	// Whether to allow the reseller to create packages with unlimited features.
	//
	// Possible values: `1`.
	AclAllowUnlimitedPkgs *int64 `cpanel:"acl-allow-unlimited-pkgs,omitempty"`

	// Whether to allow the reseller to retrieve basic system information.
	//
	// Possible values: `1`.
	AclBasicSystemInfo *int64 `cpanel:"acl-basic-system-info,omitempty"`

	// Whether to allow the reseller to access basic cPanel & WHM options.
	//
	// Possible values: `1`.
	AclBasicWHMFunctions *int64 `cpanel:"acl-basic-whm-functions,omitempty"`

	// Whether to allow the reseller to use DNS clusters.
	//
	// Possible values: `1`.
	AclClustering *int64 `cpanel:"acl-clustering,omitempty"`

	// Whether to allow the reseller to perform Cross-Origin Resource Sharing (CORS) HTTP requests.
	//
	// Possible values: `1`.
	AclCorsProxyGet *int64 `cpanel:"acl-cors-proxy-get,omitempty"`

	// Whether to allow the reseller to execute cPanel API 1, cPanel API 2 and UAPI functions via WHM.
	//
	// Possible values: `1`.
	AclCpanelAPI *int64 `cpanel:"acl-cpanel-api,omitempty"`

	// Whether to allow the reseller to manage how their server and its services connect to other servers and services.
	//
	// Possible values: `1`.
	AclCpanelIntegration *int64 `cpanel:"acl-cpanel-integration,omitempty"`

	// Whether to allow the reseller to create accounts.
	//
	// Possible values: `1`.
	AclCreateAcct *int64 `cpanel:"acl-create-acct,omitempty"`

	// Whether to allow the reseller to add DNS zones.
	//
	// Possible values: `1`.
	AclCreateDNS *int64 `cpanel:"acl-create-dns,omitempty"`

	// Whether to allow the reseller to create a temporary session user for a specified service.
	//
	// **Note:**
	//
	//  This privilege allows an API token user to bypass any restrictions that you set on the API token. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `1`.
	AclCreateUserSession *int64 `cpanel:"acl-create-user-session,omitempty"`

	// Whether to allow the reseller to enable demo mode for accounts.
	//
	// Possible values: `1`.
	AclDemoSetup *int64 `cpanel:"acl-demo-setup,omitempty"`

	// Whether to allow the reseller to manage Digest Authentication support.
	//
	// Possible values: `1`.
	AclDigestAuth *int64 `cpanel:"acl-digest-auth,omitempty"`

	// Whether to allow the reseller to create accounts with shell access.
	//
	// Possible values: `1`.
	AclDisallowShell *int64 `cpanel:"acl-disallow-shell,omitempty"`

	// Whether to allow the reseller to edit accounts.
	//
	// Possible values: `1`.
	AclEditAccount *int64 `cpanel:"acl-edit-account,omitempty"`

	// Whether to allow the reseller to edit DNS zones.
	//
	// Possible values: `1`.
	AclEditDNS *int64 `cpanel:"acl-edit-dns,omitempty"`

	// Whether to allow the reseller to edit MX entries.
	//
	// Possible values: `1`.
	AclEditMX *int64 `cpanel:"acl-edit-mx,omitempty"`

	// Whether to allow the reseller to edit hosting plans (packages).
	//
	// Possible values: `1`.
	AclEditPkg *int64 `cpanel:"acl-edit-pkg,omitempty"`

	// Whether to allow the reseller to generate a mobile configuration profile for an email account.
	//
	// Possible values: `1`.
	AclGenerateEmailConfig *int64 `cpanel:"acl-generate-email-config,omitempty"`

	// Whether to allow the reseller to terminate accounts.
	//
	// Possible values: `1`.
	AclKillAcct *int64 `cpanel:"acl-kill-acct,omitempty"`

	// Whether to allow the reseller to remove DNS zones.
	//
	// Possible values: `1`.
	AclKillDNS *int64 `cpanel:"acl-kill-dns,omitempty"`

	// Whether to allow the reseller to modify bandwidth limits (quotas).
	//
	// **Warning:**
	//
	//  If you do **not** use resource limits, a value of `1` allows resellers to circumvent package limits for disk space.
	//
	// Possible values: `1`.
	AclLimitBandwidth *int64 `cpanel:"acl-limit-bandwidth,omitempty"`

	// Whether to allow the reseller to view the list of accounts.
	//
	// Possible values: `1`.
	AclListAccts *int64 `cpanel:"acl-list-accts,omitempty"`

	// Whether to allow the reseller to view existing hosting plans (packages).
	//
	// Possible values: `1`.
	AclListPkgs *int64 `cpanel:"acl-list-pkgs,omitempty"`

	// Whether to allow the reseller to create and modify locales on the server.
	//
	// Possible values: `1`.
	AclLocaleEdit *int64 `cpanel:"acl-locale-edit,omitempty"`

	// Whether to allow the reseller to troubleshoot mail delivery.
	//
	// Possible values: `1`.
	AclMailcheck *int64 `cpanel:"acl-mailcheck,omitempty"`

	// Whether to allow the reseller to manage API tokens.
	//
	// **Note:**
	//
	//  This privilege allows an API token user to bypass any restrictions that you set on the API token. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `1`.
	AclManageAPITokens *int64 `cpanel:"acl-manage-api-tokens,omitempty"`

	// Whether to allow the reseller to manage DNS records.
	//
	// Possible values: `1`.
	AclManageDNSRecords *int64 `cpanel:"acl-manage-dns-records,omitempty"`

	// Whether to allow the reseller to manage external authentication for their accounts.
	//
	// Possible values: `1`.
	AclManageOidc *int64 `cpanel:"acl-manage-oidc,omitempty"`

	// Whether to allow the reseller to manage their server's cPanel styles.
	//
	// Possible values: `1`.
	AclManageStyles *int64 `cpanel:"acl-manage-styles,omitempty"`

	// Whether to allow the reseller to retrieve MySQL® database and user data.
	//
	// Possible values: `1`.
	AclMysqlInfo *int64 `cpanel:"acl-mysql-info,omitempty"`

	// Whether to allow the reseller to manage nameservers.
	//
	// Possible values: `1`.
	AclNameserverConfig *int64 `cpanel:"acl-nameserver-config,omitempty"`

	// Whether to allow the reseller to modify the server's news.
	//
	// Possible values: `1`.
	AclNews *int64 `cpanel:"acl-news,omitempty"`

	// Whether to allow the reseller to park DNS zones.
	//
	// Possible values: `1`.
	AclParkDNS *int64 `cpanel:"acl-park-dns,omitempty"`

	// Whether to allow the reseller to change passwords.
	//
	// **Note:**
	//
	//  This privilege allows an API token user to change account passwords and log in with a new password. For more information, read our [Manage API Tokens](https://go.cpanel.net/whmdocsManageasisAPITokens) documentation.
	//
	// Possible values: `1`.
	AclPasswd *int64 `cpanel:"acl-passwd,omitempty"`

	// Whether to allow the reseller to modify quotas.
	//
	// **Warning:**
	//
	//  If you do **not** use resource limits, a value of `1` allows resellers to circumvent package limits for disk space.
	//
	// Possible values: `1`.
	AclQuota *int64 `cpanel:"acl-quota,omitempty"`

	// Whether to allow the reseller to rearrange accounts.
	//
	// Possible values: `1`.
	AclRearrangeAccts *int64 `cpanel:"acl-rearrange-accts,omitempty"`

	// Whether to allow the reseller to resync FTP passwords.
	//
	// Possible values: `1`.
	AclResftp *int64 `cpanel:"acl-resftp,omitempty"`

	// Whether to allow the reseller to restart services.
	//
	// Possible values: `1`.
	AclRestart *int64 `cpanel:"acl-restart,omitempty"`

	// Whether to allow the reseller to view account bandwidth usage.
	//
	// Possible values: `1`.
	AclShowBandwidth *int64 `cpanel:"acl-show-bandwidth,omitempty"`

	// Whether to allow the reseller to perform SSL site management.
	//
	// Possible values: `1`.
	AclSSL *int64 `cpanel:"acl-ssl,omitempty"`

	// Whether to allow the reseller to purchase SSL certificates.
	//
	// Possible values: `1`.
	AclSSLBuy *int64 `cpanel:"acl-ssl-buy,omitempty"`

	// Whether to allow the reseller to generate SSL certificates.
	//
	// Possible values: `1`.
	AclSSLGencrt *int64 `cpanel:"acl-ssl-gencrt,omitempty"`

	// Whether to allow the reseller to view their server's SSL information.
	//
	// Possible values: `1`.
	AclSSLInfo *int64 `cpanel:"acl-ssl-info,omitempty"`

	// Whether to allow the reseller to view server information.
	//
	// Possible values: `1`.
	AclStats *int64 `cpanel:"acl-stats,omitempty"`

	// Whether to allow the reseller to view the server's status.
	//
	// Possible values: `1`.
	AclStatus *int64 `cpanel:"acl-status,omitempty"`

	// Whether to allow the reseller to suspend or unsuspend accounts.
	//
	// Possible values: `1`.
	AclSuspendAcct *int64 `cpanel:"acl-suspend-acct,omitempty"`

	// Whether to allow the reseller to manage third-party services.
	//
	// Possible values: `1`.
	AclThirdparty *int64 `cpanel:"acl-thirdparty,omitempty"`

	// Whether to allow the reseller to view reports about email message delivery attempts from their account.
	//
	// Possible values: `1`.
	AclTrackEmail *int64 `cpanel:"acl-track-email,omitempty"`

	// Whether to allow the reseller to upgrade or downgrade accounts.
	//
	// Possible values: `1`.
	AclUpgradeAccount *int64 `cpanel:"acl-upgrade-account,omitempty"`

	// Whether to allow the reseller to use all global packages. For more information, read our [reseller packages](https://go.cpanel.net/resellerpackages) documentation.
	//
	// Possible values: `1`.
	AclViewGlobalPackages *int64 `cpanel:"acl-viewglobalpackages,omitempty"`

	// The ACL to assign to the reseller.
	//
	// **Warning:**
	//
	//  Functions should **either** use this parameter, or a combination of the `acl-*` parameters below. **Do not** include both in a single function.
	Acllist *string `cpanel:"acllist,omitempty"`

	// The reseller's username.
	//
	// **Note:**
	//
	// This parameter is an alias for `reseller` and is provided for backwards compatibility.
	User *string `cpanel:"user,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// Setacls calls the WHM API 1 function `setacls` — Create or update reseller privilege settings
//
// This function creates or modifies an Access Control List (ACL).
//
// **Note:**
//
//	For each `acl-*` parameter, any value adds that privilege to the ACL list and no value removes that privilege from the ACL list.
//
// **Warning:**
//
//	We **strongly** recommend that WHM users create and edit ACLs and ACL privileges through WHM's [*Edit Reseller Nameservers and Privileges*](https://go.cpanel.net/whmdocsEditResellerNameserversandPrivileges) interface ( *WHM >> Home >> Resellers >> Edit Reseller Nameservers and Privileges* ).
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-permissions/resellers-setacls.md
func (c *Client) Setacls(ctx context.Context, args *SetaclsArgs) (*cpanel.WHMResult[SetaclsData], error) {
	return cpanel.WHMCall[SetaclsData](ctx, c.c, http.MethodGet, "setacls", args)
}

// SetaclsData is a generated payload type.
type SetaclsData struct {
	// An array of the reseller's privileges. An array that contains the names of one or more privileges.
	Acl []string `json:"acl"`
}

// SetResellerIPsArgs are the parameters of the WHM API 1 function `setresellerips`.
type SetResellerIPsArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to allocate the reseller a dedicated IP address.
	//
	// * `1` — Restrict the reseller's account to its dedicated IP address.
	// * `0` — Allow the user to dedicate any available IP address to an owned account.
	//
	// Possible values: `1`.
	//
	// Defaults to `0`.
	Delegate *int64 `cpanel:"delegate,omitempty"`

	// The IP addresses to allocate to the reseller's account.
	//
	// **Note:**
	//
	// * If you do **not** use this parameter, the function clears the reseller's IP address list.
	// * Use a comma-separated list to allocate multiple IP addresses.
	IPs *string `cpanel:"ips,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetResellerIPs calls the WHM API 1 function `setresellerips` — Add IP addresses to reseller
//
// This function adds IP addresses to a reseller's account.
//
// **Note:**
//
// To assign a main IP address to a reseller's account, call the WHM API 1 `setresellermainip` function.
//
// For more information, read our [Manage Reseller's IP Delegation](https://go.cpanel.net/whmdocsManageResellersIPDelegation) documentation.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-setresellerips.md
func (c *Client) SetResellerIPs(ctx context.Context, args *SetResellerIPsArgs) (*cpanel.WHMResult[SetResellerIPsData], error) {
	return cpanel.WHMCall[SetResellerIPsData](ctx, c.c, http.MethodGet, "setresellerips", args)
}

// SetResellerIPsData is a generated payload type.
type SetResellerIPsData struct {
	// Whether the function allocated all available IP addresses to the reseller. This return **only** appears if you set the `delegate` parameter to `0`.
	//
	// **Note:**
	//
	// `1` is the only possible value.
	//
	// Possible values: `1`.
	All int64 `json:"all"`

	// An array of the reseller's allocated IP addresses.
	IP []string `json:"ip"`
}

// SetResellerLimitsArgs are the parameters of the WHM API 1 function `setresellerlimits`.
type SetResellerLimitsArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// The reseller's maximum total number of accounts.
	//
	// **Important:**
	//
	// The system **only** enforces this maximum if you set the `enable_account_limit`
	// value to `1`.
	AccountLimit *int64 `cpanel:"account_limit,omitempty"`

	// The reseller's total bandwidth limit.
	//
	// **Important:**
	//
	// The system **only** enforces this limit if you set the `enable_resource_limits`
	// value to `1`.
	BandwidthLimit *int64 `cpanel:"bandwidth_limit,omitempty"`

	// The reseller's total disk space usage limit.
	//
	// **Important:**
	//
	// The system **only** enforces this limit if you set the `enable_resource_limits`
	// value to `1`.
	DiskspaceLimit *int64 `cpanel:"diskspace_limit,omitempty"`

	// Whether to limit the reseller's total number of accounts.
	//
	// * `1` — Limit.
	// * `0` — Do **not** limit.
	//
	// **Note:**
	//
	// Use this parameter with the `account_limit` parameter.
	//
	// Possible values: `1`, `0`.
	//
	// Defaults to `0`.
	EnableAccountLimit *int64 `cpanel:"enable_account_limit,omitempty"`

	// Whether the reseller can oversell accounts.
	//
	// * `1` — The reseller can oversell accounts.
	// * `0` — The reseller **cannot** oversell accounts.
	//
	// **Important:**
	//
	// The system **only** enforces this limit if you set the `enable_resource_limits`
	// value to `1`.
	//
	// Possible values: `1`, `0`.
	EnableOverselling *int64 `cpanel:"enable_overselling,omitempty"`

	// Whether the reseller can oversell bandwidth.
	//
	// * `1` — The reseller can oversell bandwidth.
	// * `0` — The reseller **cannot** oversell bandwidth.
	//
	// **Important:**
	//
	// The system **only** enforces this limit if you set the `enable_resource_limits` and
	// the `enable_overselling` values to `1`.
	//
	// Possible values: `1`, `0`.
	EnableOversellingBandwidth *int64 `cpanel:"enable_overselling_bandwidth,omitempty"`

	// Whether the reseller can oversell disk space.
	//
	// * `1` — The reseller can oversell disk space.
	// * `0` — The reseller **cannot** oversell disk space.
	//
	// **Important:**
	//
	// The system **only** enforces this limit if you set the `enable_resource_limits`
	// and the `enable_oversellng` values to `1`.
	//
	// Possible values: `1`, `0`.
	EnableOversellingDiskspace *int64 `cpanel:"enable_overselling_diskspace,omitempty"`

	// Whether to apply package limit numbers to the reseller.
	//
	// * `1` — Enable package limit numbers.
	// * `0` — Disable package limit numbers.
	//
	// Possible values: `1`, `0`.
	EnablePackageLimitNumbers *int64 `cpanel:"enable_package_limit_numbers,omitempty"`

	// Whether to apply package limits to the reseller.
	//
	// * `1` — Enable package limits.
	// * `0` — Disable package limits.
	//
	// Possible values: `1`, `0`.
	EnablePackageLimits *int64 `cpanel:"enable_package_limits,omitempty"`

	// Whether to limit the reseller's resources.
	//
	// * `1` — Limit resources.
	// * `0` — Do **not** limit resources.
	//
	// **Note:**
	//
	// Use this parameter with the `bandwidthlimit`, `diskspace_limit`,
	// `enable_overselling`, `enable_overselling_bandwidth`, `enable_overselling_diskspace`,
	// `enable_overselling`, `enable_package_limits`, and `enable_package_limit_numbers`
	// parameters.
	//
	// Possible values: `1`, `0`.
	//
	// Defaults to `0`.
	EnableResourceLimits *int64 `cpanel:"enable_resource_limits,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetResellerLimits calls the WHM API 1 function `setresellerlimits` — Update reseller's bandwidth and disk quotas
//
// This function sets a reseller's bandwidth and disk quotas.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-limits/resellers-setresellerlimits.md
func (c *Client) SetResellerLimits(ctx context.Context, args *SetResellerLimitsArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "setresellerlimits", args)
}

// SetResellerMainIPArgs are the parameters of the WHM API 1 function `setresellermainip`.
type SetResellerMainIPArgs struct {
	// The IP address to assign to the reseller's account as the main shared IP address.
	//
	// This parameter is required.
	IP string `cpanel:"ip"`

	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetResellerMainIP calls the WHM API 1 function `setresellermainip` — Update reseller's main IP address
//
// This function assigns a main IP address to a reseller's account.
//
// **Note:**
//
//	To assign additional IP addresses to a reseller's account, call the WHM API 1 `setresellerips` function.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-setresellermainip.md
func (c *Client) SetResellerMainIP(ctx context.Context, args *SetResellerMainIPArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "setresellermainip", args)
}

// SetResellerNameserversArgs are the parameters of the WHM API 1 function `setresellernameservers`.
type SetResellerNameserversArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// A comma-separated list of the nameserver domains to assign to the reseller's account.
	//
	// **Note:**
	//
	// If you do **not** use this parameter, the function resets the reseller's nameservers
	// to use the server default.
	Nameservers *string `cpanel:"nameservers,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetResellerNameservers calls the WHM API 1 function `setresellernameservers` — Update reseller's assigned nameservers
//
// This function assigns nameservers to a reseller's account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-settings/resellers-setresellernameservers.md
func (c *Client) SetResellerNameservers(ctx context.Context, args *SetResellerNameserversArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "setresellernameservers", args)
}

// SetResellerPackageLimitArgs are the parameters of the WHM API 1 function `setresellerpackagelimit`.
type SetResellerPackageLimitArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether the reseller can access the package hosting plan.
	// * `1` — Enable access.
	// * `0` — Disable access
	//
	// **Note:**
	//
	// If you use this parameter, you **must** also include the `package` parameter.
	//
	// Possible values: `0`, `1`.
	Allowed *int64 `cpanel:"allowed,omitempty"`

	// Whether to grant the reseller unlimited package use.
	// * `1` — Grant the reseller unlimited package use.
	// * `0` — Use package limits.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	NoLimit *int64 `cpanel:"no_limit,omitempty"`

	// The maximum number of accounts to which the reseller can assign the package hosting plan.
	//
	// **Note:**
	//
	// * If you use this parameter, you **must** also include the `package` parameter.
	// * If you set a value for this parameter **and** set the `allowed` parameter to `0`, the reseller **cannot** use the hosting plan.
	Number *int64 `cpanel:"number,omitempty"`

	// A hosting plan (package), to modify the reseller's access settings for it.
	//
	// **Note:**
	//
	//  Use this parameter with the `number` or `allowed` parameters.
	Package2 *string `cpanel:"package,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetResellerPackageLimit calls the WHM API 1 function `setresellerpackagelimit` — Update reseller's hosting plan limits
//
// This function limits the packages that a reseller assigns to cPanel accounts.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/account-limits/resellers-setresellerpackagelimit.md
func (c *Client) SetResellerPackageLimit(ctx context.Context, args *SetResellerPackageLimitArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "setresellerpackagelimit", args)
}

// SetupResellerArgs are the parameters of the WHM API 1 function `setupreseller`.
type SetupResellerArgs struct {
	// The account's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to set the account to own itself.
	// * `1` — Make the account own itself.
	// * `0` — Keep the account's current owner.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	MakeOwner *int64 `cpanel:"makeowner,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SetupReseller calls the WHM API 1 function `setupreseller` — Enable cPanel account's reseller status
//
// This function grants reseller status to an account.
//
// **Note:**
//
// This function grants reseller status to an **existing** account. You **cannot** create a new account with this function.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/reseller-account-management/resellers-setupreseller.md
func (c *Client) SetupReseller(ctx context.Context, args *SetupResellerArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "setupreseller", args)
}

// SuspendResellerArgs are the parameters of the WHM API 1 function `suspendreseller`.
type SuspendResellerArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to allow only the `root` user to unsuspend the account.
	// * `1` — **Only** the `root` user can unsuspend the account.
	// * `0` — The `root` user or the account's owner can unsuspend the account.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	Disallow *int64 `cpanel:"disallow,omitempty"`

	// The reason for the reseller's suspension.
	//
	// **Note:**
	//
	//  We **strongly** recommend that you **always** include a reason for suspension.
	Reason *string `cpanel:"reason,omitempty"`

	// Whether to suspend only the reseller account.
	// * `1` — The function **only** suspends the reseller account. The function will **not** suspend the accounts that the reseller account owns.
	// * `0` — The function suspends the reseller account **and** the accounts that it owns.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ResellerOnly *int64 `cpanel:"reseller-only,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SuspendReseller calls the WHM API 1 function `suspendreseller` — Suspend reseller
//
// This function suspends a reseller account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/reseller-account-management/resellers-suspendreseller.md
func (c *Client) SuspendReseller(ctx context.Context, args *SuspendResellerArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "suspendreseller", args)
}

// TerminateResellerArgs are the parameters of the WHM API 1 function `terminatereseller`.
type TerminateResellerArgs struct {
	// Whether to terminate the reseller's main account.
	//
	// * `1` — Terminate.
	// * `0` — Do **not** terminate.
	//
	// Possible values: `1`, `0`.
	//
	// This parameter is required.
	TerminateReseller int64 `cpanel:"terminatereseller"`

	// The reseller account's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// TerminateReseller calls the WHM API 1 function `terminatereseller` — Delete reseller and reseller's cPanel accounts
//
// This function deletes a reseller and **all** of the reseller's cPanel accounts.
//
// **Warning:**
//
// * You **cannot** recover deleted accounts. **Use this function with extreme caution.**
// * This function deletes the reseller account and **all** of the accounts that the reseller
// owns.
// * To remove reseller privileges from an account but **not** delete the reseller's account
// or any accounts that the reseller owns, use the WHM API 1 `unsetupreseller` function.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/reseller-account-management/resellers-terminatereseller.md
func (c *Client) TerminateReseller(ctx context.Context, args *TerminateResellerArgs) (*cpanel.WHMResult[TerminateResellerData], error) {
	return cpanel.WHMCall[TerminateResellerData](ctx, c.c, http.MethodGet, "terminatereseller", args)
}

// An object containing the termination data for the reseller's accounts.
type TerminateResellerDataAcctItemOutput struct {
	// Output from the account's removal.
	//
	// **Note:**
	//
	// This output may contain HTML.
	Raw string `json:"raw"`
}

// TerminateResellerDataAcctItem is a generated payload type.
type TerminateResellerDataAcctItem struct {
	// An object containing the termination data for the reseller's accounts.
	Output TerminateResellerDataAcctItemOutput `json:"output"`

	// A message of success or the reason for a failure.
	Reason string `json:"reason"`

	// Whether the function succeeded.
	//
	// * `1` — Success.
	// * `0` — Failure.
	//
	// Possible values: `1`, `0`.
	Result int64 `json:"result"`

	// The account username.
	User string `json:"user"`
}

// TerminateResellerData is a generated payload type.
type TerminateResellerData struct {
	// An array of objects containing the function's output.
	Acct []TerminateResellerDataAcctItem `json:"acct"`
}

// UnsetupResellerArgs are the parameters of the WHM API 1 function `unsetupreseller`.
type UnsetupResellerArgs struct {
	// The reseller account's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UnsetupReseller calls the WHM API 1 function `unsetupreseller` — Disables cPanel account's reseller status
//
// This function revokes reseller status from an account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/reseller-account-management/resellers-unsetupreseller.md
func (c *Client) UnsetupReseller(ctx context.Context, args *UnsetupResellerArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "unsetupreseller", args)
}

// UnsuspendResellerArgs are the parameters of the WHM API 1 function `unsuspendreseller`.
type UnsuspendResellerArgs struct {
	// The reseller's username.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to unsuspend only the reseller account.
	// * `1` — The function **only** unsuspends the reseller account. The function will **not** unsuspend the accounts that the reseller account owns.
	// * `0` — The function unsuspends the reseller account **and** the accounts that it owns.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	ResellerOnly *int64 `cpanel:"reseller-only,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UnsuspendReseller calls the WHM API 1 function `unsuspendreseller` — Unsuspend reseller
//
// This function unsuspends a reseller account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/reseller-account-management/resellers-unsuspendreseller.md
func (c *Client) UnsuspendReseller(ctx context.Context, args *UnsuspendResellerArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "unsuspendreseller", args)
}
