// Code generated by go-cpanel/tools/gen from the official
// cPanel & WHM OpenAPI documents. DO NOT EDIT.
// Source: https://api.docs.cpanel.net (cPanel & WHM version 138)

package whm

import (
	"context"
	"encoding/json"
	"net/http"

	cpanel "github.com/fmotalleb/go-cpanel"
)

// ListLockedAccounts calls the WHM API 1 function `listlockedaccounts` — Return suspended cPanel accounts
//
// This function lists locked accounts on the server. **Only** WHM users with
// `root`-level privileges can unsuspend locked accounts.
//
// Available since cPanel & WHM version 11.40.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/suspensions/accounts-listlockedaccounts.md
func (c *Client) ListLockedAccounts(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ListLockedAccountsData], error) {
	return cpanel.WHMCall[ListLockedAccountsData](ctx, c.c, http.MethodGet, "listlockedaccounts", cpanel.CombineArgs(extra...))
}

// ListLockedAccountsData is a generated payload type.
type ListLockedAccountsData struct {
	// A list of locked accounts on the server.
	Account []string `json:"account"`
}

// ListSuspended calls the WHM API 1 function `listsuspended` — Return suspended cPanel accounts and information
//
// This function lists suspended accounts on the server.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/suspensions/accounts-listsuspended.md
func (c *Client) ListSuspended(ctx context.Context, extra ...cpanel.Args) (*cpanel.WHMResult[ListSuspendedData], error) {
	return cpanel.WHMCall[ListSuspendedData](ctx, c.c, http.MethodGet, "listsuspended", cpanel.CombineArgs(extra...))
}

// ListSuspendedDataAccountItem is a generated payload type.
type ListSuspendedDataAccountItem struct {
	// Whether the account is locked.
	// * `1` - Locked.
	// * `0` - Not locked.
	//
	// Possible values: `0`, `1`.
	IsLocked int64 `json:"is_locked"`

	// The cPanel account's owner.
	// - `root`
	// - A reseller's username.
	// - The account's username.
	Owner string `json:"owner"`

	// The reason why the account is suspended, if one exists.
	Reason string `json:"reason"`

	// The current date and time in `Day Mon DD HH:mm:SS YYYY` human-readable format, where:
	// * `Day` - represents the day of the week as a three-letter abbreviation.
	// * `Mon` - represents the month's three-letter abbreviation.
	// * `DD` - represents the date.
	// * `HH` - represents the hour.
	// * `mm` - represents the minute.
	// * `SS` - represents the second.
	// * `YYYY` - represents the year.
	Time string `json:"time"`

	// The current date and time.
	Unixtime int64 `json:"unixtime"`

	// The cPanel account's username.
	User string `json:"user"`
}

// ListSuspendedData is a generated payload type.
type ListSuspendedData struct {
	// A list of objects containing suspended account data.
	Account []ListSuspendedDataAccountItem `json:"account"`
}

// SuspendAcctArgs are the parameters of the WHM API 1 function `suspendacct`.
type SuspendAcctArgs struct {
	// The account to suspend.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to allow only the `root` user to unsuspend the account.
	// * `1` - **Only** the `root` user can unsuspend the account.
	// * `0` - The `root` user or the account's owner can unsuspend the account.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	DisallowUn *int64 `cpanel:"disallowun,omitempty"`

	// Whether to skip suspension of the account's FTP accounts.
	// * `1` - Do **not** suspend the FTP accounts.
	// * `0` - Suspend the FTP accounts.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	LeaveFTPAcctsEnabled *int64 `cpanel:"leave-ftp-accts-enabled,omitempty"`

	// The reason for suspension.
	//
	// **Important:**
	//
	//  We strongly recommend that you provide a reason for suspension whenever you suspend an account.
	//
	// Defaults to `Unknown`.
	Reason *string `cpanel:"reason,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// SuspendAcct calls the WHM API 1 function `suspendacct` — Suspend cPanel account
//
// This function suspends an account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/suspensions/accounts-suspendacct.md
func (c *Client) SuspendAcct(ctx context.Context, args *SuspendAcctArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "suspendacct", args)
}

// UnsuspendAcctArgs are the parameters of the WHM API 1 function `unsuspendacct`.
type UnsuspendAcctArgs struct {
	// The account to unsuspend.
	//
	// This parameter is required.
	User string `cpanel:"user"`

	// Whether to retain any [service proxies](https://go.cpanel.net/serviceproxyglossary) on an account.
	// * `1` — Retain service proxies.
	// * `0` — Do **not** retain service proxies.
	//
	// Possible values: `0`, `1`.
	//
	// Defaults to `0`.
	RetainServiceProxies *int64 `cpanel:"retain-service-proxies,omitempty"`

	// Extra carries any additional arguments (e.g. UAPI/WHM meta arguments such as api.filter.*, api.sort.*, api.paginate.*).
	Extra cpanel.Args `cpanel:"-"`
}

// UnsuspendAcct calls the WHM API 1 function `unsuspendacct` — Unsuspend cPanel account
//
// This function unsuspends an account.
//
// **Note:**
//
// **Only** the `root` account and `root`-enabled resellers can unsuspend a locked account.
//
// Available since cPanel & WHM version 11.
//
// Documentation: https://api.docs.cpanel.net/specifications/whm.openapi/suspensions/accounts-unsuspendacct.md
func (c *Client) UnsuspendAcct(ctx context.Context, args *UnsuspendAcctArgs) (*cpanel.WHMResult[json.RawMessage], error) {
	return cpanel.WHMCall[json.RawMessage](ctx, c.c, http.MethodGet, "unsuspendacct", args)
}
